# Simplicial Complex Analysis

<span style='color:Red'>TODO: Generate a system to analyze the largest shape per stratum per year.</span> <br>
<span style='color:Red'> Currently using the largest number of nodes in each shape. </span> <br> 
Written by Frederick Miller, Casey McKean, and Wako Bungula. <br> 
The kepler mapper object gives an output that is not easily navigatible. To resolve this, we wish to create shapes that are easier to navigate and understand, and reveal the data inside of them. <br>
We generate all the shapes in the simplicial complex, condense 1-simplices where possible, and obtain summary statistics on the shapes and the nodes within the shapes.

In [1]:
import numpy as np
import pandas as pd 
import queue
import animation
import json
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', None)
import pickle
print("Imports Done")

Imports Done

# File paths, `.p`, and `.json` import

From the `kmapper_demo` file, I added one extra code block to place the resulting simplicial complices in a `.json` file, which is a way to store dictionaries in long term storage. Additionally, it stores the dictionary of dataframes in a `.p` file, which is similar. The code below only needs to have the file paths changed, and then it will read the simplicial complices generated from kepler mapper. <br>
Here, we also import the actual data set, with data interpolated for the specific pool. <br>
Lastly, a list of the 11 continuous variables (the interpolated versions) is created.

In [2]:
jsonFilePath = r"C:\Users\forre\Desktop\REU\TDA\Data\TDAOutputs\TDA1PCA10Cubes30perc_complices.json"
jsonFile = open(jsonFilePath, "r")
jsonData = json.load(jsonFile) 
jsonFile.close()

dataFilePath = r"C:\Users\forre\Desktop\REU\TDA\Data\TDAOutputs\TDA1PCA10Cubes30perc_dfs.p"
df_dict = pickle.load(open(dataFilePath, "rb"))

variables = ["PredictedWDP", "PredictedSECCHI", "PredictedTEMP", "PredictedDO", 
           "PredictedTURB", "PredictedVEL", "PredictedTP", #"PREDICTED_COND",
           "PredictedTN", "PredictedSS", "PredictedCHLcal"]

variables = ["PREDICTED_WDP", "PREDICTED_SECCHI", "PREDICTED_TEMP", "PREDICTED_DO", 
           "PREDICTED_TURB", "PREDICTED_VEL", "PREDICTED_TP", #"PREDICTED_COND",
           "PREDICTED_TN", "PREDICTED_SS", "PREDICTED_CHLcal"]



print("Json file imported")

print(len(jsonData.keys()))

Json file imported
25

# Functions
See the `docstring`'s for what each function does and how it works.

In [22]:
def getSubdf(scomplex, shape, df):
    """
    Returns the part of the data frame from the particular shape in the simplicial complex.
    params:
    scomplex: the entire simplicial complex
    shape: the particular shape being inspected (within the simplicial complex)
    df: the entire data frame
    
    Description:
    1. Get all the nodes from the particular simplicial complex. 
    2. Generate the indices we care about from the particular shape. To do this, we read each node and append it's 
    indices to a list. Then, we convert the list to a set and then back to a list to eliminate duplicates.
    3. Return the dataframe with only those indices.
    """
    nodes = scomplex.get('nodes')
    indices = []
    npShape = np.array(shape).flatten()
    for node in npShape:
        indices.append(nodes.get(node))
    indices = list(set([item for sublist in indices for item in sublist]))
    subdf = df.loc[indices]
    return subdf

def shapeDataSummary(scomplex, shape, df, variables, verbose = False):
    """
    Generates summary statistics of the given variables for a given shape in the simplicial.
    params:
    scomplex: the entire simplicial complex
    shape: the particular shape being inspected (within the simplicial complex) at this function call.
    df: the entire dataframe
    variables: the variables of interest
    verbose: Determines if the function will print out extra information. False by default
    
    Description:
    1. Create an empty result dataframe to store the summary statistics.
    2. Get the sub dataframe (see getSubdf) for the particular shape
    3. For each variable we are analzying, generate summary statistics from the sub dataframe and place them
    inside the result dataframe.
    4. Return the result dataframe
    
    NOTE: this only creates summaries for one particular shape. In executing this method, it is done for each shape 
    outside of the function.
    
    """
    result = pd.DataFrame()
    if verbose == True:
        print("Obtaining sub dataframe for: ", shape)
        print("The number of nodes in this shape is: ", len(shape))
    subdf = getSubdf(scomplex, shape, df)
    if verbose == True:
        print("The number of datapoints in this shape is: ", subdf.shape[0])
    for var in variables:
        result[var] = subdf[var].describe()
    return result
    
    

def adjacent(v, scomplex):
    """
    Determines the nodes adjacent to a given vertex
    
    params:
    v: vertex
    scomlex: the entire simplicial complex
    
    Description:
    Determines the nodes that are adjacent to a given vertex.
    """
    
    simplices = scomplex.get('simplices')
    edges = [item for item in simplices if len(item) == 2]
    result = []
    for edge in edges:
        if v in edge:
            for item in edge:
                if item != v:
                    result.append(item)
    return result

def bfs(node, scomplex):
    """
    Conducts a breadth first search to obtain the entire shape from a given node
    params:
    node: the start node
    scomplex: the entire simplicial complex
    
    Description:
    Preforms a breadth first search to obtain the entire shape for a given start node.
    """
    Q = queue.Queue()
    result = []
    result.append(node)
    Q.put(node)
    while not Q.empty():
        v = Q.get()
        adjacentEdges = adjacent(v, scomplex)
        for edge in adjacentEdges:
            if edge not in result:
                result.append(edge)
                Q.put(edge)
    return result


        
    
def getShapes(scomplex):
    """
    Gets all of the shapes from a given simplicial complex.
    
    params:
    scomplex: the entire simplicial complex
    
    Description:
    1. Obtain all the nodes for the entire complex
    2. For each node, preform a breadth first search to obtain everything in that particular shape. 
    If this entire shape has not already been discovered, add it to the set of results. 
    The result item is a set as the order of the shapes does not matter. The resulting shape is a frozenset
    which means items cannot be added or removed once created, and is needed to allow the set object to have other sets within it.
    3. Convert each shape to a list and the result to a list for easier navigation outside of the function.
    4. Return the result
    
    """
    
    nodes = list(scomplex.get('nodes').keys())
    result = set()
    for node in nodes: # currently does more computations than necessary due to going through every node without considering it is already in a shape
        bfsResult = frozenset(bfs(node, scomplex))
        result.add(bfsResult)
    result = [list(x) for x in result]
    # Sort the list depending on what is decided: nodes or indices. Currently doing it by number of nodes
    result.sort(key = len, reverse = True)
    
    
    
    return result

def nodeDataSummary(node, scomplex, variables,df):
    """
    Returns a data summary of a particular node
    params:
    node: node in question
    scomplex: The entire simplicial complex
    variables: The variables to obtain summaries
    df: the entire dataframe 
    
    description:
    1. Creates a result dataframe
    2. Get all the indices from the node from the simplicial complex
    3. Generate summaries for each variable
    4. Return the result
    """
    result = pd.DataFrame()
    indices = scomplex.get('nodes').get(node)
    subdf = df.loc[indices]
    for var in variables:
        result[var] = subdf[var].describe()
    return result
    
    
def condenseShape(shape, scomplex):
    """
    
    params:
    shape: a shape of two nodes. must be 2
    scomplex: the entire simplicial complex
    
    description:
    gets the two nodes a and b
    gets the indices for a and b (what is inside the nodes)
    if a \subseteq b, return b
    elif b \subseteq a, return a 
    else return shape 
    
    """
    nodes = scomplex.get('nodes')
    a = shape[0]
    b = shape[1]
    aIndices = set(nodes.get(a))
    bIndices = set(nodes.get(b))
    
    if aIndices.issubset(bIndices):
        return b
    elif bIndices.issubset(aIndices):
        return a
    else:
        return shape

def clean_getShapes(scomplex):
    """
    Condenses 1-simplices down to 0-simplices when each node 
    is a subset of the other 
    
    params:
    scomplex: the entire simplicial complex
    
    Description:
    1. Get all the shapes from the original getShapes function
    2. For shapes that of length 2, if one is a subset of the other, return the larger of the two
        Otherwise, do nothing
    3. return the clean Shapes list 
    
    """
    shapes = getShapes(scomplex)
    cleanShapes = []
    for shape in shapes:
        if len(shape) == 2:
            shape = condenseShape(shape, scomplex)
            cleanShapes.append([shape])
        else:
            cleanShapes.append(shape)
    return cleanShapes


def getBoxplots(subdf, shape, key,filePath):
    """
    Generates box plots for 10 of the 11 continuous variables
    NOTE: CONDUCTIVITY IS NOT INCLUDED
    
    params:
    subdf: the sub dataframe of the particular shape
    shape: the shape in question
    key: what strata year season combo we are looking at 
    filePath: the output file path for all the box plots 
    
    description:
    clears the current plot 
    generates the sub dataframes for the respective variables.
    the reason they are grouped is based upon the numerical outputs for making the boxplots readable
    create a box plot, and then save it based upon the file path
    clear the plot
    repeat for the second set of variables
    """
    plt.clf()
    varDf1 = subdf[["PREDICTED_SS","PREDICTED_TURB","PREDICTED_CHLcal"]]
    varDf2 = subdf[["PREDICTED_TP","PREDICTED_TN","PREDICTED_TEMP","PREDICTED_DO","PREDICTED_VEL","PREDICTED_WDP",
                  "PREDICTED_SECCHI"]]
    plot1 = varDf1.boxplot()
    plt.savefig(filePath + "\\" + key +"_" + str(shape)  + "_SS_TURB_CHLcal"  + ".png")
    plt.clf()
    plot2 = varDf2.boxplot(rot = 45)
    plt.savefig(filePath + "\\" + key +"_" + str(shape)  + "_" + "TP_TN_TEMP_etc" + ".png")
    return plot1, plot2

def determineOverlap(scomplex, shapes, verbose = True):
    """
    Determines the overlap within a shape. 
    
    For each node, find it's neighbors, and generate the intersection, and saving the result without
    duplicates through utlizing the set functionality of python.
    
    params:
    scomplex: the entire simplicial complex in question
    shapes: all the shapes
    verbose: see prinout as the code works

    
    """
    
    shape = shapes[0] # chosen arbitrarily 
    
    result = set()
    if verbose:
        print("Shape: ", shape)
    nodes = scomplex.get('nodes')
    for node in shape:
        # currently, this displays a lot of repeats. 
        A = set(nodes.get(node))
        if verbose:
            print("Node: " , node  , " | Indices: ",A)
        B = adjacent(node, scomplex)
        if verbose:
            print("Adjacent nodes: ",B)
        for b in B:
            bSet = set(nodes.get(b))
            name = str(node) + " -> " + str(b) +": "
            intersection = set(A.intersection(bSet))
            intersection.add(name)
            intersection = frozenset(intersection)
            result.add(intersection)
            if verbose:
                print("Node: ", b, " | Indices: ", bSet)
                print("Overlap is: ", A.intersection(bSet))
    return result
print("Functions loaded")

Functions loaded

# Generating Summary Statistics on the entire simplicial complex
For each `mapper` output from `kepler-mapper`, we can generate the summary statistics for each of the continuous variables. This is done by first obtaining a list of the keys from the `.json` file, and then iterating through each complex, generating the shape and obtaining data summaries on each shape.

In [4]:
allComplices = list(jsonData.keys())
for key in allComplices: # remove indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    shapes = clean_getShapes(scomplex)
    for shape in shapes:
        summaries = shapeDataSummary(scomplex, shape, df_dict.get(key), variables, verbose = False)
        if summaries.loc['count'][0] > 5 and len(shape)  > 2: # at least 6 datapoints and 3 nodes to see info
            print("The shape is: ",shape)
            print("The number of nodes in the shape is: ", len(shape))
            display(summaries) # Uncomment to see summaries

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
The shape is:  ['cube6_cluster1', 'cube0_cluster0', 'cube2_cluster0', 'cube5_cluster0', 'cube8_cluster1', 'cube1_cluster0', 'cube4_cluster0', 'cube7_cluster1', 'cube5_cluster2', 'cube3_cluster0']
The number of nodes in the shape is:  10

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000
mean,5.807438,39.445314,28.055503,7.612425,31.490741,0.311708,0.173857,3.620438,46.316052,25.681036
std,2.689415,10.622191,1.600216,1.281878,13.943474,0.248585,0.064355,0.637487,21.792598,10.487500
min,0.340000,14.000000,25.800000,5.400000,11.000000,0.000000,0.033480,2.432000,12.700000,9.751950
25%,4.000000,32.500000,26.675000,6.875000,22.000000,0.019134,0.147750,3.282750,31.700000,18.313660
50%,5.350000,40.000000,27.900000,7.500000,27.500000,0.332943,0.172609,3.664633,41.850000,23.866420
75%,7.600000,46.000000,29.200000,8.025000,36.500000,0.493413,0.206250,4.039438,59.900000,29.584580
max,12.200000,68.000000,32.900000,13.200000,88.000000,0.971381,0.380512,5.372994,108.300000,60.993300

Current Simplical Complex:  ['Stratum 2 SUMMER 93-00: ']
The shape is:  ['cube6_cluster1', 'cube0_cluster0', 'cube2_cluster0', 'cube8_cluster0', 'cube5_cluster0', 'cube8_cluster1', 'cube7_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube9_cluster1', 'cube4_cluster2', 'cube3_cluster0', 'cube2_cluster3']
The number of nodes in the shape is:  13

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000
mean,3.770625,35.100000,27.993179,7.773181,37.765000,0.544608,0.185213,3.636574,57.774063,26.393068
std,1.969209,10.464445,1.389663,1.491258,18.169783,0.264792,0.067865,0.656414,31.614296,12.546677
min,0.550000,12.000000,25.581729,4.400000,11.000000,0.000000,0.041000,2.255000,14.300000,5.911680
25%,2.100000,26.750000,26.800000,6.800000,25.000000,0.377500,0.153345,3.259775,33.900000,15.399952
50%,3.500000,35.000000,27.800000,7.600000,34.000000,0.520000,0.176550,3.612500,48.923178,24.135400
75%,5.000000,43.000000,29.200000,8.100000,46.000000,0.700000,0.211986,4.128250,69.950000,34.470165
max,11.300000,63.000000,31.600000,14.300000,99.000000,1.700000,0.723927,5.849319,151.400000,65.769350

Current Simplical Complex:  ['Stratum 3 SUMMER 93-00: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster15', 'cube1_cluster0', 'cube2_cluster10', 'cube2_cluster18', 'cube2_cluster1']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000
mean,0.950344,24.215653,29.115963,9.329880,51.472049,0.035760,0.279727,2.567889,54.283605,72.462298
std,0.744180,8.567753,2.752198,4.664146,22.087829,0.131865,0.183523,1.126765,21.921755,36.496744
min,0.320000,11.000000,24.100000,3.300000,10.000000,0.000000,0.036000,0.560000,9.900000,9.299840
25%,0.600000,19.000000,27.200000,6.500000,34.000000,0.000000,0.171000,1.793000,38.700000,42.326220
50%,0.760000,22.000000,28.700000,8.200000,52.000000,0.000000,0.271561,2.213000,54.800000,68.043180
75%,0.970000,26.000000,30.500000,10.800000,68.000000,0.000000,0.364000,3.238000,68.600000,105.354660
max,4.900000,51.000000,39.500000,25.000000,101.000000,0.948848,1.613000,8.370005,112.700000,148.505460

Current Simplical Complex:  ['Stratum 4 SUMMER 93-00: ']
The shape is:  ['cube3_cluster5', 'cube3_cluster4', 'cube1_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,0.883333,18.393939,30.200000,9.487879,73.242424,0.000303,0.693154,2.056373,73.342424,87.074066
std,0.519854,3.904640,2.516073,5.039268,16.355485,0.001741,0.383099,0.663917,17.357780,14.711485
min,0.300000,11.000000,26.400000,2.200000,31.000000,0.000000,0.277000,1.290000,36.600000,59.440470
25%,0.590000,15.000000,28.300000,6.800000,65.000000,0.000000,0.417589,1.531000,61.200000,77.081690
50%,0.750000,18.000000,29.400000,7.900000,78.000000,0.000000,0.670000,1.969333,72.400000,84.958260
75%,0.850000,20.000000,32.100000,11.600000,85.000000,0.000000,0.715929,2.302000,88.900000,98.080120
max,2.300000,27.000000,34.500000,25.000000,101.000000,0.010000,1.874142,3.965000,100.700000,118.098140

The shape is:  ['cube6_cluster1', 'cube5_cluster0', 'cube4_cluster6']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,0.470000,11.857143,30.042857,11.771429,143.142857,0.008571,0.644323,1.924376,143.759134,161.737229
std,0.118603,1.951800,1.263404,2.976415,10.945754,0.006901,0.230879,0.794909,7.464677,8.991427
min,0.350000,10.000000,28.100000,5.400000,128.000000,0.000000,0.329618,0.872723,132.600000,148.985950
25%,0.380000,10.000000,29.600000,11.800000,136.000000,0.005000,0.459816,1.415669,139.356969,155.664325
50%,0.400000,12.000000,29.600000,12.300000,144.000000,0.010000,0.767838,2.026682,142.800000,164.067560
75%,0.575000,13.000000,30.650000,13.450000,149.000000,0.010000,0.793333,2.359944,149.500000,167.280650
max,0.630000,15.000000,32.100000,14.200000,160.000000,0.020000,0.906506,3.020000,153.200000,173.217140

The shape is:  ['cube4_cluster3', 'cube3_cluster6', 'cube5_cluster6']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,0.561667,12.666667,29.666667,16.183333,103.333333,0.015000,0.731152,2.175667,112.950000,155.186351
std,0.274257,1.861899,1.102119,7.301073,6.683313,0.022583,0.300707,0.963430,3.850065,9.346303
min,0.330000,9.000000,28.300000,6.800000,97.000000,0.000000,0.309983,0.817835,107.600000,141.052850
25%,0.340000,13.000000,28.850000,13.125000,98.250000,0.002500,0.514997,1.450323,110.375000,150.099012
50%,0.470000,13.000000,29.650000,13.650000,101.500000,0.010000,0.797273,2.477946,113.400000,156.919050
75%,0.735000,13.750000,30.525000,22.200000,107.000000,0.010000,0.934675,2.919357,115.300000,159.853487
max,0.980000,14.000000,31.000000,25.000000,114.000000,0.060000,1.081000,3.106000,118.000000,167.569858

Current Simplical Complex:  ['Stratum 5 SUMMER 93-00: ']
The shape is:  ['cube7_cluster3', 'cube2_cluster0', 'cube5_cluster0', 'cube6_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube7_cluster1', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,2.193158,33.052084,28.497368,8.714474,33.135869,0.011711,0.157153,3.344466,36.740737,34.985070
std,1.166738,8.166568,2.114078,3.034456,10.945652,0.045325,0.076908,0.556751,13.311718,15.225210
min,0.600000,19.000000,25.400000,4.000000,14.000000,0.000000,0.028000,2.097000,12.400000,9.266250
25%,1.247500,27.750000,26.700000,7.175000,26.500000,0.000000,0.137500,3.060156,26.875000,25.718330
50%,2.000000,32.000000,27.650000,8.100000,32.000000,0.000000,0.154250,3.271625,35.250000,31.287540
75%,3.000000,37.000000,30.500000,9.950000,39.000000,0.000000,0.176250,3.615125,44.125000,39.980025
max,7.000000,53.000000,33.500000,25.000000,68.000000,0.340000,0.640000,4.691000,71.049995,76.638240

Current Simplical Complex:  ['Stratum 1 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube5_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,6.248455,44.239706,28.060000,8.080000,24.780000,0.275793,0.200605,3.719023,37.423000,32.525356
std,2.951668,9.850165,1.582927,1.232145,9.116064,0.225755,0.068732,0.827890,15.503879,12.390508
min,1.000000,21.000000,25.300000,5.400000,7.000000,0.000000,0.050028,1.656369,6.500000,12.261240
25%,4.175000,37.750000,26.800000,7.475000,18.000000,0.078590,0.159500,3.319000,25.425000,23.149375
50%,6.000000,44.000000,27.750000,7.900000,24.000000,0.242579,0.177450,3.698082,34.500000,31.029300
75%,8.250000,50.000000,29.300000,8.725000,31.000000,0.451573,0.222250,4.352265,46.850000,38.720465
max,13.000000,75.000000,31.500000,13.200000,45.000000,0.971381,0.480270,5.758000,80.200000,61.636230

The shape is:  ['cube6_cluster0', 'cube8_cluster0', 'cube7_cluster1']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,5.415783,21.312333,28.480000,6.600000,63.700000,0.401310,0.228682,3.979537,94.020000,12.933602
std,3.490749,3.193622,1.615756,0.661648,11.585911,0.229256,0.025222,0.552990,9.933199,2.059359
min,0.340000,14.000000,26.300000,5.400000,51.000000,0.000000,0.195702,3.322286,77.800000,9.751950
25%,3.529457,20.342501,27.275000,6.325000,56.250000,0.314449,0.204922,3.474136,86.600000,12.129260
50%,4.000000,21.000000,28.250000,6.550000,61.000000,0.462964,0.232558,4.001772,96.000000,12.343610
75%,7.975000,23.000000,29.400000,6.700000,70.750000,0.574217,0.241750,4.327500,100.700000,14.046267
max,11.000000,26.000000,31.000000,7.900000,88.000000,0.641584,0.273000,4.830000,108.300000,17.050240

Current Simplical Complex:  ['Stratum 2 SUMMER 98-04: ']
The shape is:  ['cube2_cluster0', 'cube0_cluster1', 'cube5_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000
mean,3.636066,38.286885,28.059836,8.224180,33.490164,0.491611,0.189916,3.916744,52.061475,33.714166
std,2.265481,13.177159,1.449828,1.577422,19.713413,0.272844,0.062361,0.733997,32.591371,15.946011
min,0.300000,12.000000,25.400000,4.400000,6.000000,0.000000,0.002000,1.874175,11.500000,5.955980
25%,2.000000,26.000000,26.800000,7.500000,19.000000,0.320000,0.152940,3.392692,29.850000,22.106680
50%,3.200000,38.500000,28.200000,8.200000,28.000000,0.490000,0.174165,3.884106,40.750000,33.505280
75%,4.825000,45.000000,29.200000,8.600000,41.000000,0.620000,0.215000,4.479119,62.225000,41.507005
max,18.400000,80.000000,31.600000,18.200000,99.000000,1.700000,0.723927,5.426000,151.400000,68.848800

Current Simplical Complex:  ['Stratum 3 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube0_cluster2', 'cube0_cluster1', 'cube1_cluster6', 'cube1_cluster0', 'cube1_cluster7', 'cube2_cluster1']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000
mean,0.909731,22.830505,28.786318,8.310614,59.274326,0.037945,0.349227,2.647885,59.982014,74.590876
std,0.749517,8.982122,2.155192,3.436111,28.765338,0.138655,0.258840,1.024042,28.100218,42.152079
min,0.300000,11.000000,23.400000,2.800000,10.000000,0.000000,0.002000,1.055000,9.900000,9.299840
25%,0.522500,17.000000,27.225000,6.050000,34.141278,0.000000,0.239116,1.992872,38.000000,42.336160
50%,0.745000,20.000000,28.700000,7.800000,58.500000,0.000000,0.319777,2.334811,58.650000,63.230460
75%,0.950000,26.000000,29.900000,9.400000,84.750000,0.000000,0.386613,3.225000,79.100000,110.273562
max,4.900000,51.000000,35.500000,25.000000,116.000000,0.948848,2.527667,6.398813,130.200000,167.211530

Current Simplical Complex:  ['Stratum 4 SUMMER 98-04: ']
The shape is:  ['cube3_cluster0', 'cube1_cluster0', 'cube0_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,0.752000,19.650000,30.080000,9.565000,65.725000,0.000250,0.716168,1.695329,63.812500,89.584307
std,0.464698,3.613011,2.768523,4.477554,18.989859,0.001581,0.337686,0.688453,18.851201,14.029394
min,0.300000,11.000000,26.300000,4.600000,31.000000,0.000000,0.026000,0.024000,34.500000,65.056840
25%,0.507500,18.000000,27.075000,6.875000,47.250000,0.000000,0.408442,1.402048,46.375000,78.631705
50%,0.615000,20.000000,30.200000,8.200000,71.500000,0.000000,0.710500,1.803091,63.700000,87.346320
75%,0.770000,21.250000,32.250000,9.725000,82.000000,0.000000,1.003897,2.108997,77.475000,99.253425
max,2.300000,27.000000,34.400000,25.000000,94.000000,0.010000,1.307046,2.885041,99.300000,119.127730

Current Simplical Complex:  ['Stratum 5 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube0_cluster1', 'cube5_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  7

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,2.115584,32.239910,28.185714,8.576623,31.467532,0.021688,0.162828,3.376298,35.283117,36.638372
std,1.203185,5.813152,2.348500,2.222072,9.970462,0.052551,0.027163,0.620355,13.013054,17.355426
min,0.360000,19.000000,24.700000,4.000000,15.000000,0.000000,0.036000,2.221000,16.700000,8.132950
25%,1.000000,28.000000,26.100000,7.300000,25.000000,0.000000,0.150461,2.972483,26.100000,25.574660
50%,2.100000,33.000000,27.500000,7.800000,29.000000,0.000000,0.166500,3.314500,31.100000,33.110440
75%,3.000000,35.000000,30.600000,9.500000,36.000000,0.010000,0.179000,3.708000,41.500000,51.687420
max,7.000000,48.000000,31.600000,14.900000,68.000000,0.340000,0.220000,4.965000,78.000000,74.026250

Current Simplical Complex:  ['Stratum 1 SUMMER 01-13: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube3_cluster1', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000
mean,6.236978,41.737778,28.984889,7.906667,31.248889,0.275929,0.235926,3.276117,45.081778,34.952097
std,3.536730,14.433581,1.802885,1.903709,25.535695,0.279318,0.129205,1.031044,35.353000,21.700931
min,0.450000,12.000000,25.300000,3.700000,7.000000,0.000000,0.050028,1.098997,6.500000,9.164280
25%,3.500000,32.000000,27.700000,6.500000,15.000000,0.000000,0.170000,2.491000,20.600000,23.082820
50%,6.000000,43.000000,29.200000,7.900000,22.000000,0.214855,0.200444,3.287600,31.700000,29.545520
75%,8.200000,50.000000,30.100000,9.100000,35.000000,0.473235,0.257074,4.084857,57.600000,38.821380
max,19.300000,75.000000,33.400000,12.300000,128.000000,1.050000,1.228158,5.940472,166.800000,138.525820

The shape is:  ['cube4_cluster1', 'cube5_cluster0', 'cube6_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,10.00000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,7.09000,16.70000,27.220000,5.370000,131.600000,0.413261,0.293474,4.011093,183.000000,11.584294
std,1.97228,2.58414,1.301964,0.676675,8.934328,0.254628,0.078758,0.404630,14.707066,2.558159
min,3.40000,13.00000,25.600000,4.400000,120.000000,0.000000,0.192748,3.486090,159.200000,9.303560
25%,5.87500,14.25000,26.100000,5.000000,128.000000,0.268029,0.229881,3.744103,175.975000,9.960100
50%,7.15000,17.00000,27.150000,5.250000,130.000000,0.424766,0.288151,3.955636,184.550000,10.967710
75%,8.32500,19.00000,28.175000,6.075000,138.000000,0.596561,0.357000,4.160950,192.775000,11.497220
max,9.90000,20.00000,28.900000,6.100000,148.000000,0.745295,0.421000,4.807087,205.400000,17.381800

Current Simplical Complex:  ['Stratum 2 SUMMER 01-13: ']
Current Simplical Complex:  ['Stratum 3 SUMMER 01-13: ']
The shape is:  ['cube1_cluster16', 'cube0_cluster0', 'cube2_cluster0', 'cube1_cluster14', 'cube2_cluster6', 'cube1_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  7

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000
mean,1.018832,23.848797,30.469072,9.054334,51.725086,0.039278,0.389884,2.524294,52.737113,66.890048
std,0.773418,9.272010,3.130584,3.808940,26.072446,0.126496,0.285081,0.935908,26.616907,44.212644
min,0.180000,10.000000,23.200000,0.400000,9.000000,0.000000,0.002000,0.919000,8.800000,7.214360
25%,0.500000,17.000000,28.400000,6.200000,31.000000,0.000000,0.225330,1.836000,33.000000,30.807055
50%,0.780000,21.000000,30.000000,8.369485,48.000000,0.000000,0.323000,2.325333,48.300000,59.376120
75%,1.100000,27.000000,32.350000,11.550000,70.500000,0.000000,0.464500,2.931138,70.600000,91.302990
max,3.900000,67.000000,38.600000,21.800000,116.000000,1.000000,2.904651,6.531588,130.200000,175.992050

Current Simplical Complex:  ['Stratum 4 SUMMER 01-13: ']
The shape is:  ['cube3_cluster2', 'cube0_cluster0', 'cube2_cluster0', 'cube0_cluster1', 'cube1_cluster0', 'cube1_cluster1', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
mean,1.110101,28.898990,30.000000,8.013131,41.080808,0.001515,0.803153,1.670896,40.044444,61.984517
std,0.909488,12.781919,2.915301,2.406057,23.413618,0.012402,0.537995,0.624384,21.998619,34.527586
min,0.250000,11.000000,24.000000,3.700000,6.000000,0.000000,0.017000,0.024000,6.000000,10.027860
25%,0.515000,20.000000,27.750000,6.200000,22.000000,0.000000,0.358496,1.130610,21.750000,29.373350
50%,0.650000,27.000000,30.000000,7.500000,36.000000,0.000000,0.535000,1.691000,38.100000,68.873860
75%,1.450000,36.000000,32.650000,9.300000,63.500000,0.000000,1.121904,2.258098,58.400000,86.098970
max,3.300000,70.000000,35.500000,14.500000,94.000000,0.120000,2.168000,2.879706,94.000000,140.556380

Current Simplical Complex:  ['Stratum 5 SUMMER 01-13: ']
The shape is:  ['cube2_cluster2', 'cube1_cluster0', 'cube0_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000
mean,2.501243,34.372781,29.785799,11.010059,23.674556,0.012426,0.174256,2.827293,26.992899,53.186539
std,1.575602,7.887420,2.544001,3.608895,8.114912,0.045820,0.046326,0.828452,9.295734,23.185295
min,0.400000,18.000000,24.700000,5.100000,10.000000,0.000000,0.036000,1.289000,11.100000,16.452220
25%,1.200000,30.000000,27.800000,8.400000,19.000000,0.000000,0.143000,2.280000,20.400000,34.931080
50%,2.200000,34.000000,30.100000,10.300000,22.000000,0.000000,0.167000,2.811000,24.700000,49.957320
75%,3.600000,38.000000,31.600000,13.300000,27.000000,0.000000,0.192905,3.329500,32.000000,69.157410
max,9.400000,58.000000,34.900000,20.500000,53.000000,0.380000,0.335000,4.965000,56.100000,126.426440

Current Simplical Complex:  ['Stratum 1 SUMMER 10-16: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube4_cluster1', 'cube1_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  5

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,6.280000,30.316667,28.701667,6.611667,51.108333,0.375711,0.241029,3.340142,74.576917,23.046890
std,3.411069,11.978961,2.051070,1.351201,31.503713,0.331638,0.097719,1.014256,39.039223,7.859109
min,0.700000,12.000000,24.800000,3.700000,8.000000,0.000000,0.140535,1.056507,11.400000,9.549010
25%,3.600000,21.750000,27.800000,5.675000,33.000000,0.000000,0.195870,2.693934,43.175000,16.729913
50%,6.100000,28.000000,28.600000,6.600000,46.000000,0.404451,0.226832,3.432168,74.990000,22.853470
75%,7.925000,35.250000,30.200000,7.300000,67.000000,0.655683,0.253341,4.133300,106.062500,29.037960
max,19.300000,62.000000,32.800000,10.200000,128.000000,1.022370,0.928245,5.940472,156.350000,38.821380

Current Simplical Complex:  ['Stratum 2 SUMMER 10-16: ']
The shape is:  ['cube2_cluster0', 'cube4_cluster1', 'cube3_cluster1', 'cube0_cluster1', 'cube1_cluster0', 'cube4_cluster0', 'cube5_cluster2', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000
mean,4.014885,28.973282,28.829008,6.662595,56.511450,0.698494,0.238551,3.435145,81.519606,23.332080
std,2.233446,10.333299,1.979918,1.435421,34.018221,0.341312,0.100529,1.016961,40.431537,9.185101
min,0.300000,9.000000,25.200000,4.100000,10.000000,0.000000,0.145235,0.990000,14.500000,2.329570
25%,2.400000,23.000000,27.900000,5.700000,35.000000,0.480000,0.196109,2.858469,55.025000,16.711955
50%,3.800000,29.000000,28.800000,6.400000,47.000000,0.765000,0.223578,3.515385,81.990000,21.533790
75%,5.400000,33.000000,30.000000,7.100000,78.000000,0.960000,0.262526,4.227563,111.350000,30.423270
max,12.000000,60.000000,35.200000,12.000000,172.000000,1.360000,1.673310,6.523909,193.580000,43.965610

The shape is:  ['cube6_cluster0', 'cube7_cluster2', 'cube7_cluster0', 'cube5_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,5.821053,11.736842,28.247368,5.868421,175.157895,0.863684,0.281485,3.839048,241.412105,17.930186
std,2.387835,1.939132,0.676895,0.331751,20.958327,0.184066,0.034280,0.339757,23.200092,2.555011
min,0.700000,8.000000,27.500000,4.800000,152.000000,0.350000,0.214280,3.091000,199.510000,11.251450
25%,4.350000,10.000000,27.600000,5.700000,158.000000,0.740000,0.253390,3.597762,223.285000,17.397865
50%,6.300000,12.000000,27.800000,5.900000,170.000000,0.920000,0.280000,3.932013,250.390000,19.003620
75%,7.700000,13.000000,29.000000,6.050000,185.000000,0.975000,0.293500,4.107243,258.990000,19.468515
max,8.600000,15.000000,29.300000,6.300000,220.000000,1.170000,0.346000,4.299000,276.870000,20.465700

Current Simplical Complex:  ['Stratum 3 SUMMER 10-16: ']
Current Simplical Complex:  ['Stratum 4 SUMMER 10-16: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube3_cluster1', 'cube0_cluster1', 'cube1_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,1.591633,35.795918,29.553061,7.365306,23.224490,0.003061,0.369782,1.372517,23.421079,35.650223
std,1.030834,12.622697,3.437362,2.206576,10.188362,0.017584,0.108070,0.329019,10.479480,21.083073
min,0.460000,16.000000,24.000000,3.700000,6.000000,0.000000,0.210000,0.963000,6.000000,10.027860
25%,0.780000,27.000000,26.800000,5.800000,16.000000,0.000000,0.281449,1.107000,15.900000,19.435850
50%,1.000000,35.000000,29.500000,6.900000,22.000000,0.000000,0.334286,1.297983,21.900000,29.052150
75%,2.900000,40.000000,33.000000,8.400000,29.000000,0.000000,0.432000,1.568000,31.620000,50.266810
max,3.300000,70.000000,35.500000,13.400000,50.000000,0.120000,0.547000,2.218000,42.500000,91.549870

Current Simplical Complex:  ['Stratum 5 SUMMER 10-16: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube4_cluster1', 'cube1_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  5

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.0,95.000000,95.000000,95.000000,95.000000
mean,2.423158,29.968421,30.395789,11.118947,24.526316,0.0,0.192469,2.761972,26.835579,58.019429
std,1.617232,4.585947,2.274742,3.828263,7.298852,0.0,0.058694,0.742897,7.645653,22.779512
min,0.260000,18.000000,26.000000,5.100000,13.000000,0.0,0.117000,1.289000,15.040000,17.851060
25%,1.225000,27.000000,29.000000,8.800000,20.000000,0.0,0.149450,2.321500,21.500000,42.018255
50%,2.000000,30.000000,30.500000,10.600000,22.000000,0.0,0.180000,2.759659,24.750000,51.370920
75%,3.050000,34.000000,31.850000,13.800000,28.000000,0.0,0.209124,3.271713,29.960000,72.089495
max,9.400000,42.000000,34.900000,19.600000,48.000000,0.0,0.444069,4.398842,53.100000,119.462400

Current Simplical Complex:  ['Stratum 1 SUMMER 14-20: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube4_cluster4', 'cube3_cluster1', 'cube2_cluster2', 'cube1_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,106.000000,106.000000,106.000000,106.000000,106.00000,106.000000,106.000000,106.000000,106.000000,106.000000
mean,6.149811,28.399878,27.166038,7.578302,54.90566,0.499686,0.229527,3.181405,81.943679,32.555738
std,2.528473,6.854749,1.482462,1.163738,24.46320,0.317300,0.050133,0.678528,26.904529,15.833449
min,0.680000,13.000000,24.800000,5.100000,15.00000,0.000000,0.109000,1.056507,22.010000,9.653400
25%,4.325000,25.000000,25.600000,6.700000,36.25000,0.227204,0.195160,2.749118,64.720000,19.115893
50%,6.200000,28.000000,27.100000,7.300000,51.50000,0.560000,0.230500,3.165176,82.175000,25.920300
75%,7.625000,32.000000,28.475000,8.300000,67.00000,0.754384,0.253000,3.597841,103.722500,47.306130
max,12.300000,48.000000,29.700000,11.000000,128.00000,1.022370,0.494508,4.628146,137.350000,72.416960

Current Simplical Complex:  ['Stratum 2 SUMMER 14-20: ']
The shape is:  ['cube5_cluster1', 'cube0_cluster0', 'cube2_cluster0', 'cube7_cluster2', 'cube6_cluster0', 'cube7_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  9

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000
mean,4.078179,25.946429,27.270714,7.497500,71.285714,0.736567,0.247037,3.251966,102.589179,35.748010
std,1.974336,7.766807,1.426905,1.538384,41.597885,0.243710,0.053167,0.644665,50.476622,25.322034
min,0.300000,8.000000,25.200000,5.300000,15.000000,0.000000,0.152000,1.450107,19.720000,3.155920
25%,2.600000,21.750000,26.300000,6.400000,40.000000,0.620000,0.207724,2.963901,67.545000,19.423160
50%,4.000000,26.500000,26.800000,7.000000,59.000000,0.750000,0.246327,3.303877,90.525000,23.152325
75%,5.300000,31.000000,28.500000,8.400000,88.000000,0.912500,0.280056,3.569500,119.572500,42.589875
max,11.400000,42.000000,32.200000,12.000000,220.000000,1.360000,0.536388,4.791793,276.870000,107.311760

Current Simplical Complex:  ['Stratum 3 SUMMER 14-20: ']
The shape is:  ['cube2_cluster4', 'cube0_cluster0', 'cube2_cluster0', 'cube1_cluster5', 'cube2_cluster2', 'cube1_cluster1']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,0.919173,22.756958,28.723308,8.717293,52.315789,0.029850,0.317627,2.247321,52.580150,53.671621
std,0.505967,8.682136,2.132394,2.981090,30.324100,0.117827,0.116237,0.932839,29.353381,26.629376
min,0.300000,9.000000,23.100000,1.100000,5.000000,0.000000,0.138000,0.930000,7.640000,12.912610
25%,0.550000,15.000000,27.800000,6.600000,28.000000,0.000000,0.247752,1.585523,30.680000,30.735000
50%,0.800000,22.000000,28.900000,8.400000,41.000000,0.000000,0.289822,1.987938,44.140000,51.081280
75%,1.200000,30.000000,30.100000,10.600000,75.000000,0.000000,0.366000,2.941437,79.150000,70.535380
max,3.000000,47.000000,34.300000,15.500000,116.000000,0.620000,0.959000,5.341000,125.630000,121.777920

Current Simplical Complex:  ['Stratum 4 SUMMER 14-20: ']
The shape is:  ['cube1_cluster0', 'cube0_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.0,12.000000,12.000000,12.000000,12.000000
mean,1.258333,24.416667,26.991667,8.675000,32.833333,0.0,0.296585,1.387400,34.786073,53.868560
std,0.339942,5.775471,0.782140,1.649862,9.675023,0.0,0.042173,0.108285,6.148955,7.851244
min,0.850000,16.000000,25.900000,6.800000,21.000000,0.0,0.240000,1.262000,23.990000,43.351450
25%,0.995000,20.000000,26.375000,7.450000,24.750000,0.0,0.243549,1.295844,30.550000,47.457445
50%,1.150000,25.000000,26.800000,8.150000,33.000000,0.0,0.312067,1.354604,36.411440,51.779545
75%,1.535000,27.000000,27.550000,10.025000,38.750000,0.0,0.330938,1.485797,39.765000,60.964008
max,1.930000,35.000000,28.300000,12.000000,50.000000,0.0,0.345000,1.568000,42.220000,66.258580

Current Simplical Complex:  ['Stratum 5 SUMMER 14-20: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube0_cluster2', 'cube5_cluster0', 'cube6_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
mean,1.958842,28.452632,29.240000,12.674737,30.978947,0.017474,0.240889,2.421064,33.654211,71.726039
std,0.867914,4.081011,1.478239,4.508927,8.772514,0.074562,0.095062,0.563783,10.997084,31.960131
min,0.260000,20.000000,26.500000,3.400000,13.000000,0.000000,0.139000,1.438000,15.040000,17.851060
25%,1.300000,26.000000,28.150000,9.200000,25.000000,0.000000,0.185765,2.107062,27.715000,44.177800
50%,2.000000,28.000000,29.200000,13.300000,30.000000,0.000000,0.201172,2.430420,31.220000,73.999150
75%,2.600000,30.000000,30.600000,15.700000,35.500000,0.000000,0.258601,2.760124,36.300000,94.769645
max,4.200000,42.000000,31.900000,22.900000,56.000000,0.470000,0.511000,3.458000,74.530000,152.640790

# Analyzing the largest structure
Largest = Node count of the shape. The largest structure is likely to be the dominant feature of the stratum during this particular time period. As such, it is important to analyze the nodes within it. To do this, we generate all the shapes, and since the shapes are returned in descending order of the number of nodes per shape, we pull the first shape. From here, we can preform an analysis on each one.

In [ ]:
allComplices = list(jsonData.keys())
for key in allComplices[0:3]: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    largestShape = clean_getShapes(scomplex)[0]
    nodes = scomplex.get('nodes')
    print("Largest shape is: ", largestShape)
    print("Number of nodes is: ", len(largestShape))
    for node in largestShape:
        summary = nodeDataSummary(node, scomplex,variables,df_dict.get(key))
        if summary.loc['count'][0] > 5: # 5 is chosen arbitraily
            print("Information for: ", node)
            display(summary)

# Condensing 1-simplices
Currently, many one simplices that we have contain information that means one of them is a subset of the other. To resolve this, we replace them with one cluster with all the indices in one node.

This is stored in the function `clean_getShapes(scomplex)` function. Below is a comparison of running the two functions

In [ ]:
allComplices = list(jsonData.keys())
print("Standard shape version")
for key in allComplices[0:1]:
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    nodes = scomplex.get('nodes')
    shapes = getShapes(scomplex)
    for shape in shapes:
        indices = []
        for node in shape:
            indices.append(nodes.get(node))
        indices = list(set([item for sublist in indices for item in sublist]))
        print(str(shape) + " : " + str(indices))

print("Clean shape version")
for key in allComplices[0:1]:
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    nodes = scomplex.get('nodes')
    cleanShapes = clean_getShapes(scomplex)
    for shape in cleanShapes:
        indices = []
        npShape = np.array(shape).flatten()
        for node in npShape:
            indices.append(nodes.get(node))
        indices = list(set([item for sublist in indices for item in sublist]))
        print(str(shape) + " : " + str(indices))

# Box plot per shape
Here, we generate box plots for the variables of interest. for each shape in the simplicial complex <br>
TODO: Plot output ideas: <br>
SS, Turb, CHLCal <br>
Vel, TN, TP <br>
Temp, DO, SECCHI <br>

In [ ]:
allComplices = list(jsonData.keys())
for key in allComplices[0:1]: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    shapes = clean_getShapes(scomplex)
    print("number of shapes: ", len(shapes))
    for shape in shapes:
        """
        Hello whoever is using this function
        getBoxplots takes a couple arguments. 
        the big thing that matters here is the 
        strataYear variable. Essentially, the key that allows us to access each simplicial complex is weird.
        Depending on your file system, using the str(key) conversion may cause errors. to resolve this, 
        below is a potential example. Feel free to change it as you go for your use.
        """
        strataYear = str(key).replace(" ","-").replace(":","").replace("[","").replace("]","").replace("'","")
        print(strataYear)
        """
        before: 
        ['Stratum 1 SUMMER 93-00: ']
        after:
        Stratum-1-SUMMER-93-00-
        """
        subdf = getSubdf(scomplex, shape, df_dict.get(key))
        plots = getBoxplots(subdf, shape, strataYear,  
                            filePath = r"C:\Users\forre\Desktop\REU\TDA\Data\TDAOutputs\Boxplots")

# Discovering which indices within the nodes overlap
This code will determine what points in the nodes are overlapping within two nodes.

In [23]:
allComplices = list(jsonData.keys())
for key in allComplices[0:1]: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    shapes = clean_getShapes(scomplex)
    print("number of shapes: ", len(shapes))
    result = determineOverlap(scomplex, shapes, verbose = False)
    print(result)

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
number of shapes:  8
{frozenset({97, 66, 'cube6_cluster1 -> cube5_cluster0: '}), frozenset({'cube2_cluster0 -> cube3_cluster0: ', 51, 22, 87, 72, 56, 76}), frozenset({59, 'cube4_cluster0 -> cube5_cluster0: ', 83, 4}), frozenset({98, 'cube7_cluster1 -> cube8_cluster1: '}), frozenset({67, 44, 'cube1_cluster0 -> cube0_cluster0: '}), frozenset({32, 1, 34, 65, 36, 69, 71, 'cube3_cluster0 -> cube4_cluster0: ', 62, 63}), frozenset({'cube7_cluster1 -> cube6_cluster1: ', 102}), frozenset({20, 'cube5_cluster2 -> cube4_cluster0: '}), frozenset({'cube0_cluster0 -> cube1_cluster0: ', 67, 44}), frozenset({0, 2, 5, 10, 11, 15, 18, 24, 26, 27, 28, 29, 43, 47, 111, 112, 114, 53, 54, 'cube1_cluster0 -> cube2_cluster0: '}), frozenset({0, 2, 5, 10, 11, 15, 18, 24, 26, 27, 28, 29, 43, 47, 111, 112, 114, 'cube2_cluster0 -> cube1_cluster0: ', 53, 54}), frozenset({98, 'cube8_cluster1 -> cube7_cluster1: '}), frozenset({'cube4_cluster0 -> cube5_cluster2: ', 20}), frozenset({'cube5_cluster0 -> cube6_cluster1: ', 97, 66}), frozenset({32, 1, 34, 65, 36, 69, 'cube4_cluster0 -> cube3_cluster0: ', 71, 62, 63}), frozenset({51, 22, 87, 72, 56, 76, 'cube3_cluster0 -> cube2_cluster0: '}), frozenset({59, 'cube5_cluster0 -> cube4_cluster0: ', 83, 4}), frozenset({102, 'cube6_cluster1 -> cube7_cluster1: '})}

# See compare shapes over the years
NOTE: Comparing the largest shape in each.