# Simplicial Complex Analysis

<span style='color:Red'>TODO: Get more robust numbers working for when to display summary information for shapes as a whole and the largest shape.</span> <br>
<span style='color:Red'> Currently using the largest number of nodes in each shape. </span> <br> 
Written by Frederick Miller, Casey McKean, and Wako Bungula
The kepler mapper object gives an output that is not easily navigatible. To resolve this, we wish to create shapes that are easier to navigate and understand, and reveal the data inside of them. <br>
We generate all the shapes in the simplicial complex, condense 1-simplices where possible, and obtain summary statistics on the shapes and the nodes within the shapes.

In [15]:
import numpy as np
import pandas as pd 
import queue
import json
pd.set_option('display.max_rows', None)
print("Imports Done")

Imports Done

# File paths and `.json` import

From the `kmapper_demo` file, I added one extra code block to place the results in a `.json` file, which is a way to store dictionaries in long term storage. The code below only needs to have the file paths changed, and then it will read the simplicial complices generated from kepler mapper. <br>
Here, we also import the actual data set, with data interpolated for the specific pool. <br>
Lastly, a list of the 11 continuous variables (the interpolated versions) is created.

In [16]:
jsonFilePath = r"C:\Users\forre\Desktop\REU\TDA\Data\TDAOutputs\TDA1PCA10Cubes45perc.json"
jsonFile = open(jsonFilePath, "r")
jsonData = json.load(jsonFile) 
jsonFile.close()

dataFilePath = r"C:\Users\forre\Desktop\REU\TDA\Data\interpolatedPool26.csv"
df = pd.read_csv(dataFilePath)

variables = ['PREDICTED_TN',
             'PREDICTED_TP',
             'PREDICTED_TEMP',
             'PREDICTED_DO',
             'PREDICTED_TURB',
             'PREDICTED_COND',
             'PREDICTED_VEL',
             'PREDICTED_SS',
             'PREDICTED_WDP',
             'PREDICTED_CHLcal',
             'PREDICTED_SECCHI']
print("Json file imported")

print(len(jsonData.keys()))

Json file imported
25

# Functions
See the `docstring`'s for what each function does and how it works.

In [21]:
def getSubdf(scomplex, shape, df):
    """
    Returns the part of the data frame from the particular shape in the simplicial complex.
    params:
    scomplex: the entire simplicial complex
    shape: the particular shape being inspected (within the simplicial complex)
    df: the entire data frame
    
    Description:
    1. Get all the nodes from the particular simplicial complex. 
    2. Generate the indices we care about from the particular shape. To do this, we read each node and append it's 
    indices to a list. Then, we convert the list to a set and then back to a list to eliminate duplicates.
    3. Return the dataframe with only those indices.
    """
    nodes = scomplex.get('nodes')
    indices = []
    npShape = np.array(shape).flatten()
    for node in npShape:
        indices.append(nodes.get(node))
    indices = list(set([item for sublist in indices for item in sublist]))
    subdf = df.loc[indices]
    return subdf

def shapeDataSummary(scomplex, shape, df, variables, verbose = False):
    """
    Generates summary statistics of the given variables for a given shape in the simplicial.
    params:
    scomplex: the entire simplicial complex
    shape: the particular shape being inspected (within the simplicial complex) at this function call.
    df: the entire dataframe
    variables: the variables of interest
    verbose: Determines if the function will print out extra information. False by default
    
    Description:
    1. Create an empty result dataframe to store the summary statistics.
    2. Get the sub dataframe (see getSubdf) for the particular shape
    3. For each variable we are analzying, generate summary statistics from the sub dataframe and place them
    inside the result dataframe.
    4. Return the result dataframe
    
    NOTE: this only creates summaries for one particular shape. In executing this method, it is done for each shape 
    outside of the function.
    
    """
    result = pd.DataFrame()
    if verbose == True:
        print("Obtaining sub dataframe for: ", shape)
        print("The number of nodes in this shape is: ", len(shape))
    subdf = getSubdf(scomplex, shape, df)
    if verbose == True:
        print("The number of datapoints in this shape is: ", subdf.shape[0])
    for var in variables:
        result[var] = subdf[var].describe()
    return result
    
    

def adjacent(v, scomplex):
    """
    Determines the nodes adjacent to a given vertex
    
    params:
    v: vertex
    scomlex: the entire simplicial complex
    
    Description:
    Determines the nodes that are adjacent to a given vertex.
    """
    
    simplices = scomplex.get('simplices')
    edges = [item for item in simplices if len(item) == 2]
    result = []
    for edge in edges:
        if v in edge:
            for item in edge:
                if item != v:
                    result.append(item)
    return result

def bfs(node, scomplex):
    """
    Conducts a breadth first search to obtain the entire shape from a given node
    params:
    node: the start node
    scomplex: the entire simplicial complex
    
    Description:
    Preforms a breadth first search to obtain the entire shape for a given start node.
    """
    Q = queue.Queue()
    result = []
    result.append(node)
    Q.put(node)
    while not Q.empty():
        v = Q.get()
        adjacentEdges = adjacent(v, scomplex)
        for edge in adjacentEdges:
            if edge not in result:
                result.append(edge)
                Q.put(edge)
    return result


        
    
def getShapes(scomplex):
    """
    Gets all of the shapes from a given simplicial complex.
    
    params:
    scomplex: the entire simplicial complex
    
    Description:
    1. Obtain all the nodes for the entire complex
    2. For each node, preform a breadth first search to obtain everything in that particular shape. 
    If this entire shape has not already been discovered, add it to the set of results. 
    The result item is a set as the order of the shapes does not matter. The resulting shape is a frozenset
    which means items cannot be added or removed once created, and is needed to allow the set object to have other sets within it.
    3. Convert each shape to a list and the result to a list for easier navigation outside of the function.
    4. Return the result
    
    """
    
    nodes = list(scomplex.get('nodes').keys())
    result = set()
    for node in nodes: # currently does more computations than necessary due to going through every node without considering it is already in a shape
        bfsResult = frozenset(bfs(node, scomplex))
        result.add(bfsResult)
    result = [list(x) for x in result]
    # Sort the list depending on what is decided: nodes or indices. Currently doing it by number of nodes
    result.sort(key = len, reverse = True)
    
    
    return result

def nodeDataSummary(node, scomplex, variables,df):
    """
    Returns a data summary of a particular node
    params:
    node: node in question
    scomplex: The entire simplicial complex
    variables: The variables to obtain summaries
    df: the entire dataframe 
    
    description:
    1. Creates a result dataframe
    2. Get all the indices from the node from the simplicial complex
    3. Generate summaries for each variable
    4. Return the result
    """
    result = pd.DataFrame()
    indices = scomplex.get('nodes').get(node)
    subdf = df.loc[indices]
    for var in variables:
        result[var] = subdf[var].describe()
    return result
    
    
def condenseShape(shape, scomplex):
    """
    
    params:
    shape: a shape of two nodes. must be 2
    scomplex: the entire simplicial complex
    
    description:
    gets the two nodes a and b
    gets the indices for a and b (what is inside the nodes)
    if a \subseteq b, return b
    elif b \subseteq a, return a 
    else return shape 
    
    """
    nodes = scomplex.get('nodes')
    a = shape[0]
    b = shape[1]
    aIndices = set(nodes.get(a))
    bIndices = set(nodes.get(b))
    
    if aIndices.issubset(bIndices):
        return b
    elif bIndices.issubset(aIndices):
        return a
    else:
        return shape

def clean_getShapes(scomplex):
    """
    Condenses 1-simplices down to 0-simplices when each node 
    is a subset of the other 
    
    params:
    scomplex: the entire simplicial complex
    
    Description:
    1. Get all the shapes from the original getShapes function
    2. For shapes that of length 2, if one is a subset of the other, return the larger of the two
        Otherwise, do nothing
    3. return the clean Shapes list 
    
    """
    shapes = getShapes(scomplex)
    cleanShapes = []
    for shape in shapes:
        if len(shape) == 2:
            shape = condenseShape(shape, scomplex)
            cleanShapes.append([shape])
        else:
            cleanShapes.append(shape)
    return cleanShapes
print("Functions loaded")

Functions loaded

# Generating Summary Statistics on the entire simplicial complex
For each `mapper` output from `kepler-mapper`, we can generate the summary statistics for each of the continuous variables. This is done by first obtaining a list of the keys from the `.json` file, and then iterating through each complex, generating the shape and obtaining data summaries on each shape.

In [22]:
allComplices = list(jsonData.keys())
for key in allComplices: # remove indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    shapes = clean_getShapes(scomplex)
    for shape in shapes:
        summaries = shapeDataSummary(scomplex, shape, df, variables, verbose = False)
        if summaries.loc['count'][0] > 5 and len(shape)  > 2: # at least 6 datapoints and 3 nodes to see info
            print("The shape is: ",shape)
            print("The number of nodes in the shape is: ", len(shape))
            display(summaries) # Uncomment to see summaries

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
The shape is:  ['cube7_cluster1', 'cube6_cluster0', 'cube3_cluster0', 'cube5_cluster0', 'cube4_cluster0', 'cube5_cluster1', 'cube5_cluster5', 'cube7_cluster0', 'cube2_cluster0', 'cube5_cluster11', 'cube1_cluster0', 'cube2_cluster6']
The number of nodes in the shape is:  12

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000
mean,3.321725,0.218013,14.083784,9.522973,54.986486,475.972973,0.330604,60.462093,3.074189,55.155801,26.432432
std,0.941895,0.073410,2.574055,2.204637,30.887553,55.188338,0.332414,34.098436,2.673006,34.438192,8.146066
min,1.730722,0.112000,6.500000,3.600000,21.000000,347.000000,0.000000,16.400000,0.400000,10.457550,9.000000
25%,2.475142,0.170719,13.000000,8.325000,37.000000,445.250000,0.000000,38.506935,1.105000,23.575204,23.000000
50%,3.334431,0.200094,14.000000,9.800000,43.000000,465.500000,0.310000,51.442821,1.800000,54.557334,27.000000
75%,4.061680,0.238260,15.200000,11.375000,60.000000,515.000000,0.565000,71.879000,4.525000,84.450847,30.000000
max,5.081000,0.429201,21.500000,13.600000,150.000000,587.000000,1.580000,187.900000,10.400000,128.955279,50.000000

Current Simplical Complex:  ['Stratum 2 SUMMER 93-00: ']
The shape is:  ['cube1_cluster1', 'cube4_cluster2', 'cube6_cluster0', 'cube4_cluster1', 'cube3_cluster0', 'cube1_cluster4', 'cube5_cluster4', 'cube5_cluster1', 'cube7_cluster0', 'cube2_cluster0', 'cube2_cluster8', 'cube5_cluster2']
The number of nodes in the shape is:  12

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,3.320844,0.233468,16.36550,9.161500,63.647786,437.660000,0.300183,71.453582,2.978300,51.520813,24.945000
std,1.216655,0.103036,4.22948,2.479031,46.724682,83.955865,0.347283,53.672637,2.509813,36.177092,9.094809
min,1.358000,0.033000,6.50000,3.600000,15.000000,227.000000,0.000000,16.400000,0.400000,9.239100,5.000000
25%,2.332597,0.171971,13.90000,7.600000,37.000000,374.000000,0.000000,38.687777,1.100000,25.189010,19.000000
50%,3.227672,0.225356,15.00000,8.600000,51.000000,450.000000,0.133885,54.025000,1.900000,40.114605,25.000000
75%,4.053040,0.282344,17.62500,10.625000,70.250000,490.750000,0.552500,87.322971,4.300000,63.834940,30.000000
max,9.568764,0.972000,28.00000,19.600000,360.000000,697.000000,1.580000,307.700000,11.900000,183.861190,50.000000

Current Simplical Complex:  ['Stratum 3 SUMMER 93-00: ']
Current Simplical Complex:  ['Stratum 4 SUMMER 93-00: ']
The shape is:  ['cube1_cluster8', 'cube2_cluster8', 'cube3_cluster13', 'cube3_cluster15']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,6.000000,6.00000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,3.399333,0.25100,11.350000,11.766667,46.000000,505.333333,0.333333,61.247187,2.733333,95.466727,30.500000
std,0.820661,0.07718,1.838206,1.155278,22.342784,54.763735,0.383597,33.309009,2.454112,21.439255,8.757854
min,2.256000,0.19600,9.100000,10.300000,30.000000,450.000000,0.000000,27.927783,0.500000,61.724220,15.000000
25%,2.786250,0.20275,9.950000,11.025000,36.000000,460.250000,0.000000,33.787987,0.800000,89.315900,28.750000
50%,3.784500,0.22750,11.550000,11.900000,36.000000,497.000000,0.230000,55.734611,1.900000,92.579900,32.000000
75%,3.975000,0.25150,13.000000,12.100000,45.000000,540.500000,0.655000,81.443912,4.500000,110.140220,34.500000
max,4.079000,0.40100,13.000000,13.600000,90.000000,585.000000,0.820000,111.599994,6.300000,121.694780,41.000000

The shape is:  ['cube3_cluster10', 'cube3_cluster7', 'cube4_cluster2']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,3.278000,0.233500,14.783333,10.166667,41.833333,543.666667,0.145000,53.933333,1.633333,40.863633,33.333333
std,1.178918,0.071896,1.158303,2.133229,32.220594,25.943528,0.247689,35.400038,1.535795,14.137468,11.325487
min,2.005000,0.152000,13.500000,8.100000,15.000000,496.000000,0.000000,17.400000,0.500000,19.422780,21.000000
25%,2.355250,0.172000,13.850000,8.225000,19.500000,538.750000,0.000000,31.400000,1.000000,36.504380,24.750000
50%,3.140500,0.232500,14.650000,9.950000,26.500000,550.500000,0.000000,41.000000,1.050000,38.484540,31.500000
75%,3.942250,0.290000,15.825000,12.050000,63.500000,562.250000,0.202500,75.800000,1.400000,49.799740,40.500000
max,5.079000,0.323000,16.100000,12.600000,90.000000,564.000000,0.600000,108.600000,4.700000,59.374140,50.000000

Current Simplical Complex:  ['Stratum 5 SUMMER 93-00: ']
The shape is:  ['cube8_cluster4', 'cube6_cluster0', 'cube4_cluster1', 'cube3_cluster5', 'cube3_cluster0', 'cube5_cluster0', 'cube7_cluster0', 'cube2_cluster0', 'cube4_cluster7']
The number of nodes in the shape is:  9

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000
mean,3.095007,0.189526,14.340351,9.773684,49.210526,478.438596,0.266863,50.229048,3.036842,51.096813,29.192982
std,0.861922,0.049730,1.468096,2.409766,31.871246,58.030170,0.290247,24.435783,2.783025,35.388401,7.548506
min,1.398977,0.103728,9.900000,4.300000,16.000000,391.000000,0.000000,16.400000,0.400000,9.239100,9.000000
25%,2.454000,0.158000,13.500000,8.400000,34.000000,435.000000,0.000000,29.643698,1.000000,24.297020,25.000000
50%,3.049000,0.180000,14.700000,9.900000,40.000000,461.000000,0.150000,40.475000,1.800000,40.290417,28.000000
75%,3.783000,0.219000,15.200000,11.200000,54.000000,515.000000,0.481934,65.200000,4.500000,67.010894,33.000000
max,4.935000,0.343000,17.500000,17.400000,200.000000,697.000000,0.950000,111.599994,10.400000,128.955279,50.000000

The shape is:  ['cube1_cluster1', 'cube0_cluster1', 'cube2_cluster1']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.00000,7.000000,7.000000
mean,3.189571,0.225000,14.842857,10.957143,36.857143,542.714286,0.038571,41.614286,2.00000,55.693591,33.285714
std,0.886456,0.060459,1.337731,1.652127,21.035118,32.760313,0.102050,21.741085,2.61916,31.040743,10.061714
min,2.005000,0.152000,13.500000,8.600000,15.000000,496.000000,0.000000,17.400000,0.50000,27.343420,21.000000
25%,2.537500,0.171000,13.750000,9.850000,21.000000,522.500000,0.000000,28.600000,0.95000,37.135420,27.000000
50%,3.306000,0.236000,14.200000,11.300000,37.000000,541.000000,0.000000,40.700000,1.00000,38.571580,32.000000
75%,3.785500,0.272500,16.050000,12.250000,44.500000,565.000000,0.000000,45.900000,1.35000,66.859580,38.000000
max,4.370000,0.300000,16.600000,12.600000,75.000000,587.000000,0.270000,84.200000,7.90000,115.950140,50.000000

Current Simplical Complex:  ['Stratum 1 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster9', 'cube2_cluster2', 'cube3_cluster3', 'cube2_cluster0', 'cube2_cluster8', 'cube0_cluster5', 'cube1_cluster0', 'cube2_cluster6']
The number of nodes in the shape is:  9

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000
mean,3.038003,0.193883,14.130508,10.111864,46.135593,479.067797,0.243252,47.357250,2.923729,49.149700,29.050847
std,0.796105,0.053550,1.507482,2.437005,24.489588,56.668688,0.279312,21.328671,2.859729,28.884776,7.632561
min,1.398977,0.103728,9.100000,4.200000,16.000000,409.000000,0.000000,16.400000,0.400000,10.457550,9.000000
25%,2.411353,0.158750,13.500000,8.550000,33.500000,438.500000,0.000000,29.817815,1.100000,29.088646,24.000000
50%,3.023000,0.183000,14.200000,10.200000,40.000000,463.000000,0.070416,42.431505,1.700000,40.399420,28.000000
75%,3.779052,0.226798,15.050000,11.400000,52.000000,497.000000,0.484222,56.625000,4.050000,62.788945,33.000000
max,4.681500,0.401000,17.000000,17.400000,175.000000,697.000000,0.950000,111.599994,11.900000,123.995324,50.000000

The shape is:  ['cube5_cluster3', 'cube4_cluster6', 'cube3_cluster8', 'cube2_cluster7']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,3.210879,0.239210,14.716667,9.216667,80.277778,497.388889,0.439126,62.430411,3.109444,31.036441,25.111111
std,1.173228,0.113757,2.352283,2.341505,66.074651,45.331639,0.388250,45.913208,2.594103,32.007170,10.851342
min,1.828000,0.113500,10.100000,6.500000,25.000000,420.000000,0.000000,25.050000,0.500000,10.535133,9.000000
25%,2.225625,0.153785,13.000000,7.425000,35.500000,459.000000,0.142500,29.858441,1.187500,12.872829,14.000000
50%,2.858600,0.177212,15.000000,8.500000,53.500000,513.500000,0.445000,45.049287,2.150000,16.860820,27.500000
75%,4.061790,0.311617,15.775000,11.500000,107.000000,524.500000,0.593318,79.727576,4.525000,26.098296,33.750000
max,5.081000,0.429201,18.500000,13.500000,290.000000,560.000000,1.580000,187.900000,9.000000,116.966006,40.000000

The shape is:  ['cube6_cluster0', 'cube5_cluster2', 'cube7_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,2.985478,0.198857,16.300000,9.433333,68.666667,413.000000,0.311667,85.657916,4.870000,70.993370,25.666667
std,1.369041,0.095558,2.809982,1.764842,51.836924,52.191953,0.444721,57.266567,3.658497,38.015949,10.443499
min,1.443500,0.104500,13.400000,6.700000,26.000000,347.000000,0.000000,26.949998,0.700000,24.122461,11.000000
25%,1.910250,0.131208,15.000000,9.000000,34.750000,370.500000,0.000000,42.500765,1.665000,47.334178,18.000000
50%,2.944999,0.194690,15.450000,9.300000,41.000000,426.000000,0.080000,69.648240,5.000000,65.472680,30.500000
75%,3.865000,0.213833,16.725000,10.050000,108.750000,441.750000,0.527500,130.024120,7.900000,91.855002,31.750000
max,4.842370,0.369000,21.500000,12.100000,140.000000,480.000000,1.060000,164.100000,9.100000,128.955279,36.000000

Current Simplical Complex:  ['Stratum 2 SUMMER 98-04: ']
The shape is:  ['cube1_cluster7', 'cube2_cluster3', 'cube4_cluster1', 'cube2_cluster5', 'cube6_cluster3', 'cube3_cluster0', 'cube0_cluster2', 'cube4_cluster0', 'cube5_cluster5', 'cube2_cluster0', 'cube1_cluster0', 'cube1_cluster6']
The number of nodes in the shape is:  12

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000
mean,3.329489,0.250463,15.126190,9.385714,69.919984,436.482143,0.271454,78.000845,2.842917,52.643028,23.273810
std,1.238054,0.099380,2.568656,2.204847,50.815389,87.589884,0.334648,59.071730,2.494869,35.730411,9.317232
min,1.358000,0.103728,6.500000,3.600000,15.000000,227.000000,0.000000,16.400000,0.400000,8.086720,5.000000
25%,2.265187,0.183176,13.600000,8.000000,39.000000,355.500000,0.000000,39.566088,1.100000,27.097965,16.750000
50%,3.209212,0.234884,14.950000,9.000000,53.000000,452.000000,0.027323,58.400000,1.800000,42.357820,23.000000
75%,4.083250,0.300250,16.000000,10.700000,86.000000,496.250000,0.512500,98.617570,3.725000,67.625865,30.000000
max,9.568764,0.972000,23.100000,19.600000,360.000000,697.000000,1.580000,307.700000,11.900000,183.861190,50.000000

The shape is:  ['cube7_cluster3', 'cube8_cluster2', 'cube9_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000
mean,3.716213,0.245331,17.700000,9.621429,64.571429,361.642857,0.337036,86.185714,3.351429,58.349779,21.500000
std,1.632674,0.081644,3.146182,1.577329,23.329461,62.718672,0.472277,63.389794,2.981375,31.284645,7.035624
min,1.823000,0.138395,14.200000,8.200000,25.000000,257.000000,0.000000,27.300000,0.810000,34.019060,11.000000
25%,2.308750,0.179697,14.925000,8.525000,56.000000,352.000000,0.000000,55.400000,0.992500,39.990323,19.000000
50%,3.257039,0.231658,17.400000,8.950000,66.000000,364.500000,0.000000,68.000000,1.600000,49.227500,20.000000
75%,5.222043,0.292957,18.900000,10.150000,73.250000,379.500000,0.855823,100.275000,4.950000,61.608730,21.750000
max,5.956041,0.434000,23.100000,13.300000,120.000000,465.000000,1.127214,283.400000,9.200000,141.453040,36.000000

Current Simplical Complex:  ['Stratum 3 SUMMER 98-04: ']
The shape is:  ['cube2_cluster2', 'cube3_cluster1', 'cube4_cluster1']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2.682208,0.237648,16.480000,7.880000,72.800000,383.600000,0.158844,91.220000,3.511000,40.780756,25.900000
std,0.853154,0.099145,2.084226,2.017589,47.316429,58.205002,0.337490,84.451956,3.316908,28.337694,13.033717
min,1.358000,0.112000,14.200000,4.300000,21.000000,308.000000,0.000000,16.400000,0.910000,13.329980,11.000000
25%,2.081489,0.164152,15.900000,7.150000,34.750000,334.750000,0.000000,27.425000,1.575000,21.250620,17.000000
50%,2.713000,0.234000,16.000000,8.000000,62.000000,372.500000,0.000000,67.750000,2.000000,31.045615,21.500000
75%,3.164750,0.288907,16.175000,9.050000,100.250000,431.500000,0.067500,107.300000,3.700000,51.279420,32.000000
max,4.304431,0.442000,21.800000,11.500000,155.000000,476.000000,1.020000,267.700000,11.400000,99.434850,50.000000

Current Simplical Complex:  ['Stratum 4 SUMMER 98-04: ']
The shape is:  ['cube3_cluster2', 'cube3_cluster0', 'cube2_cluster0', 'cube3_cluster4', 'cube1_cluster0']
The number of nodes in the shape is:  5

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,3.631000,0.198429,14.871429,9.314286,63.857143,470.000000,0.165714,51.146819,2.357143,40.610803,28.428571
std,0.572272,0.052741,0.861615,1.869428,60.642198,46.328537,0.262161,19.167753,3.091848,30.200240,6.778819
min,2.769000,0.145000,13.000000,8.200000,31.000000,424.000000,0.000000,36.500000,0.500000,9.239100,17.000000
25%,3.306000,0.159500,15.000000,8.450000,37.000000,443.500000,0.000000,39.413867,0.750000,26.298940,26.000000
50%,3.652000,0.179000,15.000000,8.600000,39.000000,456.000000,0.000000,43.300000,0.900000,32.826940,28.000000
75%,3.918000,0.228000,15.200000,9.000000,51.500000,482.500000,0.235000,55.000000,2.250000,42.880060,31.500000
max,4.548000,0.290000,15.700000,13.500000,200.000000,558.000000,0.690000,89.400000,9.100000,103.851580,39.000000

Current Simplical Complex:  ['Stratum 5 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube3_cluster0', 'cube5_cluster0', 'cube0_cluster2', 'cube4_cluster0', 'cube2_cluster0', 'cube1_cluster0']
The number of nodes in the shape is:  7

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000
mean,3.319580,0.202602,14.691228,9.643860,50.508772,483.912281,0.239246,56.423790,2.807018,49.049700,28.350877
std,0.885853,0.053647,1.628790,2.428258,32.112594,56.126859,0.255013,23.898691,2.496845,29.929117,7.665999
min,1.398977,0.103728,7.400000,3.600000,15.000000,391.000000,0.000000,16.400000,0.400000,9.239100,9.000000
25%,2.680000,0.160000,13.800000,8.400000,35.000000,444.000000,0.000000,38.741125,1.000000,25.308385,25.000000
50%,3.384000,0.207333,14.900000,9.600000,43.000000,476.000000,0.150000,54.900000,1.700000,41.530940,28.000000
75%,4.065000,0.234000,15.700000,11.200000,58.000000,515.000000,0.481934,71.938667,4.300000,65.728060,30.000000
max,5.079000,0.323000,21.000000,17.400000,200.000000,697.000000,0.690000,108.600000,10.400000,128.955279,50.000000

The shape is:  ['cube8_cluster3', 'cube6_cluster0', 'cube5_cluster3', 'cube7_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,3.096159,0.189183,13.591667,9.933333,49.916667,477.000000,0.504795,37.771184,4.158333,52.942076,30.250000
std,0.664448,0.040253,1.264522,1.822253,19.194973,41.433408,0.237655,13.258427,2.831787,39.082042,5.986728
min,2.084805,0.130168,10.800000,6.500000,28.000000,417.000000,0.000000,26.570509,1.100000,12.324687,23.000000
25%,2.561809,0.167790,12.950000,9.200000,37.500000,458.500000,0.382500,28.731945,1.750000,24.409766,26.500000
50%,3.029896,0.182436,14.050000,10.350000,47.500000,467.500000,0.483767,29.817815,4.450000,43.578652,28.000000
75%,3.774827,0.202891,14.425000,10.850000,53.250000,481.750000,0.682500,46.530351,5.250000,70.611831,35.000000
max,4.051720,0.281459,15.100000,12.100000,98.000000,556.000000,0.820000,66.800000,10.400000,116.472380,41.000000

Current Simplical Complex:  ['Stratum 1 SUMMER 01-13: ']
The shape is:  ['cube1_cluster1', 'cube3_cluster0', 'cube5_cluster0', 'cube4_cluster0', 'cube5_cluster1', 'cube2_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000
mean,3.215806,0.224799,15.618978,9.059124,63.072993,454.627737,0.312734,69.095243,2.949489,51.343478,25.759124
std,1.125565,0.085074,3.672364,2.283301,44.345839,77.600979,0.337434,49.208947,2.626001,32.738216,8.771214
min,1.398977,0.033000,6.500000,3.600000,15.000000,227.000000,0.000000,16.400000,0.400000,7.306800,6.000000
25%,2.266000,0.172875,13.800000,7.600000,37.000000,409.000000,0.000000,40.300000,1.100000,24.562530,20.000000
50%,3.147000,0.213000,14.900000,8.600000,51.000000,458.000000,0.220000,57.550000,1.900000,42.227260,26.000000
75%,4.017000,0.272000,15.900000,10.600000,70.000000,507.000000,0.550000,79.300000,3.800000,71.037500,31.000000
max,9.568764,0.490000,28.000000,17.000000,290.000000,697.000000,1.580000,307.700000,11.900000,164.753150,50.000000

The shape is:  ['cube7_cluster3', 'cube6_cluster2', 'cube7_cluster2', 'cube5_cluster6']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,3.649330,0.396663,16.300000,8.885714,120.000000,358.571429,0.502675,139.000000,4.821429,112.596000,16.571429
std,1.276143,0.262139,1.672324,1.618053,108.391267,58.926104,0.396354,61.932759,2.043660,56.730944,7.678045
min,2.261000,0.189194,13.200000,7.000000,55.000000,238.000000,0.000000,75.000000,1.700000,18.420660,5.000000
25%,2.700500,0.270507,15.500000,7.350000,60.500000,358.500000,0.240000,117.400000,3.775000,80.668025,11.500000
50%,3.028000,0.352000,17.200000,9.200000,89.000000,373.000000,0.488722,128.000000,6.000000,119.615280,17.000000
75%,4.697248,0.361218,17.450000,10.300000,107.500000,374.500000,0.765000,131.800000,6.150000,153.395565,22.500000
max,5.460812,0.972000,17.800000,10.700000,360.000000,433.000000,1.020000,271.600000,6.200000,182.008880,26.000000

The shape is:  ['cube5_cluster3', 'cube4_cluster2', 'cube5_cluster2', 'cube3_cluster8']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.0
mean,2.998539,0.157490,13.771429,10.842857,40.000000,476.142857,0.567637,34.037454,4.414286,30.098754,27.0
std,0.562669,0.026728,0.453557,0.472077,2.768875,9.299258,0.196630,5.971004,2.958845,22.395585,2.0
min,2.214889,0.123522,13.000000,10.300000,38.000000,460.000000,0.343460,27.586596,1.100000,10.457550,24.0
25%,2.657992,0.139108,13.550000,10.500000,38.500000,472.500000,0.450000,29.237507,2.250000,13.630481,26.0
50%,2.918369,0.161869,13.900000,10.600000,39.000000,480.000000,0.570000,31.689932,4.300000,18.554266,27.0
75%,3.330629,0.168388,14.000000,11.300000,40.000000,482.000000,0.605000,39.039566,6.250000,45.575629,28.0
max,3.879273,0.202048,14.400000,11.400000,46.000000,484.000000,0.950000,42.431505,8.500000,63.267240,30.0

The shape is:  ['cube4_cluster5', 'cube5_cluster5', 'cube6_cluster1']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,3.577289,0.265866,16.983333,8.905556,87.777778,381.111111,0.197699,107.711111,2.011111,49.059601,16.000000
std,1.206387,0.072407,4.096663,1.426420,40.795841,60.925112,0.397087,74.300494,2.107851,29.107271,7.372445
min,1.842000,0.131354,12.200000,7.200000,22.000000,318.000000,0.000000,29.700000,0.600000,11.206400,8.000000
25%,2.632758,0.225250,13.825000,7.900000,53.750000,335.750000,0.000000,53.800000,0.970000,33.482865,11.500000
50%,3.556554,0.258500,15.050000,8.150000,81.500000,353.000000,0.000000,91.150000,1.135000,41.087085,15.000000
75%,4.231766,0.303750,20.575000,10.175000,100.000000,451.000000,0.015000,120.725000,1.800000,50.251145,17.750000
max,6.035742,0.399444,24.200000,11.300000,190.000000,491.000000,1.127214,283.400000,8.200000,121.077630,41.000000

The shape is:  ['cube4_cluster10', 'cube3_cluster16', 'cube2_cluster16']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,4.033795,0.239597,15.660000,10.88000,50.855729,438.700000,0.095000,55.790000,2.665000,46.497780,25.700000
std,1.012388,0.054313,1.361535,3.65416,42.400303,109.410593,0.300416,54.650169,2.410335,30.448111,8.380533
min,1.993000,0.139411,13.500000,5.90000,22.000000,262.000000,0.000000,23.000000,0.960000,16.275880,8.000000
25%,3.554250,0.206750,15.100000,9.02500,29.500000,336.750000,0.000000,28.350000,1.700000,32.142378,26.250000
50%,4.137648,0.236500,16.000000,10.45000,33.500000,488.500000,0.000000,32.450000,1.800000,36.115095,28.500000
75%,4.397630,0.280532,16.150000,11.45000,44.389321,533.250000,0.000000,42.150000,1.950000,55.150017,30.750000
max,5.915136,0.311000,18.000000,19.60000,160.000000,547.000000,0.950000,191.000000,8.700000,122.247510,33.000000

Current Simplical Complex:  ['Stratum 2 SUMMER 01-13: ']
The shape is:  ['cube2_cluster5', 'cube2_cluster2', 'cube0_cluster2', 'cube1_cluster5', 'cube1_cluster4', 'cube1_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,3.241762,0.201412,16.264942,9.803231,54.332558,464.830148,0.259703,63.307645,3.058289,49.079121,33.917448
std,1.332957,0.100316,7.657282,2.852674,43.869499,125.856876,0.301037,51.546230,2.599782,39.621856,27.402254
min,0.827000,0.028000,0.000000,3.600000,4.000000,227.000000,0.000000,3.600000,0.180000,6.195150,5.000000
25%,2.267000,0.133250,13.800000,7.800000,28.000000,387.250000,0.000000,30.125000,1.030000,18.642727,20.000000
50%,3.175000,0.190000,15.900000,9.200000,43.000000,441.500000,0.146800,50.400000,2.100000,34.721655,28.000000
75%,3.921899,0.259685,20.150000,11.600000,64.000000,510.500000,0.473750,76.575000,4.600000,70.081700,35.000000
max,12.296000,0.972000,31.200000,20.000000,360.000000,1104.000000,1.580000,307.700000,16.000000,252.118470,200.000000

Current Simplical Complex:  ['Stratum 3 SUMMER 01-13: ']
The shape is:  ['cube3_cluster7', 'cube2_cluster0', 'cube0_cluster23', 'cube1_cluster0', 'cube1_cluster64']
The number of nodes in the shape is:  5

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000
mean,3.420069,0.211548,18.683871,9.231183,62.795699,417.021505,0.336228,72.209654,2.972258,54.641804,25.881720
std,1.484057,0.092736,5.178221,1.913907,40.678901,81.318346,0.354898,54.084062,2.477014,40.928898,10.762101
min,1.808000,0.059000,10.100000,5.000000,13.000000,257.000000,0.000000,14.900000,0.350000,7.306800,8.000000
25%,2.454000,0.145000,14.200000,7.800000,36.000000,363.000000,0.000000,31.900000,1.050000,26.449600,19.000000
50%,3.224995,0.193799,17.400000,8.600000,52.000000,423.000000,0.330000,54.900000,1.900000,40.063440,25.000000
75%,3.790000,0.255232,23.400000,10.600000,71.000000,465.000000,0.570000,96.800000,4.600000,64.435940,34.000000
max,12.296000,0.434000,31.200000,15.100000,200.000000,697.000000,1.580000,304.500000,10.400000,183.861190,50.000000

The shape is:  ['cube1_cluster24', 'cube0_cluster12', 'cube0_cluster13']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,3.476326,0.311897,14.316667,8.558333,103.666667,391.750000,0.445833,93.921641,3.508333,70.230925,17.916667
std,1.133943,0.219906,1.631415,2.177763,90.383359,82.970011,0.364753,38.675346,2.753331,49.427859,9.394954
min,1.922898,0.167689,12.200000,5.000000,39.000000,238.000000,0.000000,32.368564,0.600000,10.711221,5.000000
25%,2.769027,0.193545,13.050000,7.200000,52.000000,341.000000,0.150000,64.487500,1.275000,32.191122,11.000000
50%,3.232131,0.248007,14.500000,7.750000,79.500000,375.000000,0.465000,101.300000,2.200000,56.841465,16.000000
75%,4.268273,0.318537,15.200000,10.875000,97.000000,440.500000,0.650000,129.025000,6.175000,101.240380,25.000000
max,5.564667,0.972000,17.800000,11.600000,360.000000,551.000000,1.110000,135.900000,8.200000,182.008880,35.000000

Current Simplical Complex:  ['Stratum 4 SUMMER 01-13: ']
The shape is:  ['cube0_cluster2', 'cube2_cluster11', 'cube1_cluster9', 'cube3_cluster10']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.00000
mean,2.651974,0.182922,13.741667,11.504167,38.250000,499.041667,0.201811,45.054129,2.383333,44.279812,29.37500
std,0.731503,0.045017,1.767808,2.918379,14.438023,67.068089,0.254482,16.386184,2.185260,21.861341,7.22804
min,1.443500,0.104500,9.800000,5.000000,16.000000,412.000000,0.000000,26.949998,0.400000,10.711221,18.00000
25%,2.094361,0.151429,13.175000,10.275000,31.500000,460.750000,0.000000,36.086686,0.875000,27.785140,26.50000
50%,2.398873,0.183708,13.900000,11.400000,37.000000,480.500000,0.000000,40.185909,1.200000,39.816547,28.50000
75%,3.229306,0.223209,14.825000,12.200000,40.750000,517.000000,0.417500,53.076731,3.500000,60.170440,33.00000
max,4.248363,0.253868,17.000000,17.400000,72.000000,697.000000,0.650000,93.093305,8.200000,85.507178,50.00000

Current Simplical Complex:  ['Stratum 5 SUMMER 01-13: ']
The shape is:  ['cube7_cluster1', 'cube6_cluster0', 'cube4_cluster1', 'cube4_cluster3', 'cube5_cluster0', 'cube7_cluster4', 'cube6_cluster4', 'cube4_cluster4']
The number of nodes in the shape is:  8

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,3.234738,0.244136,16.258730,9.255556,72.714286,444.873016,0.293556,82.592428,2.866349,55.333373,21.984127
std,1.133231,0.124789,3.219779,2.310200,58.020694,80.423374,0.377284,71.562452,2.408112,30.840206,8.472902
min,1.358000,0.104500,7.400000,4.400000,21.000000,227.000000,0.000000,23.400000,0.400000,9.239100,5.000000
25%,2.238633,0.165046,14.050000,7.550000,39.500000,376.000000,0.000000,40.185909,1.095000,32.399951,17.000000
50%,3.121030,0.222573,15.200000,9.100000,58.000000,458.000000,0.050000,58.600000,1.800000,51.801660,21.000000
75%,4.098500,0.292500,17.150000,10.600000,78.500000,482.000000,0.585000,89.150000,4.150000,74.834384,28.000000
max,6.035742,0.972000,24.200000,17.400000,360.000000,661.000000,1.580000,307.700000,11.900000,123.995324,41.000000

The shape is:  ['cube0_cluster0', 'cube3_cluster0', 'cube4_cluster0', 'cube2_cluster0', 'cube1_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  6

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,91.000000,91.000000,91.000000,91.000000,91.000000,91.000000,91.000000,91.000000,91.000000,91.000000,91.000000
mean,3.263986,0.243444,14.504396,9.674725,64.802198,448.725275,0.272031,73.611260,2.885934,61.829235,24.758242
std,1.025554,0.079099,2.455602,2.115162,40.123758,84.483143,0.315625,43.642170,2.680712,44.091426,9.353954
min,1.730722,0.113500,6.500000,3.600000,15.000000,308.000000,0.000000,17.400000,0.400000,10.457550,8.000000
25%,2.311050,0.181524,13.250000,8.100000,37.000000,374.500000,0.000000,40.174999,1.015000,26.995260,18.000000
50%,3.207423,0.225116,14.200000,9.800000,52.000000,451.000000,0.140000,57.550000,1.800000,50.060860,25.000000
75%,4.040408,0.285500,15.950000,11.050000,80.000000,515.500000,0.489361,104.100000,4.050000,92.579900,30.000000
max,5.941145,0.429201,21.500000,16.100000,200.000000,697.000000,1.060000,205.600000,11.400000,183.861190,50.000000

Current Simplical Complex:  ['Stratum 1 SUMMER 10-16: ']
The shape is:  ['cube3_cluster3', 'cube0_cluster5', 'cube1_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,3.120600,0.208122,15.781132,9.996226,54.660377,469.490566,0.266150,68.376160,3.362264,59.492754,26.132075
std,1.152753,0.066781,2.967650,1.950933,29.969820,71.757236,0.293808,50.134670,2.926517,45.445017,8.864444
min,1.443500,0.104500,10.100000,6.500000,16.000000,356.000000,0.000000,20.300000,0.400000,10.457550,8.000000
25%,2.216556,0.155126,13.800000,8.800000,34.000000,427.000000,0.000000,39.338007,1.100000,25.308385,20.000000
50%,2.777417,0.193799,15.000000,10.200000,49.000000,465.000000,0.104605,55.662528,2.100000,50.494870,26.000000
75%,3.783000,0.240013,17.000000,10.700000,64.000000,484.000000,0.481934,87.800000,4.900000,75.776298,32.000000
max,6.035742,0.366000,24.200000,17.000000,175.000000,697.000000,0.950000,276.400000,11.900000,183.861190,50.000000

The shape is:  ['cube4_cluster6', 'cube3_cluster2', 'cube2_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
mean,4.040258,0.336032,17.512500,8.012500,116.500000,466.250000,0.634573,108.287500,3.223750,36.732872,13.125000
std,1.128302,0.110047,2.306783,0.937226,32.350756,75.209707,0.510610,61.490079,3.032651,32.284749,6.621124
min,1.941154,0.160000,14.000000,6.700000,52.000000,347.000000,0.000000,25.300000,0.820000,11.596360,9.000000
25%,3.368965,0.272127,16.475000,7.475000,105.000000,422.000000,0.340000,49.850000,1.142500,14.179845,9.750000
50%,4.316185,0.386500,18.000000,7.650000,125.000000,513.500000,0.535223,121.250000,1.850000,20.906655,11.000000
75%,4.951258,0.416963,18.275000,8.850000,140.000000,517.500000,0.869603,153.300000,4.175000,50.375052,12.500000
max,5.081000,0.429201,21.500000,9.400000,150.000000,520.000000,1.580000,187.900000,8.300000,98.752420,29.000000

Current Simplical Complex:  ['Stratum 2 SUMMER 10-16: ']
The shape is:  ['cube0_cluster4', 'cube3_cluster5', 'cube1_cluster19', 'cube4_cluster3', 'cube1_cluster5', 'cube2_cluster5']
The number of nodes in the shape is:  6

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000
mean,3.016027,0.187779,17.120930,8.934884,49.813953,426.162791,0.316663,48.398785,3.299302,45.571692,27.255814
std,1.004645,0.071478,4.615118,1.600727,26.443341,77.870751,0.301261,22.387156,2.685334,32.875949,7.111671
min,1.398977,0.059000,10.800000,5.000000,20.000000,257.000000,0.000000,20.705501,0.400000,10.457550,9.000000
25%,2.225945,0.143500,14.450000,8.150000,35.500000,397.500000,0.000000,29.237507,1.040000,24.166910,23.000000
50%,2.743000,0.169333,15.000000,8.600000,45.000000,427.000000,0.290000,42.431505,2.200000,34.701490,27.000000
75%,3.787538,0.222818,17.900000,10.300000,56.000000,479.500000,0.500000,57.550000,4.550000,58.095923,32.500000
max,5.802840,0.434000,27.000000,11.800000,175.000000,556.000000,0.950000,105.200000,10.400000,141.453040,40.000000

The shape is:  ['cube4_cluster1', 'cube3_cluster0', 'cube4_cluster0', 'cube2_cluster0', 'cube4_cluster9']
The number of nodes in the shape is:  5

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,3.513534,0.179841,17.753846,7.576923,48.576923,448.846154,0.208179,53.026016,2.986538,35.980678,28.923077
std,0.551239,0.067149,5.612716,1.891520,15.057684,30.873539,0.229505,21.448418,2.511834,17.286338,7.868535
min,1.910000,0.051000,7.400000,3.600000,21.000000,391.000000,0.000000,16.400000,0.500000,13.155900,20.000000
25%,3.221750,0.145250,14.825000,6.250000,40.000000,433.000000,0.000000,39.325000,1.425000,22.845155,24.250000
50%,3.661500,0.185743,15.150000,8.100000,49.000000,447.500000,0.133885,50.800000,1.800000,30.563900,26.500000
75%,3.883500,0.227750,23.500000,9.075000,53.500000,460.000000,0.337500,63.425000,4.150000,48.808600,30.750000
max,4.332000,0.291000,27.000000,10.200000,92.000000,546.000000,0.690000,98.200000,10.400000,69.470780,50.000000

The shape is:  ['cube1_cluster8', 'cube2_cluster8', 'cube0_cluster6', 'cube1_cluster10']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000
mean,3.575608,0.278582,16.393243,8.997297,81.142666,377.378378,0.313528,105.972882,3.188919,63.642712,19.905405
std,1.497482,0.111173,3.040563,2.126221,55.429004,82.379460,0.384957,71.757932,2.563070,44.938802,7.926320
min,1.842000,0.139411,12.200000,5.000000,13.000000,227.000000,0.000000,18.300000,0.360000,7.306800,5.000000
25%,2.396000,0.215364,14.525000,7.725000,52.250000,327.750000,0.000000,52.125000,1.285000,31.606182,14.000000
50%,3.251500,0.262500,15.800000,8.400000,64.000000,362.500000,0.000000,98.846652,2.050000,43.524335,19.500000
75%,4.397630,0.308500,17.475000,10.250000,99.000000,376.000000,0.655000,127.825000,4.200000,92.370175,24.000000
max,9.568764,0.972000,26.700000,19.600000,360.000000,697.000000,1.127214,307.700000,11.400000,183.861190,48.000000

The shape is:  ['cube1_cluster2', 'cube2_cluster3', 'cube0_cluster1']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,3.36270,0.231400,14.690000,10.490000,42.200000,539.600000,0.140000,49.840000,2.160000,54.874172,31.600000
std,1.03500,0.059369,1.187387,1.874063,24.316432,36.169969,0.239861,28.675123,2.334381,29.829828,8.859396
min,2.00500,0.152000,13.500000,8.100000,15.000000,474.000000,0.000000,17.400000,0.500000,19.422780,21.000000
25%,2.40175,0.187000,13.825000,8.650000,25.250000,514.750000,0.000000,31.400000,1.000000,36.504380,26.500000
50%,3.38900,0.223500,14.100000,11.100000,37.500000,550.500000,0.000000,40.950000,1.150000,46.057020,30.000000
75%,4.07850,0.278750,15.825000,12.150000,49.500000,563.750000,0.202500,62.975000,1.725000,70.602300,32.750000
max,5.07900,0.323000,16.600000,12.600000,90.000000,587.000000,0.600000,108.600000,7.900000,115.950140,50.000000

The shape is:  ['cube2_cluster2', 'cube1_cluster1', 'cube3_cluster2']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,3.160511,0.148129,24.100000,9.615000,49.727681,399.000000,0.246854,51.145000,2.653500,51.216147,32.100000
std,0.960275,0.045090,5.468763,2.562744,25.747006,66.973679,0.299000,23.927819,1.727238,29.353695,9.369042
min,0.951000,0.069000,13.500000,4.400000,24.455847,309.000000,0.000000,16.500000,0.500000,19.703740,19.000000
25%,2.941000,0.126637,24.675000,8.000000,38.875000,359.750000,0.000000,32.650000,1.157500,28.544905,27.000000
50%,3.180628,0.145000,26.500000,9.000000,41.500000,395.000000,0.000000,47.550000,2.400000,36.295830,29.500000
75%,3.699250,0.166000,27.125000,11.625000,60.250000,422.250000,0.487500,63.475000,3.650000,72.713020,35.500000
max,4.935000,0.232000,29.000000,15.000000,146.125745,572.000000,0.880000,99.100000,6.000000,126.342840,55.000000

Current Simplical Complex:  ['Stratum 3 SUMMER 10-16: ']
Current Simplical Complex:  ['Stratum 4 SUMMER 10-16: ']
The shape is:  ['cube7_cluster2', 'cube5_cluster2', 'cube6_cluster1', 'cube7_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2.966878,0.209587,12.500000,10.920000,39.800000,476.80000,0.106000,49.401050,1.440000,72.321430,31.200000
std,0.939515,0.082097,2.517936,1.804808,19.100902,56.56815,0.227459,27.888469,0.857904,33.227657,7.420692
min,1.398977,0.103728,9.100000,8.400000,25.000000,418.00000,0.000000,28.056643,0.500000,23.748126,15.000000
25%,2.305500,0.164286,10.275000,10.000000,28.500000,435.25000,0.000000,31.004642,0.750000,44.638628,28.500000
50%,2.892000,0.189500,12.600000,10.700000,33.500000,458.00000,0.000000,40.988863,1.100000,75.171900,33.000000
75%,3.854500,0.241500,14.875000,11.950000,42.000000,513.25000,0.105000,47.177474,2.200000,97.606460,36.500000
max,4.079000,0.401000,15.800000,13.600000,90.000000,585.00000,0.720000,111.599994,2.700000,121.694780,39.000000

The shape is:  ['cube1_cluster0', 'cube3_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,3.837000,0.195923,15.169231,9.030769,57.923077,474.615385,0.345259,63.530769,3.084615,50.141205,26.769231
std,0.614383,0.041462,1.899291,1.737040,43.549706,44.503817,0.290559,18.544289,2.754041,23.647650,4.781106
min,2.769000,0.145000,13.500000,4.400000,37.000000,424.000000,0.000000,36.500000,0.500000,9.239100,17.000000
25%,3.345000,0.161000,14.100000,8.400000,39.000000,456.000000,0.000000,48.600000,1.100000,29.954620,26.000000
50%,3.864000,0.184000,14.900000,9.100000,43.000000,461.000000,0.490000,62.900000,2.700000,58.416700,27.000000
75%,4.234000,0.213000,15.200000,9.800000,54.000000,483.000000,0.550000,78.600000,4.900000,68.252220,30.000000
max,4.935000,0.290000,21.000000,11.500000,200.000000,572.000000,0.690000,94.400000,10.400000,82.961980,33.000000

Current Simplical Complex:  ['Stratum 5 SUMMER 10-16: ']
The shape is:  ['cube6_cluster3', 'cube5_cluster0', 'cube3_cluster3', 'cube4_cluster0', 'cube4_cluster5', 'cube7_cluster2']
The number of nodes in the shape is:  6

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000
mean,3.104057,0.197438,14.598462,9.880000,54.169231,492.476923,0.243061,49.165382,3.286154,40.858632,29.138462
std,0.890029,0.056823,1.088361,2.443115,43.849020,57.785192,0.260260,22.792386,3.077838,27.453464,7.950780
min,1.443500,0.104500,12.700000,4.300000,15.000000,391.000000,0.000000,16.400000,0.400000,9.239100,9.000000
25%,2.407371,0.158000,13.800000,8.300000,33.000000,450.000000,0.000000,29.883765,1.100000,19.422780,24.000000
50%,3.049000,0.180003,14.800000,9.500000,42.000000,476.000000,0.150000,42.224980,1.800000,35.873340,29.000000
75%,3.890000,0.230166,15.200000,11.400000,58.000000,549.000000,0.460000,63.900000,4.600000,55.224048,32.000000
max,5.079000,0.343000,17.500000,17.400000,290.000000,697.000000,0.950000,108.600000,11.900000,128.955279,50.000000

The shape is:  ['cube4_cluster4', 'cube4_cluster1', 'cube3_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,3.722854,0.229122,13.216667,10.177778,47.666667,468.777778,0.399353,61.049185,3.072222,74.669002,28.888889
std,0.537160,0.048966,2.792479,2.668014,15.373774,28.548319,0.278298,20.987317,1.971505,28.825740,6.858991
min,2.256000,0.179000,7.400000,3.600000,30.000000,433.000000,0.000000,27.927783,0.500000,14.983740,15.000000
25%,3.679250,0.206000,12.850000,9.650000,36.750000,453.000000,0.180000,51.125000,1.550000,59.852860,25.000000
50%,3.812000,0.212500,13.550000,10.750000,42.500000,462.500000,0.470000,61.850000,2.550000,74.388540,28.000000
75%,4.091750,0.233500,14.025000,11.675000,52.000000,478.000000,0.621272,71.500000,4.825000,93.167420,34.500000
max,4.332000,0.401000,21.000000,13.600000,90.000000,546.000000,0.820000,98.200000,7.100000,116.472380,41.000000

Current Simplical Complex:  ['Stratum 1 SUMMER 14-20: ']
The shape is:  ['cube4_cluster3', 'cube3_cluster2', 'cube2_cluster1']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,3.434286,0.245857,14.671429,10.171429,50.142857,532.571429,0.200000,55.600000,2.742857,60.493226,27.285714
std,1.243878,0.058590,1.307305,1.840031,24.279131,41.096866,0.268887,31.729429,2.613336,33.524581,4.231402
min,2.005000,0.161000,13.500000,8.100000,24.000000,474.000000,0.000000,25.800000,1.000000,19.422780,21.000000
25%,2.235000,0.208000,13.650000,8.350000,33.000000,501.500000,0.000000,31.400000,1.150000,37.135420,24.500000
50%,4.017000,0.236000,13.900000,10.900000,45.000000,541.000000,0.000000,40.700000,1.500000,53.542460,28.000000
75%,4.234500,0.292500,15.700000,11.650000,63.000000,561.500000,0.400000,75.650000,3.250000,80.133180,30.000000
max,5.079000,0.323000,16.600000,12.200000,90.000000,587.000000,0.600000,108.600000,7.900000,115.950140,33.000000

The shape is:  ['cube3_cluster3', 'cube1_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000
mean,3.302239,0.231246,14.066000,9.248000,67.22000,465.760000,0.328016,62.402774,2.69380,50.625349,26.500000
std,0.894698,0.084693,2.883352,2.323196,52.25303,57.520736,0.357167,38.945245,2.30758,34.404415,9.998469
min,1.730722,0.112000,6.500000,3.600000,21.00000,347.000000,0.000000,16.400000,0.50000,9.239100,9.000000
25%,2.659001,0.172846,12.825000,7.775000,37.00000,435.000000,0.000000,33.401423,1.10500,20.533367,21.000000
50%,3.259000,0.206305,14.500000,9.000000,45.50000,459.000000,0.285000,49.900000,1.80000,42.880060,28.000000
75%,3.924250,0.269000,15.675000,11.325000,85.25000,514.750000,0.572500,77.025000,3.22500,86.474527,34.500000
max,5.081000,0.429201,21.500000,13.600000,290.00000,585.000000,1.580000,187.900000,9.10000,116.472380,50.000000

Current Simplical Complex:  ['Stratum 2 SUMMER 14-20: ']
The shape is:  ['cube1_cluster2', 'cube4_cluster6', 'cube1_cluster12', 'cube3_cluster0', 'cube2_cluster2', 'cube1_cluster11']
The number of nodes in the shape is:  6

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000
mean,3.349398,0.189876,18.219318,8.777273,54.852273,460.022727,0.314724,61.123435,2.911818,45.731840,27.204545
std,1.000036,0.085555,6.244959,2.490475,37.690372,59.682489,0.305756,26.591726,2.478139,25.535968,7.239990
min,1.141000,0.033000,6.500000,3.600000,15.000000,318.000000,0.000000,17.400000,0.350000,9.239100,9.000000
25%,2.443668,0.143270,13.800000,7.100000,38.000000,412.000000,0.000000,43.750000,1.142500,25.189010,23.000000
50%,3.345231,0.205000,15.000000,8.400000,47.000000,457.500000,0.310000,57.100000,2.000000,39.152250,27.000000
75%,4.059000,0.236000,26.000000,10.400000,54.000000,486.250000,0.535000,70.575000,4.050000,61.931981,30.000000
max,6.805569,0.490000,28.000000,16.100000,290.000000,587.000000,1.048878,166.900000,10.400000,115.950140,50.000000

The shape is:  ['cube1_cluster8', 'cube2_cluster11', 'cube0_cluster3', 'cube0_cluster4']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000
mean,3.656135,0.253560,14.983333,9.404762,66.465650,381.714286,0.183074,72.057143,2.557857,38.518121,20.333333
std,1.645387,0.071038,2.311468,2.324625,35.215522,84.918694,0.327682,41.334443,2.233983,20.850960,6.802678
min,1.522000,0.048000,12.200000,5.900000,20.000000,262.000000,0.000000,18.300000,0.600000,7.306800,8.000000
25%,2.355597,0.204950,13.625000,8.200000,48.500000,325.000000,0.000000,44.725000,1.112500,28.389012,17.000000
50%,3.375500,0.251000,14.550000,8.600000,57.000000,335.500000,0.000000,53.900000,1.750000,34.847725,19.000000
75%,4.351625,0.292298,15.775000,9.875000,80.000000,472.000000,0.190000,101.775000,3.125000,43.597453,26.750000
max,9.568764,0.418000,26.100000,19.600000,190.000000,547.000000,1.010000,191.000000,9.200000,122.247510,33.000000

The shape is:  ['cube3_cluster1', 'cube4_cluster0', 'cube2_cluster6', 'cube2_cluster5']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,3.384641,0.244336,15.923529,10.135294,58.588235,453.176471,0.317353,56.037763,2.638235,63.599028,25.352941
std,1.020577,0.070702,4.323703,1.766331,30.653423,54.838667,0.469042,33.462926,2.550709,35.206793,9.746417
min,1.358000,0.174000,9.100000,7.400000,28.000000,330.000000,0.000000,20.705501,0.500000,12.278790,9.000000
25%,2.788000,0.190000,12.800000,9.000000,34.000000,436.000000,0.000000,33.800000,1.050000,34.480700,16.000000
50%,3.655000,0.200189,15.200000,10.200000,43.000000,459.000000,0.025000,51.300000,1.500000,55.369370,27.000000
75%,4.008000,0.302000,21.100000,11.500000,77.000000,466.000000,0.640000,66.800000,2.700000,98.752420,35.000000
max,4.904000,0.401000,21.900000,13.500000,140.000000,552.000000,1.580000,164.100000,8.300000,116.472380,39.000000

The shape is:  ['cube4_cluster2', 'cube3_cluster2', 'cube5_cluster8']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.0000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,2.980966,0.283055,15.640909,8.213636,91.727273,395.5000,0.391320,131.132651,3.844091,64.756948,18.954545
std,1.024101,0.104565,1.137105,1.957475,58.239393,83.8671,0.359168,97.486979,2.761350,34.187056,7.040544
min,1.986000,0.130168,13.800000,5.000000,35.000000,227.0000,0.000000,27.586596,0.800000,10.711221,6.000000
25%,2.130500,0.191147,14.925000,7.400000,53.500000,343.5000,0.008662,57.762500,2.250000,33.609826,13.750000
50%,2.639842,0.283938,15.500000,7.700000,71.000000,371.5000,0.337407,109.100000,2.900000,66.531975,20.000000
75%,3.629566,0.347000,16.200000,8.175000,117.500000,467.5000,0.647500,195.250000,4.950000,92.439943,22.000000
max,4.929042,0.470000,17.800000,13.600000,280.000000,551.0000,1.020000,307.700000,11.400000,119.127830,30.000000

The shape is:  ['cube4_cluster7', 'cube5_cluster11', 'cube6_cluster13']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.00000
mean,3.420105,0.283928,18.885714,9.921429,89.928571,381.571429,0.472313,143.592857,3.233571,109.169923,18.00000
std,1.299922,0.069366,2.445988,1.022951,45.316773,49.506354,0.412988,76.937082,2.118928,55.552916,5.58845
min,2.181000,0.161721,17.000000,8.100000,51.000000,310.000000,0.000000,51.000000,0.870000,23.295160,8.00000
25%,2.474750,0.219986,17.425000,9.125000,57.000000,361.500000,0.000000,109.000000,1.375000,53.322080,14.00000
50%,2.975578,0.302500,17.900000,10.300000,61.500000,374.500000,0.564361,119.750000,2.700000,120.346455,20.00000
75%,4.121873,0.330750,18.425000,10.700000,120.000000,375.000000,0.758532,143.675000,5.212500,157.173303,22.00000
max,5.941145,0.382000,24.200000,11.300000,200.000000,468.000000,1.127214,283.400000,6.400000,183.861190,26.00000

The shape is:  ['cube2_cluster3', 'cube0_cluster6', 'cube1_cluster3']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,2.901495,0.242016,17.241667,8.775000,57.000000,368.083333,0.146667,49.391667,1.440000,44.721203,26.083333
std,0.848705,0.093258,2.338009,2.192601,22.667558,95.990017,0.291901,22.761469,0.646248,34.238140,11.595127
min,1.817000,0.112000,14.900000,4.300000,21.000000,257.000000,0.000000,16.400000,0.700000,13.155900,11.000000
25%,2.125750,0.155750,15.000000,8.075000,46.250000,271.000000,0.000000,30.250000,0.967500,24.624517,19.000000
50%,2.851500,0.253574,16.850000,8.500000,59.500000,386.000000,0.000000,50.900000,1.415000,36.895015,23.000000
75%,3.537987,0.283237,18.500000,9.250000,69.500000,431.250000,0.092500,63.000000,1.575000,51.372280,30.250000
max,4.101484,0.434000,22.000000,13.300000,92.000000,546.000000,0.910000,87.300000,2.900000,141.453040,50.000000

The shape is:  ['cube2_cluster12', 'cube1_cluster13', 'cube3_cluster8']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,3.058328,0.133822,26.719355,8.729032,42.179149,356.677419,0.232550,43.945161,3.381935,42.047066,34.580645
std,0.703530,0.068038,0.809699,2.471868,25.638256,39.487878,0.262698,28.067844,2.194239,29.312069,8.558716
min,0.951000,0.033480,25.800000,5.000000,13.000000,279.000000,0.000000,16.500000,0.360000,19.703740,14.000000
25%,2.977000,0.107181,26.100000,7.450000,29.000000,315.500000,0.000000,28.300000,1.275000,26.483670,29.500000
50%,3.185556,0.139000,26.500000,7.900000,37.000000,364.000000,0.156854,35.800000,3.500000,28.970780,35.000000
75%,3.417414,0.150474,27.050000,8.900000,41.079688,393.000000,0.427483,45.850000,5.200000,36.295830,39.500000
max,4.300000,0.447720,29.000000,15.000000,146.125745,423.000000,0.880000,161.900000,7.300000,126.342840,55.000000

Current Simplical Complex:  ['Stratum 3 SUMMER 14-20: ']
The shape is:  ['cube4_cluster1', 'cube4_cluster34', 'cube3_cluster0', 'cube2_cluster5']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000
mean,3.532080,0.218316,14.478261,10.034783,53.826087,457.434783,0.297751,60.975077,2.836957,67.540197,28.869565
std,0.730439,0.063205,3.264542,2.166818,36.228633,60.567638,0.325779,28.627023,2.329564,32.085579,6.804439
min,2.081000,0.131354,9.100000,4.200000,22.000000,312.000000,0.000000,25.300000,0.500000,13.155900,14.000000
25%,2.950684,0.179500,13.000000,8.750000,36.500000,440.500000,0.000000,43.200000,1.100000,43.315260,27.000000
50%,3.775000,0.209000,14.100000,10.300000,43.000000,459.000000,0.140000,55.700000,1.800000,63.726140,30.000000
75%,4.029500,0.239000,15.300000,11.550000,52.000000,481.500000,0.555000,68.850000,4.900000,92.579900,33.000000
max,5.054338,0.401000,23.100000,13.600000,200.000000,585.000000,0.929917,127.300000,9.100000,121.694780,41.000000

Current Simplical Complex:  ['Stratum 4 SUMMER 14-20: ']
The shape is:  ['cube3_cluster1', 'cube1_cluster0', 'cube0_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,3.392100,0.197400,15.170000,8.310000,62.500000,459.200000,0.218844,57.720000,2.890000,34.210876,27.900000
std,0.798008,0.057417,0.551866,1.587066,50.255459,46.329256,0.279500,27.457919,2.585623,17.905973,8.999383
min,1.910000,0.112000,14.200000,4.300000,21.000000,391.000000,0.000000,16.400000,0.500000,9.239100,17.000000
25%,2.879750,0.160250,14.925000,8.425000,39.000000,435.500000,0.000000,41.050000,1.500000,21.163580,22.750000
50%,3.364500,0.188000,15.000000,8.800000,49.000000,450.000000,0.045000,55.000000,1.800000,35.438140,27.500000
75%,3.932000,0.234000,15.575000,9.300000,58.000000,472.250000,0.441333,78.225000,3.750000,43.380540,29.750000
max,4.548000,0.290000,16.000000,9.500000,200.000000,558.000000,0.690000,96.800000,9.100000,63.726140,50.000000

Current Simplical Complex:  ['Stratum 5 SUMMER 14-20: ']
The shape is:  ['cube3_cluster0', 'cube5_cluster0', 'cube6_cluster1', 'cube2_cluster2', 'cube4_cluster0', 'cube2_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  7

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,3.389539,0.207793,14.570833,9.439583,57.125000,492.625000,0.246721,55.033648,2.977083,44.047988,27.645833
std,0.908003,0.053925,1.747212,2.330988,44.936658,56.412095,0.247249,21.602929,2.782104,25.281331,6.966453
min,1.828000,0.112000,7.400000,4.200000,18.000000,391.000000,0.000000,16.400000,0.500000,9.239100,17.000000
25%,2.600251,0.168101,13.575000,8.100000,37.750000,454.750000,0.000000,39.833143,1.200000,21.969527,22.750000
50%,3.493500,0.201134,14.850000,9.300000,45.000000,475.500000,0.210000,52.392821,1.800000,38.870089,27.000000
75%,4.099500,0.233000,15.200000,11.000000,60.250000,549.000000,0.472111,68.612500,3.300000,63.834940,30.000000
max,5.079000,0.343000,21.000000,17.000000,290.000000,661.000000,0.690000,108.600000,11.900000,115.950140,50.000000

The shape is:  ['cube2_cluster3', 'cube0_cluster0', 'cube3_cluster1', 'cube0_cluster2', 'cube1_cluster0']
The number of nodes in the shape is:  5

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,2.846658,0.188834,14.277778,10.433333,44.777778,485.222222,0.187778,42.402675,1.988889,51.607963,30.444444
std,0.831777,0.039561,1.234578,3.241278,35.341287,67.664880,0.288904,17.734787,1.754956,31.301006,9.179403
min,1.398977,0.103728,10.800000,3.600000,16.000000,409.000000,0.000000,23.400000,0.400000,10.711221,9.000000
25%,2.151311,0.162844,13.800000,8.625000,28.000000,436.000000,0.000000,28.679983,0.825000,31.348658,26.250000
50%,2.789684,0.191026,14.150000,10.450000,37.500000,480.500000,0.000000,37.812927,1.150000,40.344918,29.500000
75%,3.407639,0.222493,14.975000,11.700000,43.000000,513.750000,0.440000,53.050557,2.700000,63.028092,36.000000
max,4.248363,0.241648,15.900000,17.400000,175.000000,697.000000,0.820000,93.093305,6.300000,123.995324,50.000000

The shape is:  ['cube5_cluster4', 'cube4_cluster3', 'cube3_cluster2']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,3.497237,0.229719,11.820000,11.900000,42.500000,479.700000,0.325000,52.760084,2.610000,98.115644,31.600000
std,0.699790,0.065094,1.514229,1.032796,17.583136,52.552725,0.311849,29.326419,2.154814,16.559902,6.619836
min,2.256000,0.179000,9.100000,10.300000,30.000000,436.000000,0.000000,20.705501,0.500000,61.724220,15.000000
25%,3.052277,0.196750,10.625000,11.525000,33.750000,441.750000,0.035000,30.324914,0.950000,91.992380,30.250000
50%,3.854000,0.200094,12.500000,11.750000,36.500000,458.000000,0.235000,43.198477,2.100000,98.846780,34.000000
75%,3.987250,0.241500,12.975000,12.100000,42.500000,508.750000,0.632500,66.000000,3.525000,105.418300,35.000000
max,4.079000,0.401000,13.000000,13.600000,90.000000,585.000000,0.770000,111.599994,7.100000,121.694780,39.000000

The shape is:  ['cube3_cluster3', 'cube4_cluster4', 'cube2_cluster5']
The number of nodes in the shape is:  3

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.00000
mean,2.838059,0.167787,13.975000,10.025000,48.625000,463.125000,0.492624,33.647097,5.037500,30.593369,26.12500
std,0.522171,0.033308,0.494975,0.688165,11.488348,21.397179,0.224189,8.226980,3.607903,19.595197,1.95941
min,2.214889,0.123522,13.000000,8.600000,38.000000,417.000000,0.270000,26.570509,1.100000,10.457550,23.00000
25%,2.501092,0.153944,13.875000,9.925000,39.500000,458.500000,0.340095,28.727851,1.850000,15.493478,24.75000
50%,2.678915,0.166246,14.100000,10.250000,47.500000,465.500000,0.433767,29.679338,4.450000,23.018276,27.00000
75%,3.211816,0.179946,14.250000,10.500000,51.000000,479.250000,0.545000,37.134502,8.275000,48.514649,27.00000
max,3.772103,0.230166,14.500000,10.600000,72.000000,484.000000,0.950000,50.814715,10.400000,58.835595,29.00000

# Analyzing the largest structure
Largest = Node count of the shape. The largest structure is likely to be the dominant feature of the stratum during this particular time period. As such, it is important to analyze the nodes within it. To do this, we generate all the shapes, and since the shapes are returned in descending order of the number of nodes per shape, we pull the first shape. From here, we can preform an analysis on each one.

In [23]:
allComplices = list(jsonData.keys())
for key in allComplices[0:3]: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    largestShape = clean_getShapes(scomplex)[0]
    npLargestShape = np.array(largestShape).flatten()
    nodes = scomplex.get('nodes')
    print("Largest shape is: ", largestShape)
    print("Number of nodes is: ", len(largestShape))
    for node in npLargestShape:
        summary = nodeDataSummary(node, scomplex,variables,df)
        if summary.loc['count'][0] > 5: # 5 is chosen arbitraily
            print("Information for: ", node)
            display(summary)

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
Largest shape is:  ['cube7_cluster1', 'cube6_cluster0', 'cube3_cluster0', 'cube5_cluster0', 'cube4_cluster0', 'cube5_cluster1', 'cube5_cluster5', 'cube7_cluster0', 'cube2_cluster0', 'cube5_cluster11', 'cube1_cluster0', 'cube2_cluster6']
Number of nodes is:  12
Information for:  cube6_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,3.104918,0.218218,14.715152,8.915152,60.575758,468.393939,0.362554,63.492205,3.023333,45.399381,25.030303
std,0.933327,0.089223,2.329716,1.837308,36.170629,55.167325,0.356081,36.833492,2.688964,33.196787,9.524589
min,1.730722,0.112000,6.500000,4.300000,21.000000,353.000000,0.000000,16.400000,0.500000,10.457550,9.000000
25%,2.388667,0.158000,14.000000,8.000000,38.000000,433.000000,0.000000,40.049999,1.100000,18.908110,20.000000
50%,3.023000,0.180000,14.900000,9.000000,46.000000,460.000000,0.343460,51.585642,1.800000,32.315664,27.000000
75%,3.661000,0.274000,15.900000,10.200000,71.000000,511.000000,0.570000,78.600000,4.300000,63.726140,30.000000
max,5.081000,0.429201,18.500000,12.200000,150.000000,577.000000,1.580000,187.900000,10.400000,128.955279,50.000000

Information for:  cube3_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.00000,16.000000,16.000000,16.000000,16.000000,16.000000
mean,3.518011,0.206031,14.256250,10.606250,43.687500,491.56250,0.326901,55.139887,3.325000,65.554711,28.875000
std,0.955304,0.049266,2.283263,1.339387,14.938624,42.36031,0.285486,23.954470,2.813894,33.395974,4.716991
min,2.005000,0.113500,10.800000,8.100000,24.000000,438.00000,0.000000,25.050000,0.500000,13.880215,20.000000
25%,2.705777,0.176484,13.150000,9.500000,37.000000,466.25000,0.000000,38.375000,1.350000,39.898940,26.000000
50%,4.027500,0.204094,13.700000,10.800000,41.000000,480.50000,0.435000,50.534611,2.250000,67.599420,29.000000
75%,4.108000,0.217750,15.025000,11.650000,45.000000,498.75000,0.515000,67.287500,4.400000,87.052860,31.500000
max,5.079000,0.323000,21.000000,12.200000,90.000000,587.00000,0.770000,108.600000,10.100000,121.694780,38.000000

Information for:  cube5_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,2.939207,0.203664,14.544444,9.488889,49.555556,478.666667,0.195770,66.316847,2.500000,59.710918,27.666667
std,1.099083,0.058031,1.894803,1.611245,22.661151,61.868813,0.257761,22.266231,2.330772,42.144041,4.358899
min,1.730722,0.146000,9.800000,6.500000,26.000000,414.000000,0.000000,36.400000,0.500000,12.324687,20.000000
25%,2.011813,0.169333,14.500000,8.600000,33.000000,424.000000,0.000000,50.814715,0.800000,26.361600,27.000000
50%,2.580412,0.177853,15.000000,10.100000,49.000000,458.000000,0.000000,57.550000,1.100000,53.784945,27.000000
75%,4.051720,0.207609,15.700000,10.200000,55.000000,553.000000,0.330000,87.120101,4.300000,80.039369,30.000000
max,4.728380,0.314771,16.000000,12.200000,98.000000,564.000000,0.680000,99.870281,7.000000,128.955279,35.000000

Information for:  cube4_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,3.397022,0.225957,13.503846,9.846154,51.153846,482.807692,0.271939,58.407601,2.977692,57.815523,27.461538
std,0.916797,0.066627,2.914444,2.574681,25.318282,53.117996,0.295448,30.894689,2.778859,33.844147,7.553705
min,1.828000,0.137571,9.100000,3.600000,25.000000,356.000000,0.000000,20.705501,0.400000,13.698400,11.000000
25%,2.492250,0.181750,12.425000,8.200000,35.250000,450.250000,0.000000,32.537502,1.105000,24.793764,23.000000
50%,3.717500,0.211500,13.350000,10.450000,41.000000,475.000000,0.150000,51.400000,1.750000,56.335172,27.500000
75%,4.069954,0.242010,14.600000,11.800000,60.000000,523.750000,0.502500,70.916500,4.475000,89.990460,34.500000
max,5.079000,0.401000,21.500000,13.600000,130.000000,585.000000,0.820000,142.300000,10.100000,116.472380,41.000000

Information for:  cube5_cluster1

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
mean,3.296776,0.219613,13.655556,9.707407,52.592593,467.888889,0.287350,58.767816,2.978519,57.992702,28.222222
std,0.876107,0.067662,2.599753,2.515020,30.086106,58.903006,0.319923,37.382394,2.575715,33.499245,9.373996
min,1.828000,0.112000,9.100000,4.200000,21.000000,347.000000,0.000000,16.400000,0.400000,13.329980,11.000000
25%,2.530500,0.180524,12.850000,7.900000,34.000000,435.000000,0.000000,29.746849,1.110000,23.989889,22.000000
50%,3.549806,0.211000,13.500000,9.900000,39.000000,460.000000,0.160000,49.600000,1.800000,57.340743,28.000000
75%,3.894500,0.240020,15.300000,11.850000,59.000000,517.500000,0.484222,76.950000,4.450000,90.012220,35.000000
max,4.904000,0.401000,21.500000,13.600000,140.000000,585.000000,1.060000,164.100000,9.000000,116.472380,50.000000

Information for:  cube2_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,4.046481,0.211170,12.357143,10.042857,44.571429,486.571429,0.412857,57.148255,3.014286,75.476540,28.428571
std,0.621893,0.019548,2.356450,2.681329,9.289010,56.568122,0.340182,15.284769,2.324097,35.213283,4.503967
min,2.852369,0.184000,7.400000,4.400000,36.000000,436.000000,0.000000,32.368564,0.500000,29.954620,21.000000
25%,3.980000,0.200094,12.200000,9.600000,39.000000,447.500000,0.100000,46.534611,1.450000,46.666300,26.000000
50%,4.065000,0.208000,13.000000,11.500000,41.000000,460.000000,0.510000,65.200000,2.700000,77.739580,30.000000
75%,4.256500,0.223500,13.500000,11.550000,47.500000,521.500000,0.705000,68.850000,3.950000,102.807100,30.500000
max,4.935000,0.239000,14.700000,12.100000,62.000000,572.000000,0.770000,71.700000,7.100000,121.694780,35.000000

Current Simplical Complex:  ['Stratum 2 SUMMER 93-00: ']
Largest shape is:  ['cube1_cluster1', 'cube4_cluster2', 'cube6_cluster0', 'cube4_cluster1', 'cube3_cluster0', 'cube1_cluster4', 'cube5_cluster4', 'cube5_cluster1', 'cube7_cluster0', 'cube2_cluster0', 'cube2_cluster8', 'cube5_cluster2']
Number of nodes is:  12
Information for:  cube6_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,2.874758,0.187834,14.292308,9.761538,56.884615,476.115385,0.308587,54.439602,3.057692,42.690793,27.000000
std,0.809294,0.064617,1.521032,2.578384,39.076670,60.255673,0.292896,55.113292,2.378264,28.683554,6.922427
min,1.579083,0.114262,10.100000,5.000000,21.000000,319.000000,0.000000,26.570509,0.400000,10.457550,9.000000
25%,2.360289,0.148167,13.800000,8.300000,35.500000,435.250000,0.000000,29.172888,1.100000,17.050873,24.000000
50%,2.572784,0.173246,14.300000,9.950000,41.500000,472.500000,0.316730,38.634429,2.400000,38.945865,27.500000
75%,3.237929,0.184671,15.075000,10.575000,67.000000,520.500000,0.575000,52.687500,4.575000,61.238818,30.000000
max,4.904000,0.379000,17.500000,17.400000,175.000000,585.000000,0.950000,304.500000,8.500000,123.995324,39.000000

Information for:  cube4_cluster1

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,134.000000,134.000000,134.000000,134.00000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000
mean,3.358409,0.232758,17.261194,9.16194,62.541472,438.619403,0.325316,68.717604,3.080970,52.757797,25.149254
std,1.150644,0.108695,4.747139,2.48205,47.379981,81.624649,0.363348,45.603523,2.648529,38.673501,8.810031
min,1.358000,0.033000,6.500000,4.90000,15.000000,238.000000,0.000000,17.400000,0.400000,9.239100,5.000000
25%,2.317025,0.170657,14.200000,7.42500,37.000000,375.000000,0.000000,39.935114,1.162500,25.427500,20.000000
50%,3.308500,0.231332,15.700000,8.55000,51.000000,450.000000,0.200000,55.731264,2.000000,39.134700,25.500000
75%,4.063000,0.284663,18.500000,10.87500,66.000000,497.750000,0.590000,83.000000,4.100000,67.444385,30.750000
max,6.805569,0.972000,28.000000,19.60000,360.000000,661.000000,1.580000,276.400000,11.900000,183.861190,50.000000

Information for:  cube3_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000
mean,3.627204,0.242217,17.864762,8.580952,67.176736,408.790476,0.320706,82.592396,2.974952,56.131827,23.742857
std,1.348256,0.117491,4.613692,2.360415,48.907799,81.342190,0.362789,61.426328,2.214768,40.725919,9.312965
min,1.817000,0.033000,9.900000,4.300000,15.000000,227.000000,0.000000,16.400000,0.500000,13.155900,5.000000
25%,2.519000,0.181000,14.900000,7.200000,42.557286,356.000000,0.000000,45.200000,1.300000,27.199140,18.000000
50%,3.440000,0.240000,16.000000,8.200000,53.000000,397.000000,0.139740,60.500000,2.000000,41.530940,23.000000
75%,4.190000,0.291000,18.600000,9.400000,73.000000,467.000000,0.630000,110.900000,4.200000,70.285340,29.000000
max,9.568764,0.972000,28.000000,19.600000,360.000000,572.000000,1.110000,307.700000,9.100000,183.861190,50.000000

Information for:  cube5_cluster1

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000
mean,2.924969,0.239530,14.851852,10.144444,63.648148,484.944444,0.292237,61.212475,2.748519,47.377089,26.555556
std,1.004317,0.089350,3.370054,2.468799,51.712981,77.659007,0.362834,36.632992,2.965279,30.447348,9.733557
min,1.358000,0.104500,6.500000,6.200000,16.000000,318.000000,0.000000,26.650000,0.400000,9.239100,9.000000
25%,2.143625,0.173500,13.000000,8.225000,33.000000,451.500000,0.000000,37.000001,0.902500,23.531564,20.000000
50%,2.553001,0.225356,14.400000,9.650000,41.000000,478.000000,0.087302,46.246785,1.550000,38.971884,28.000000
75%,3.659500,0.281344,16.000000,11.900000,73.750000,525.250000,0.530000,71.579000,3.000000,60.836804,33.000000
max,5.081000,0.490000,23.100000,17.000000,290.000000,697.000000,1.580000,187.900000,11.900000,116.472380,50.000000

Information for:  cube7_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,2.673400,0.191566,14.461538,10.715385,49.230769,460.615385,0.304497,62.677530,3.346154,43.208874,27.000000
std,0.782045,0.083973,1.017790,2.565101,39.507708,58.079742,0.324082,75.558340,2.865489,29.215584,5.901977
min,2.011813,0.114262,13.000000,7.600000,21.000000,319.000000,0.000000,27.127421,0.500000,10.457550,12.000000
25%,2.206000,0.130168,13.800000,9.700000,34.000000,435.000000,0.000000,29.108269,1.100000,18.554266,25.000000
50%,2.445000,0.161869,14.200000,10.300000,37.000000,466.000000,0.343460,36.884728,2.700000,37.492311,27.000000
75%,2.777417,0.222573,15.200000,10.600000,40.000000,484.000000,0.500000,41.301020,4.300000,59.782611,30.000000
max,4.904000,0.379000,16.000000,17.400000,170.000000,552.000000,0.950000,304.500000,8.500000,116.966006,36.000000

Information for:  cube2_cluster0

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,3.583200,0.246800,14.926667,7.866667,62.333333,446.400000,0.281545,92.155552,2.660000,55.059419,25.800000
std,0.897741,0.101071,2.841143,2.657783,34.258819,52.633232,0.317349,83.038262,1.742248,34.921559,11.983322
min,1.986000,0.112000,7.400000,3.600000,21.000000,332.000000,0.000000,16.400000,0.500000,13.329980,8.000000
25%,3.085000,0.190000,14.200000,6.050000,38.500000,433.000000,0.000000,38.763891,1.500000,26.908220,20.500000
50%,3.783000,0.228000,15.000000,8.200000,60.000000,451.000000,0.169663,65.200000,1.800000,51.801660,24.000000
75%,4.204000,0.274000,16.100000,9.300000,71.000000,469.000000,0.479222,97.500000,3.900000,74.973795,30.500000
max,4.935000,0.470000,21.000000,12.100000,150.000000,572.000000,0.880000,287.800000,6.300000,116.983050,50.000000

Information for:  cube2_cluster8

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,3.851035,0.275037,14.033333,8.320000,76.866667,347.533333,0.237187,85.753333,2.842667,36.319824,17.333333
std,2.251440,0.066361,0.670465,1.000857,33.079702,62.956750,0.359496,49.273636,2.271247,16.847317,5.702965
min,1.993000,0.178159,13.100000,5.900000,44.000000,262.000000,0.000000,38.400000,0.770000,13.936120,8.000000
25%,2.299064,0.216111,13.500000,8.150000,53.500000,323.500000,0.000000,52.050000,1.185000,23.392650,13.500000
50%,2.808000,0.279000,14.100000,8.200000,64.000000,330.000000,0.000000,68.000000,1.900000,34.311530,17.000000
75%,4.507440,0.323500,14.700000,8.750000,93.000000,338.500000,0.555000,116.500000,3.600000,44.450490,18.500000
max,9.568764,0.393000,14.900000,10.500000,160.000000,498.000000,0.950000,191.000000,8.700000,65.508330,28.000000

Information for:  cube5_cluster2

,PREDICTED_TN,PREDICTED_TP,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_COND,PREDICTED_VEL,PREDICTED_SS,PREDICTED_WDP,PREDICTED_CHLcal,PREDICTED_SECCHI
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,3.597144,0.176246,14.466667,8.950000,55.500000,472.000000,0.408333,49.235272,4.016667,43.806912,27.000000
std,0.733582,0.006007,0.488535,2.172326,13.780421,44.036349,0.264984,18.916234,2.083667,25.972109,4.560702
min,2.388667,0.169333,13.900000,5.000000,39.000000,417.000000,0.000000,26.570509,1.200000,10.711221,18.000000
25%,3.264633,0.173061,14.050000,8.700000,46.750000,458.750000,0.275000,36.985281,2.650000,20.932986,27.250000
50%,3.750704,0.174520,14.500000,9.250000,52.000000,463.000000,0.445000,48.145563,4.450000,54.534267,28.500000
75%,4.194036,0.178856,14.875000,10.025000,67.750000,476.250000,0.607500,57.550000,4.825000,63.372268,29.750000
max,4.248363,0.186227,15.000000,11.400000,72.000000,551.000000,0.680000,78.600000,7.000000,67.010894,30.000000

Current Simplical Complex:  ['Stratum 3 SUMMER 93-00: ']
Largest shape is:  ['cube3_cluster17']
Number of nodes is:  1

# Condensing 1-simplices
Currently, many one simplices that we have contain information that means one of them is a subset of the other. To resolve this, we replace them with one cluster with all the indices in one node.

This is stored in the function `clean_getShapes(scomplex)` function. Below is a comparison of running the two functions

In [7]:
allComplices = list(jsonData.keys())
print("Standard shape version")
for key in allComplices[0:1]:
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    nodes = scomplex.get('nodes')
    shapes = getShapes(scomplex)
    for shape in shapes:
        indices = []
        for node in shape:
            indices.append(nodes.get(node))
        indices = list(set([item for sublist in indices for item in sublist]))
        print(str(shape) + " : " + str(indices))

print("Clean shape version")
for key in allComplices[0:1]:
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    nodes = scomplex.get('nodes')
    cleanShapes = clean_getShapes(scomplex)
    for shape in cleanShapes:
        indices = []
        for node in shape:
            indices.append(nodes.get(node))
        indices = list(set([item for sublist in indices for item in sublist]))
        print(str(shape) + " : " + str(indices))

Standard shape version
Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
['cube7_cluster1', 'cube6_cluster0', 'cube3_cluster0', 'cube5_cluster0', 'cube4_cluster0', 'cube5_cluster1', 'cube5_cluster5', 'cube7_cluster0', 'cube2_cluster0', 'cube5_cluster11', 'cube1_cluster0', 'cube2_cluster6'] : [0, 1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 24, 25, 26, 27, 29, 33, 34, 35, 37, 39, 40, 41, 42, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 64, 65, 69, 70, 71, 72, 73, 74, 76, 77, 78, 87, 88, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 116, 117, 118, 119]
['cube4_cluster5', 'cube5_cluster8'] : [82]
['cube1_cluster2', 'cube2_cluster2'] : [23]
['cube3_cluster1', 'cube2_cluster3'] : [30]
['cube1_cluster8', 'cube2_cluster10'] : [100]
['cube3_cluster2', 'cube2_cluster7'] : [66]
['cube5_cluster2', 'cube4_cluster1'] : [16, 32]
['cube6_cluster6', 'cube7_cluster6'] : [96, 94, 95]
['cube3_cluster4', 'cube4_cluster6'] : [85]
['cube4_cluster4', 'cube5_cluster7'] : [81, 83]
['cube6_cluster5', 'cube7_cluster5'] : [93]
['cube1_cluster7', 'cube2_cluster9'] : [75]
['cube2_cluster8', 'cube1_cluster6'] : [68]
['cube6_cluster3', 'cube5_cluster10'] : [97, 98, 99, 101, 102, 89]
['cube6_cluster4', 'cube7_cluster4'] : [92]
['cube4_cluster7', 'cube5_cluster9'] : [86]
['cube3_cluster3', 'cube4_cluster2'] : [79]
['cube4_cluster3', 'cube5_cluster6'] : [80, 84]
['cube2_cluster5', 'cube1_cluster4'] : [36]
['cube3_cluster6', 'cube4_cluster9'] : [91]
['cube2_cluster11', 'cube1_cluster9'] : [106]
['cube4_cluster8', 'cube3_cluster5'] : [90]
['cube1_cluster5', 'cube0_cluster1'] : [44, 38]
['cube2_cluster4', 'cube1_cluster3'] : [31]
['cube7_cluster3', 'cube6_cluster1'] : [8]
['cube1_cluster1', 'cube2_cluster1'] : [20]
['cube5_cluster4', 'cube6_cluster2'] : [67]
['cube0_cluster2'] : [43]
['cube5_cluster3'] : [59]
['cube0_cluster3'] : [103]
['cube7_cluster2'] : [7]
['cube9_cluster0'] : [9, 10]
['cube0_cluster0'] : [28]
['cube0_cluster4'] : [115]
['cube8_cluster0'] : [6]
Clean shape version
Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
['cube7_cluster1', 'cube6_cluster0', 'cube3_cluster0', 'cube5_cluster0', 'cube4_cluster0', 'cube5_cluster1', 'cube5_cluster5', 'cube7_cluster0', 'cube2_cluster0', 'cube5_cluster11', 'cube1_cluster0', 'cube2_cluster6'] : [0, 1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 24, 25, 26, 27, 29, 33, 34, 35, 37, 39, 40, 41, 42, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 64, 65, 69, 70, 71, 72, 73, 74, 76, 77, 78, 87, 88, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 116, 117, 118, 119]
['cube5_cluster8'] : [82]
['cube2_cluster2'] : [23]
['cube2_cluster3'] : [30]
['cube2_cluster10'] : [100]
['cube2_cluster7'] : [66]
['cube4_cluster1'] : [16, 32]
['cube7_cluster6'] : [96, 94, 95]
['cube4_cluster6'] : [85]
['cube5_cluster7'] : [81, 83]
['cube7_cluster5'] : [93]
['cube2_cluster9'] : [75]
['cube1_cluster6'] : [68]
['cube6_cluster3'] : [97, 98, 99, 101, 102, 89]
['cube7_cluster4'] : [92]
['cube5_cluster9'] : [86]
['cube4_cluster2'] : [79]
['cube5_cluster6'] : [80, 84]
['cube1_cluster4'] : [36]
['cube4_cluster9'] : [91]
['cube1_cluster9'] : [106]
['cube3_cluster5'] : [90]
['cube0_cluster1'] : [44, 38]
['cube1_cluster3'] : [31]
['cube6_cluster1'] : [8]
['cube2_cluster1'] : [20]
['cube6_cluster2'] : [67]
['cube0_cluster2'] : [43]
['cube5_cluster3'] : [59]
['cube0_cluster3'] : [103]
['cube7_cluster2'] : [7]
['cube9_cluster0'] : [9, 10]
['cube0_cluster0'] : [28]
['cube0_cluster4'] : [115]
['cube8_cluster0'] : [6]

# Unique Samples
Something Killian was talking about

In [10]:
allComplices = list(jsonData.keys())
for key in allComplices[0:1]: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
{'cube0_cluster0': [28], 'cube0_cluster1': [38, 44], 'cube0_cluster2': [43], 'cube0_cluster3': [103], 'cube0_cluster4': [115], 'cube1_cluster0': [19], 'cube1_cluster1': [20], 'cube1_cluster2': [23], 'cube1_cluster3': [31], 'cube1_cluster4': [36], 'cube1_cluster5': [38, 44], 'cube1_cluster6': [68], 'cube1_cluster7': [75], 'cube1_cluster8': [100], 'cube1_cluster9': [106], 'cube2_cluster0': [19, 24, 26, 29, 50, 54, 55], 'cube2_cluster1': [20], 'cube2_cluster2': [23], 'cube2_cluster3': [30], 'cube2_cluster4': [31], 'cube2_cluster5': [36], 'cube2_cluster6': [60], 'cube2_cluster7': [66], 'cube2_cluster8': [68], 'cube2_cluster9': [75], 'cube2_cluster10': [100], 'cube2_cluster11': [106], 'cube3_cluster0': [22, 24, 25, 27, 29, 33, 34, 35, 37, 39, 41, 50, 54, 57, 60, 73], 'cube3_cluster1': [30], 'cube3_cluster2': [66], 'cube3_cluster3': [79], 'cube3_cluster4': [85], 'cube3_cluster5': [90], 'cube3_cluster6': [91], 'cube4_cluster0': [15, 18, 22, 25, 27, 33, 40, 41, 42, 45, 46, 47, 48, 49, 51, 52, 53, 56, 57, 58, 87, 88, 107, 108, 109, 113], 'cube4_cluster1': [16, 32], 'cube4_cluster2': [79], 'cube4_cluster3': [80, 84], 'cube4_cluster4': [81, 83], 'cube4_cluster5': [82], 'cube4_cluster6': [85], 'cube4_cluster7': [86], 'cube4_cluster8': [90], 'cube4_cluster9': [91], 'cube5_cluster0': [1, 61, 62, 63, 64, 65, 69, 70, 105], 'cube5_cluster1': [11, 12, 13, 14, 17, 18, 21, 40, 42, 45, 46, 47, 48, 49, 51, 52, 53, 56, 58, 87, 88, 104, 107, 108, 109, 113, 114], 'cube5_cluster2': [16, 32], 'cube5_cluster3': [59], 'cube5_cluster4': [67], 'cube5_cluster5': [77], 'cube5_cluster6': [80, 84], 'cube5_cluster7': [81, 83], 'cube5_cluster8': [82], 'cube5_cluster9': [86], 'cube5_cluster10': [98, 99, 101, 102], 'cube5_cluster11': [116, 117, 118, 119], 'cube6_cluster0': [0, 1, 2, 3, 4, 5, 11, 12, 13, 14, 17, 61, 62, 63, 64, 65, 69, 70, 71, 72, 74, 76, 77, 78, 104, 105, 110, 111, 112, 116, 117, 118, 119], 'cube6_cluster1': [8], 'cube6_cluster2': [67], 'cube6_cluster3': [89, 97, 98, 99, 101, 102], 'cube6_cluster4': [92], 'cube6_cluster5': [93], 'cube6_cluster6': [94, 95, 96], 'cube7_cluster0': [3, 4, 71], 'cube7_cluster1': [5], 'cube7_cluster2': [7], 'cube7_cluster3': [8], 'cube7_cluster4': [92], 'cube7_cluster5': [93], 'cube7_cluster6': [94, 95, 96], 'cube8_cluster0': [6], 'cube9_cluster0': [9, 10]}
{'cube0_cluster1': ['cube1_cluster5'], 'cube1_cluster0': ['cube2_cluster0'], 'cube1_cluster1': ['cube2_cluster1'], 'cube1_cluster2': ['cube2_cluster2'], 'cube1_cluster3': ['cube2_cluster4'], 'cube1_cluster4': ['cube2_cluster5'], 'cube1_cluster6': ['cube2_cluster8'], 'cube1_cluster7': ['cube2_cluster9'], 'cube1_cluster8': ['cube2_cluster10'], 'cube1_cluster9': ['cube2_cluster11'], 'cube2_cluster0': ['cube3_cluster0'], 'cube2_cluster3': ['cube3_cluster1'], 'cube2_cluster6': ['cube3_cluster0'], 'cube2_cluster7': ['cube3_cluster2'], 'cube3_cluster0': ['cube4_cluster0'], 'cube3_cluster3': ['cube4_cluster2'], 'cube3_cluster4': ['cube4_cluster6'], 'cube3_cluster5': ['cube4_cluster8'], 'cube3_cluster6': ['cube4_cluster9'], 'cube4_cluster0': ['cube5_cluster1'], 'cube4_cluster1': ['cube5_cluster2'], 'cube4_cluster3': ['cube5_cluster6'], 'cube4_cluster4': ['cube5_cluster7'], 'cube4_cluster5': ['cube5_cluster8'], 'cube4_cluster7': ['cube5_cluster9'], 'cube5_cluster0': ['cube6_cluster0'], 'cube5_cluster1': ['cube6_cluster0'], 'cube5_cluster4': ['cube6_cluster2'], 'cube5_cluster5': ['cube6_cluster0'], 'cube5_cluster10': ['cube6_cluster3'], 'cube5_cluster11': ['cube6_cluster0'], 'cube6_cluster0': ['cube7_cluster0', 'cube7_cluster1'], 'cube6_cluster1': ['cube7_cluster3'], 'cube6_cluster4': ['cube7_cluster4'], 'cube6_cluster5': ['cube7_cluster5'], 'cube6_cluster6': ['cube7_cluster6']}