# Simplicial Complex Analysis

<span style='color:Red'>TODO: Get a system to determine ecological state of a shape</span> <br>
<span style='color:Red'> Currently using the largest number of nodes in each shape. </span> <br> 
Written by Frederick Miller, Casey McKean, and Wako Bungula. <br> 
The kepler mapper object gives an output that is not easily navigatible. To resolve this, we wish to create shapes that are easier to navigate and understand, and reveal the data inside of them. <br>
We generate all the shapes in the simplicial complex, condense 1-simplices where possible, and obtain summary statistics on the shapes and the nodes within the shapes.

In [1]:
import numpy as np
import pandas as pd 
import queue
import animation
import json
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', None)
import pickle
print("Imports Done")

Imports Done

# File paths, `.p`, and `.json` import

From the `kmapper_demo` file, I added one extra code block to place the resulting simplicial complices in a `.json` file, which is a way to store dictionaries in long term storage. Additionally, it stores the dictionary of dataframes in a `.p` file, which is similar. The code below only needs to have the file paths changed, and then it will read the simplicial complices generated from kepler mapper. <br>
Here, we also import the actual data set, with data interpolated for the specific pool. <br>
Lastly, a list of the 11 continuous variables (the interpolated versions) is created.

In [2]:
jsonFilePath = r"C:\Users\forre\Desktop\REU\TDA\Data\TDAOutputs\TDA1PCA10Cubes30perc_complices.json"
jsonFile = open(jsonFilePath, "r")
jsonData = json.load(jsonFile) 
jsonFile.close()

dataFilePath = r"C:\Users\forre\Desktop\REU\TDA\Data\TDAOutputs\TDA1PCA10Cubes30perc_dfs.p"
df_dict = pickle.load(open(dataFilePath, "rb"))

variables = ["PredictedWDP", "PredictedSECCHI", "PredictedTEMP", "PredictedDO", 
           "PredictedTURB", "PredictedVEL", "PredictedTP", #"PREDICTED_COND",
           "PredictedTN", "PredictedSS", "PredictedCHLcal"]

variables = ["PREDICTED_WDP", "PREDICTED_SECCHI", "PREDICTED_TEMP", "PREDICTED_DO", 
           "PREDICTED_TURB", "PREDICTED_VEL", "PREDICTED_TP", #"PREDICTED_COND",
           "PREDICTED_TN", "PREDICTED_SS", "PREDICTED_CHLcal"]



print("Json file imported")

print(len(jsonData.keys()))

Json file imported
25

# Functions
See the `docstring`'s for what each function does and how it works.

In [43]:
def getSubdf(scomplex, shape, df):
    """
    Returns the part of the data frame from the particular shape in the simplicial complex.
    params:
    scomplex: the entire simplicial complex
    shape: the particular shape being inspected (within the simplicial complex)
    df: the entire data frame
    
    Description:
    1. Get all the nodes from the particular simplicial complex. 
    2. Generate the indices we care about from the particular shape. To do this, we read each node and append it's 
    indices to a list. Then, we convert the list to a set and then back to a list to eliminate duplicates.
    3. Return the dataframe with only those indices.
    """
    nodes = scomplex.get('nodes')
    indices = []
    npShape = np.array(shape).flatten()
    for node in npShape:
        indices.append(nodes.get(node))
    indices = list(set([item for sublist in indices for item in sublist]))
    subdf = df.loc[indices]
    return subdf

def shapeDataSummary(scomplex, shape, df, variables, verbose = False):
    """
    Generates summary statistics of the given variables for a given shape in the simplicial.
    params:
    scomplex: the entire simplicial complex
    shape: the particular shape being inspected (within the simplicial complex) at this function call.
    df: the entire dataframe
    variables: the variables of interest
    verbose: Determines if the function will print out extra information. False by default
    
    Description:
    1. Create an empty result dataframe to store the summary statistics.
    2. Get the sub dataframe (see getSubdf) for the particular shape
    3. For each variable we are analzying, generate summary statistics from the sub dataframe and place them
    inside the result dataframe.
    4. Return the result dataframe
    
    NOTE: this only creates summaries for one particular shape. In executing this method, it is done for each shape 
    outside of the function.
    
    """
    result = pd.DataFrame()
    if verbose == True:
        print("Obtaining sub dataframe for: ", shape)
        print("The number of nodes in this shape is: ", len(shape))
    subdf = getSubdf(scomplex, shape, df)
    if verbose == True:
        print("The number of datapoints in this shape is: ", subdf.shape[0])
    for var in variables:
        result[var] = subdf[var].describe()
    return result
    
    

def adjacent(v, scomplex):
    """
    Determines the nodes adjacent to a given vertex
    
    params:
    v: vertex
    scomlex: the entire simplicial complex
    
    Description:
    Determines the nodes that are adjacent to a given vertex.
    """
    
    simplices = scomplex.get('simplices')
    edges = [item for item in simplices if len(item) == 2]
    result = []
    for edge in edges:
        if v in edge:
            for item in edge:
                if item != v:
                    result.append(item)
    return result

def bfs(node, scomplex):
    """
    Conducts a breadth first search to obtain the entire shape from a given node
    params:
    node: the start node
    scomplex: the entire simplicial complex
    
    Description:
    Preforms a breadth first search to obtain the entire shape for a given start node.
    """
    Q = queue.Queue()
    result = []
    result.append(node)
    Q.put(node)
    while not Q.empty():
        v = Q.get()
        adjacentEdges = adjacent(v, scomplex)
        for edge in adjacentEdges:
            if edge not in result:
                result.append(edge)
                Q.put(edge)
    return result


        
    
def getShapes(scomplex):
    """
    Gets all of the shapes from a given simplicial complex.
    
    params:
    scomplex: the entire simplicial complex
    
    Description:
    1. Obtain all the nodes for the entire complex
    2. For each node, preform a breadth first search to obtain everything in that particular shape. 
    If this entire shape has not already been discovered, add it to the set of results. 
    The result item is a set as the order of the shapes does not matter. The resulting shape is a frozenset
    which means items cannot be added or removed once created, and is needed to allow the set object to have other sets within it.
    3. Convert each shape to a list and the result to a list for easier navigation outside of the function.
    4. Return the result
    
    """
    
    nodes = list(scomplex.get('nodes').keys())
    result = set()
    for node in nodes: # currently does more computations than necessary due to going through every node without considering it is already in a shape
        bfsResult = frozenset(bfs(node, scomplex))
        result.add(bfsResult)
    result = [list(x) for x in result]
    # Sort the list depending on what is decided: nodes or indices. Currently doing it by number of nodes
    result.sort(key = len, reverse = True)
    
    
    
    return result

def nodeDataSummary(node, scomplex, variables,df):
    """
    Returns a data summary of a particular node
    params:
    node: node in question
    scomplex: The entire simplicial complex
    variables: The variables to obtain summaries
    df: the entire dataframe 
    
    description:
    1. Creates a result dataframe
    2. Get all the indices from the node from the simplicial complex
    3. Generate summaries for each variable
    4. Return the result
    """
    result = pd.DataFrame()
    if isinstance(node, list):
        print("Node is a list and thus cannot get summary information: ", node)
        indices = scomplex.get('nodes').get(node[0])
        subdf = df.loc[indices]
        for var in variables:
            result[var] = subdf[var].describe()
        return result
    
        
    indices = scomplex.get('nodes').get(node)
    subdf = df.loc[indices]
    for var in variables:
        result[var] = subdf[var].describe()
    return result
    
    
def condenseShape(shape, scomplex):
    """
    
    params:
    shape: a shape of two nodes. must be 2
    scomplex: the entire simplicial complex
    
    description:
    gets the two nodes a and b
    gets the indices for a and b (what is inside the nodes)
    if a \subseteq b, return b
    elif b \subseteq a, return a 
    else return shape 
    
    """
    nodes = scomplex.get('nodes')
    a = shape[0]
    b = shape[1]
    aIndices = set(nodes.get(a))
    bIndices = set(nodes.get(b))
    
    if aIndices.issubset(bIndices):
        return b
    elif bIndices.issubset(aIndices):
        return a
    else:
        return shape

def clean_getShapes(scomplex):
    """
    Condenses 1-simplices down to 0-simplices when each node 
    is a subset of the other 
    
    params:
    scomplex: the entire simplicial complex
    
    Description:
    1. Get all the shapes from the original getShapes function
    2. For shapes that of length 2, if one is a subset of the other, return the larger of the two
        Otherwise, do nothing
    3. return the clean Shapes list 
    
    """
    shapes = getShapes(scomplex)
    cleanShapes = []
    for shape in shapes:
        if len(shape) == 2:
            shape = condenseShape(shape, scomplex)
            cleanShapes.append([shape])
        else:
            cleanShapes.append(shape)
    return cleanShapes


def getBoxplots(subdf, shape, key,filePath):
    """
    Generates box plots for 10 of the 11 continuous variables
    NOTE: CONDUCTIVITY IS NOT INCLUDED
    
    params:
    subdf: the sub dataframe of the particular shape
    shape: the shape in question
    key: what strata year season combo we are looking at 
    filePath: the output file path for all the box plots 
    
    description:
    clears the current plot 
    generates the sub dataframes for the respective variables.
    the reason they are grouped is based upon the numerical outputs for making the boxplots readable
    create a box plot, and then save it based upon the file path
    clear the plot
    repeat for the second set of variables
    """
    plt.clf()
    varDf1 = subdf[["PREDICTED_SS","PREDICTED_TURB","PREDICTED_CHLcal"]]
    varDf2 = subdf[["PREDICTED_TP","PREDICTED_TN","PREDICTED_TEMP","PREDICTED_DO","PREDICTED_VEL","PREDICTED_WDP",
                  "PREDICTED_SECCHI"]]
    plot1 = varDf1.boxplot()
    plt.savefig(filePath + "\\" + key +"_" + str(shape)  + "_SS_TURB_CHLcal"  + ".png")
    plt.clf()
    plot2 = varDf2.boxplot(rot = 45)
    plt.savefig(filePath + "\\" + key +"_" + str(shape)  + "_" + "TP_TN_TEMP_etc" + ".png")
    return plot1, plot2

def determineOverlap(scomplex, shapes, verbose = True):
    """
    Determines the overlap within a shape. 
    
    For each node, find it's neighbors, and generate the intersection, and saving the result without
    duplicates through utlizing the set functionality of python.
    
    params:
    scomplex: the entire simplicial complex in question
    shapes: all the shapes
    verbose: see prinout as the code works
    """
    
    shape = shapes[0] # chosen arbitrarily 
    
    result = set()
    if verbose:
        print("Shape: ", shape)
    nodes = scomplex.get('nodes')
    for node in shape:
        # currently, this displays a lot of repeats. 
        A = set(nodes.get(node))
        if verbose:
            print("Node: " , node  , " | Indices: ",A)
        B = adjacent(node, scomplex)
        if verbose:
            print("Adjacent nodes: ",B)
        for b in B:
            bSet = set(nodes.get(b))
            name = str(node) + " -> " + str(b) +": "
            intersection = set(A.intersection(bSet))
            intersection.add(name)
            intersection = frozenset(intersection)
            result.add(intersection)
            if verbose:
                print("Node: ", b, " | Indices: ", bSet)
                print("Overlap is: ", A.intersection(bSet))
    return result
print("Functions loaded")

Functions loaded

# Generating Summary Statistics on the entire simplicial complex
For each `mapper` output from `kepler-mapper`, we can generate the summary statistics for each of the continuous variables. This is done by first obtaining a list of the keys from the `.json` file, and then iterating through each complex, generating the shape and obtaining data summaries on each shape.

In [4]:
allComplices = list(jsonData.keys())
for key in allComplices: # remove indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    shapes = clean_getShapes(scomplex)
    for shape in shapes:
        summaries = shapeDataSummary(scomplex, shape, df_dict.get(key), variables, verbose = False)
        if summaries.loc['count'][0] > 5 and len(shape)  > 2: # at least 6 datapoints and 3 nodes to see info
            print("The shape is: ",shape)
            print("The number of nodes in the shape is: ", len(shape))
            display(summaries) # Uncomment to see summaries

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
The shape is:  ['cube6_cluster1', 'cube0_cluster0', 'cube2_cluster0', 'cube5_cluster0', 'cube8_cluster1', 'cube1_cluster0', 'cube4_cluster0', 'cube7_cluster1', 'cube5_cluster2', 'cube3_cluster0']
The number of nodes in the shape is:  10

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000
mean,5.807438,39.445314,28.055503,7.612425,31.490741,0.311708,0.173857,3.620438,46.316052,25.681036
std,2.689415,10.622191,1.600216,1.281878,13.943474,0.248585,0.064355,0.637487,21.792598,10.487500
min,0.340000,14.000000,25.800000,5.400000,11.000000,0.000000,0.033480,2.432000,12.700000,9.751950
25%,4.000000,32.500000,26.675000,6.875000,22.000000,0.019134,0.147750,3.282750,31.700000,18.313660
50%,5.350000,40.000000,27.900000,7.500000,27.500000,0.332943,0.172609,3.664633,41.850000,23.866420
75%,7.600000,46.000000,29.200000,8.025000,36.500000,0.493413,0.206250,4.039438,59.900000,29.584580
max,12.200000,68.000000,32.900000,13.200000,88.000000,0.971381,0.380512,5.372994,108.300000,60.993300

Current Simplical Complex:  ['Stratum 2 SUMMER 93-00: ']
The shape is:  ['cube6_cluster1', 'cube0_cluster0', 'cube2_cluster0', 'cube8_cluster0', 'cube5_cluster0', 'cube8_cluster1', 'cube7_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube9_cluster1', 'cube4_cluster2', 'cube3_cluster0', 'cube2_cluster3']
The number of nodes in the shape is:  13

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000
mean,3.770625,35.100000,27.993179,7.773181,37.765000,0.544608,0.185213,3.636574,57.774063,26.393068
std,1.969209,10.464445,1.389663,1.491258,18.169783,0.264792,0.067865,0.656414,31.614296,12.546677
min,0.550000,12.000000,25.581729,4.400000,11.000000,0.000000,0.041000,2.255000,14.300000,5.911680
25%,2.100000,26.750000,26.800000,6.800000,25.000000,0.377500,0.153345,3.259775,33.900000,15.399952
50%,3.500000,35.000000,27.800000,7.600000,34.000000,0.520000,0.176550,3.612500,48.923178,24.135400
75%,5.000000,43.000000,29.200000,8.100000,46.000000,0.700000,0.211986,4.128250,69.950000,34.470165
max,11.300000,63.000000,31.600000,14.300000,99.000000,1.700000,0.723927,5.849319,151.400000,65.769350

Current Simplical Complex:  ['Stratum 3 SUMMER 93-00: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster15', 'cube1_cluster0', 'cube2_cluster10', 'cube2_cluster18', 'cube2_cluster1']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000
mean,0.950344,24.215653,29.115963,9.329880,51.472049,0.035760,0.279727,2.567889,54.283605,72.462298
std,0.744180,8.567753,2.752198,4.664146,22.087829,0.131865,0.183523,1.126765,21.921755,36.496744
min,0.320000,11.000000,24.100000,3.300000,10.000000,0.000000,0.036000,0.560000,9.900000,9.299840
25%,0.600000,19.000000,27.200000,6.500000,34.000000,0.000000,0.171000,1.793000,38.700000,42.326220
50%,0.760000,22.000000,28.700000,8.200000,52.000000,0.000000,0.271561,2.213000,54.800000,68.043180
75%,0.970000,26.000000,30.500000,10.800000,68.000000,0.000000,0.364000,3.238000,68.600000,105.354660
max,4.900000,51.000000,39.500000,25.000000,101.000000,0.948848,1.613000,8.370005,112.700000,148.505460

Current Simplical Complex:  ['Stratum 4 SUMMER 93-00: ']
The shape is:  ['cube3_cluster5', 'cube3_cluster4', 'cube1_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,0.883333,18.393939,30.200000,9.487879,73.242424,0.000303,0.693154,2.056373,73.342424,87.074066
std,0.519854,3.904640,2.516073,5.039268,16.355485,0.001741,0.383099,0.663917,17.357780,14.711485
min,0.300000,11.000000,26.400000,2.200000,31.000000,0.000000,0.277000,1.290000,36.600000,59.440470
25%,0.590000,15.000000,28.300000,6.800000,65.000000,0.000000,0.417589,1.531000,61.200000,77.081690
50%,0.750000,18.000000,29.400000,7.900000,78.000000,0.000000,0.670000,1.969333,72.400000,84.958260
75%,0.850000,20.000000,32.100000,11.600000,85.000000,0.000000,0.715929,2.302000,88.900000,98.080120
max,2.300000,27.000000,34.500000,25.000000,101.000000,0.010000,1.874142,3.965000,100.700000,118.098140

The shape is:  ['cube6_cluster1', 'cube5_cluster0', 'cube4_cluster6']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,0.470000,11.857143,30.042857,11.771429,143.142857,0.008571,0.644323,1.924376,143.759134,161.737229
std,0.118603,1.951800,1.263404,2.976415,10.945754,0.006901,0.230879,0.794909,7.464677,8.991427
min,0.350000,10.000000,28.100000,5.400000,128.000000,0.000000,0.329618,0.872723,132.600000,148.985950
25%,0.380000,10.000000,29.600000,11.800000,136.000000,0.005000,0.459816,1.415669,139.356969,155.664325
50%,0.400000,12.000000,29.600000,12.300000,144.000000,0.010000,0.767838,2.026682,142.800000,164.067560
75%,0.575000,13.000000,30.650000,13.450000,149.000000,0.010000,0.793333,2.359944,149.500000,167.280650
max,0.630000,15.000000,32.100000,14.200000,160.000000,0.020000,0.906506,3.020000,153.200000,173.217140

The shape is:  ['cube4_cluster3', 'cube3_cluster6', 'cube5_cluster6']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,0.561667,12.666667,29.666667,16.183333,103.333333,0.015000,0.731152,2.175667,112.950000,155.186351
std,0.274257,1.861899,1.102119,7.301073,6.683313,0.022583,0.300707,0.963430,3.850065,9.346303
min,0.330000,9.000000,28.300000,6.800000,97.000000,0.000000,0.309983,0.817835,107.600000,141.052850
25%,0.340000,13.000000,28.850000,13.125000,98.250000,0.002500,0.514997,1.450323,110.375000,150.099012
50%,0.470000,13.000000,29.650000,13.650000,101.500000,0.010000,0.797273,2.477946,113.400000,156.919050
75%,0.735000,13.750000,30.525000,22.200000,107.000000,0.010000,0.934675,2.919357,115.300000,159.853487
max,0.980000,14.000000,31.000000,25.000000,114.000000,0.060000,1.081000,3.106000,118.000000,167.569858

Current Simplical Complex:  ['Stratum 5 SUMMER 93-00: ']
The shape is:  ['cube7_cluster3', 'cube2_cluster0', 'cube5_cluster0', 'cube6_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube7_cluster1', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,2.193158,33.052084,28.497368,8.714474,33.135869,0.011711,0.157153,3.344466,36.740737,34.985070
std,1.166738,8.166568,2.114078,3.034456,10.945652,0.045325,0.076908,0.556751,13.311718,15.225210
min,0.600000,19.000000,25.400000,4.000000,14.000000,0.000000,0.028000,2.097000,12.400000,9.266250
25%,1.247500,27.750000,26.700000,7.175000,26.500000,0.000000,0.137500,3.060156,26.875000,25.718330
50%,2.000000,32.000000,27.650000,8.100000,32.000000,0.000000,0.154250,3.271625,35.250000,31.287540
75%,3.000000,37.000000,30.500000,9.950000,39.000000,0.000000,0.176250,3.615125,44.125000,39.980025
max,7.000000,53.000000,33.500000,25.000000,68.000000,0.340000,0.640000,4.691000,71.049995,76.638240

Current Simplical Complex:  ['Stratum 1 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube5_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,6.248455,44.239706,28.060000,8.080000,24.780000,0.275793,0.200605,3.719023,37.423000,32.525356
std,2.951668,9.850165,1.582927,1.232145,9.116064,0.225755,0.068732,0.827890,15.503879,12.390508
min,1.000000,21.000000,25.300000,5.400000,7.000000,0.000000,0.050028,1.656369,6.500000,12.261240
25%,4.175000,37.750000,26.800000,7.475000,18.000000,0.078590,0.159500,3.319000,25.425000,23.149375
50%,6.000000,44.000000,27.750000,7.900000,24.000000,0.242579,0.177450,3.698082,34.500000,31.029300
75%,8.250000,50.000000,29.300000,8.725000,31.000000,0.451573,0.222250,4.352265,46.850000,38.720465
max,13.000000,75.000000,31.500000,13.200000,45.000000,0.971381,0.480270,5.758000,80.200000,61.636230

The shape is:  ['cube6_cluster0', 'cube8_cluster0', 'cube7_cluster1']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,5.415783,21.312333,28.480000,6.600000,63.700000,0.401310,0.228682,3.979537,94.020000,12.933602
std,3.490749,3.193622,1.615756,0.661648,11.585911,0.229256,0.025222,0.552990,9.933199,2.059359
min,0.340000,14.000000,26.300000,5.400000,51.000000,0.000000,0.195702,3.322286,77.800000,9.751950
25%,3.529457,20.342501,27.275000,6.325000,56.250000,0.314449,0.204922,3.474136,86.600000,12.129260
50%,4.000000,21.000000,28.250000,6.550000,61.000000,0.462964,0.232558,4.001772,96.000000,12.343610
75%,7.975000,23.000000,29.400000,6.700000,70.750000,0.574217,0.241750,4.327500,100.700000,14.046267
max,11.000000,26.000000,31.000000,7.900000,88.000000,0.641584,0.273000,4.830000,108.300000,17.050240

Current Simplical Complex:  ['Stratum 2 SUMMER 98-04: ']
The shape is:  ['cube2_cluster0', 'cube0_cluster1', 'cube5_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000
mean,3.636066,38.286885,28.059836,8.224180,33.490164,0.491611,0.189916,3.916744,52.061475,33.714166
std,2.265481,13.177159,1.449828,1.577422,19.713413,0.272844,0.062361,0.733997,32.591371,15.946011
min,0.300000,12.000000,25.400000,4.400000,6.000000,0.000000,0.002000,1.874175,11.500000,5.955980
25%,2.000000,26.000000,26.800000,7.500000,19.000000,0.320000,0.152940,3.392692,29.850000,22.106680
50%,3.200000,38.500000,28.200000,8.200000,28.000000,0.490000,0.174165,3.884106,40.750000,33.505280
75%,4.825000,45.000000,29.200000,8.600000,41.000000,0.620000,0.215000,4.479119,62.225000,41.507005
max,18.400000,80.000000,31.600000,18.200000,99.000000,1.700000,0.723927,5.426000,151.400000,68.848800

Current Simplical Complex:  ['Stratum 3 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube0_cluster2', 'cube0_cluster1', 'cube1_cluster6', 'cube1_cluster0', 'cube1_cluster7', 'cube2_cluster1']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000
mean,0.909731,22.830505,28.786318,8.310614,59.274326,0.037945,0.349227,2.647885,59.982014,74.590876
std,0.749517,8.982122,2.155192,3.436111,28.765338,0.138655,0.258840,1.024042,28.100218,42.152079
min,0.300000,11.000000,23.400000,2.800000,10.000000,0.000000,0.002000,1.055000,9.900000,9.299840
25%,0.522500,17.000000,27.225000,6.050000,34.141278,0.000000,0.239116,1.992872,38.000000,42.336160
50%,0.745000,20.000000,28.700000,7.800000,58.500000,0.000000,0.319777,2.334811,58.650000,63.230460
75%,0.950000,26.000000,29.900000,9.400000,84.750000,0.000000,0.386613,3.225000,79.100000,110.273562
max,4.900000,51.000000,35.500000,25.000000,116.000000,0.948848,2.527667,6.398813,130.200000,167.211530

Current Simplical Complex:  ['Stratum 4 SUMMER 98-04: ']
The shape is:  ['cube3_cluster0', 'cube1_cluster0', 'cube0_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,0.752000,19.650000,30.080000,9.565000,65.725000,0.000250,0.716168,1.695329,63.812500,89.584307
std,0.464698,3.613011,2.768523,4.477554,18.989859,0.001581,0.337686,0.688453,18.851201,14.029394
min,0.300000,11.000000,26.300000,4.600000,31.000000,0.000000,0.026000,0.024000,34.500000,65.056840
25%,0.507500,18.000000,27.075000,6.875000,47.250000,0.000000,0.408442,1.402048,46.375000,78.631705
50%,0.615000,20.000000,30.200000,8.200000,71.500000,0.000000,0.710500,1.803091,63.700000,87.346320
75%,0.770000,21.250000,32.250000,9.725000,82.000000,0.000000,1.003897,2.108997,77.475000,99.253425
max,2.300000,27.000000,34.400000,25.000000,94.000000,0.010000,1.307046,2.885041,99.300000,119.127730

Current Simplical Complex:  ['Stratum 5 SUMMER 98-04: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube0_cluster1', 'cube5_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  7

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,2.115584,32.239910,28.185714,8.576623,31.467532,0.021688,0.162828,3.376298,35.283117,36.638372
std,1.203185,5.813152,2.348500,2.222072,9.970462,0.052551,0.027163,0.620355,13.013054,17.355426
min,0.360000,19.000000,24.700000,4.000000,15.000000,0.000000,0.036000,2.221000,16.700000,8.132950
25%,1.000000,28.000000,26.100000,7.300000,25.000000,0.000000,0.150461,2.972483,26.100000,25.574660
50%,2.100000,33.000000,27.500000,7.800000,29.000000,0.000000,0.166500,3.314500,31.100000,33.110440
75%,3.000000,35.000000,30.600000,9.500000,36.000000,0.010000,0.179000,3.708000,41.500000,51.687420
max,7.000000,48.000000,31.600000,14.900000,68.000000,0.340000,0.220000,4.965000,78.000000,74.026250

Current Simplical Complex:  ['Stratum 1 SUMMER 01-13: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube3_cluster1', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000
mean,6.236978,41.737778,28.984889,7.906667,31.248889,0.275929,0.235926,3.276117,45.081778,34.952097
std,3.536730,14.433581,1.802885,1.903709,25.535695,0.279318,0.129205,1.031044,35.353000,21.700931
min,0.450000,12.000000,25.300000,3.700000,7.000000,0.000000,0.050028,1.098997,6.500000,9.164280
25%,3.500000,32.000000,27.700000,6.500000,15.000000,0.000000,0.170000,2.491000,20.600000,23.082820
50%,6.000000,43.000000,29.200000,7.900000,22.000000,0.214855,0.200444,3.287600,31.700000,29.545520
75%,8.200000,50.000000,30.100000,9.100000,35.000000,0.473235,0.257074,4.084857,57.600000,38.821380
max,19.300000,75.000000,33.400000,12.300000,128.000000,1.050000,1.228158,5.940472,166.800000,138.525820

The shape is:  ['cube4_cluster1', 'cube5_cluster0', 'cube6_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,10.00000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,7.09000,16.70000,27.220000,5.370000,131.600000,0.413261,0.293474,4.011093,183.000000,11.584294
std,1.97228,2.58414,1.301964,0.676675,8.934328,0.254628,0.078758,0.404630,14.707066,2.558159
min,3.40000,13.00000,25.600000,4.400000,120.000000,0.000000,0.192748,3.486090,159.200000,9.303560
25%,5.87500,14.25000,26.100000,5.000000,128.000000,0.268029,0.229881,3.744103,175.975000,9.960100
50%,7.15000,17.00000,27.150000,5.250000,130.000000,0.424766,0.288151,3.955636,184.550000,10.967710
75%,8.32500,19.00000,28.175000,6.075000,138.000000,0.596561,0.357000,4.160950,192.775000,11.497220
max,9.90000,20.00000,28.900000,6.100000,148.000000,0.745295,0.421000,4.807087,205.400000,17.381800

Current Simplical Complex:  ['Stratum 2 SUMMER 01-13: ']
Current Simplical Complex:  ['Stratum 3 SUMMER 01-13: ']
The shape is:  ['cube1_cluster16', 'cube0_cluster0', 'cube2_cluster0', 'cube1_cluster14', 'cube2_cluster6', 'cube1_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  7

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000
mean,1.018832,23.848797,30.469072,9.054334,51.725086,0.039278,0.389884,2.524294,52.737113,66.890048
std,0.773418,9.272010,3.130584,3.808940,26.072446,0.126496,0.285081,0.935908,26.616907,44.212644
min,0.180000,10.000000,23.200000,0.400000,9.000000,0.000000,0.002000,0.919000,8.800000,7.214360
25%,0.500000,17.000000,28.400000,6.200000,31.000000,0.000000,0.225330,1.836000,33.000000,30.807055
50%,0.780000,21.000000,30.000000,8.369485,48.000000,0.000000,0.323000,2.325333,48.300000,59.376120
75%,1.100000,27.000000,32.350000,11.550000,70.500000,0.000000,0.464500,2.931138,70.600000,91.302990
max,3.900000,67.000000,38.600000,21.800000,116.000000,1.000000,2.904651,6.531588,130.200000,175.992050

Current Simplical Complex:  ['Stratum 4 SUMMER 01-13: ']
The shape is:  ['cube3_cluster2', 'cube0_cluster0', 'cube2_cluster0', 'cube0_cluster1', 'cube1_cluster0', 'cube1_cluster1', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
mean,1.110101,28.898990,30.000000,8.013131,41.080808,0.001515,0.803153,1.670896,40.044444,61.984517
std,0.909488,12.781919,2.915301,2.406057,23.413618,0.012402,0.537995,0.624384,21.998619,34.527586
min,0.250000,11.000000,24.000000,3.700000,6.000000,0.000000,0.017000,0.024000,6.000000,10.027860
25%,0.515000,20.000000,27.750000,6.200000,22.000000,0.000000,0.358496,1.130610,21.750000,29.373350
50%,0.650000,27.000000,30.000000,7.500000,36.000000,0.000000,0.535000,1.691000,38.100000,68.873860
75%,1.450000,36.000000,32.650000,9.300000,63.500000,0.000000,1.121904,2.258098,58.400000,86.098970
max,3.300000,70.000000,35.500000,14.500000,94.000000,0.120000,2.168000,2.879706,94.000000,140.556380

Current Simplical Complex:  ['Stratum 5 SUMMER 01-13: ']
The shape is:  ['cube2_cluster2', 'cube1_cluster0', 'cube0_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000
mean,2.501243,34.372781,29.785799,11.010059,23.674556,0.012426,0.174256,2.827293,26.992899,53.186539
std,1.575602,7.887420,2.544001,3.608895,8.114912,0.045820,0.046326,0.828452,9.295734,23.185295
min,0.400000,18.000000,24.700000,5.100000,10.000000,0.000000,0.036000,1.289000,11.100000,16.452220
25%,1.200000,30.000000,27.800000,8.400000,19.000000,0.000000,0.143000,2.280000,20.400000,34.931080
50%,2.200000,34.000000,30.100000,10.300000,22.000000,0.000000,0.167000,2.811000,24.700000,49.957320
75%,3.600000,38.000000,31.600000,13.300000,27.000000,0.000000,0.192905,3.329500,32.000000,69.157410
max,9.400000,58.000000,34.900000,20.500000,53.000000,0.380000,0.335000,4.965000,56.100000,126.426440

Current Simplical Complex:  ['Stratum 1 SUMMER 10-16: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube4_cluster1', 'cube1_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  5

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,6.280000,30.316667,28.701667,6.611667,51.108333,0.375711,0.241029,3.340142,74.576917,23.046890
std,3.411069,11.978961,2.051070,1.351201,31.503713,0.331638,0.097719,1.014256,39.039223,7.859109
min,0.700000,12.000000,24.800000,3.700000,8.000000,0.000000,0.140535,1.056507,11.400000,9.549010
25%,3.600000,21.750000,27.800000,5.675000,33.000000,0.000000,0.195870,2.693934,43.175000,16.729913
50%,6.100000,28.000000,28.600000,6.600000,46.000000,0.404451,0.226832,3.432168,74.990000,22.853470
75%,7.925000,35.250000,30.200000,7.300000,67.000000,0.655683,0.253341,4.133300,106.062500,29.037960
max,19.300000,62.000000,32.800000,10.200000,128.000000,1.022370,0.928245,5.940472,156.350000,38.821380

Current Simplical Complex:  ['Stratum 2 SUMMER 10-16: ']
The shape is:  ['cube2_cluster0', 'cube4_cluster1', 'cube3_cluster1', 'cube0_cluster1', 'cube1_cluster0', 'cube4_cluster0', 'cube5_cluster2', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000
mean,4.014885,28.973282,28.829008,6.662595,56.511450,0.698494,0.238551,3.435145,81.519606,23.332080
std,2.233446,10.333299,1.979918,1.435421,34.018221,0.341312,0.100529,1.016961,40.431537,9.185101
min,0.300000,9.000000,25.200000,4.100000,10.000000,0.000000,0.145235,0.990000,14.500000,2.329570
25%,2.400000,23.000000,27.900000,5.700000,35.000000,0.480000,0.196109,2.858469,55.025000,16.711955
50%,3.800000,29.000000,28.800000,6.400000,47.000000,0.765000,0.223578,3.515385,81.990000,21.533790
75%,5.400000,33.000000,30.000000,7.100000,78.000000,0.960000,0.262526,4.227563,111.350000,30.423270
max,12.000000,60.000000,35.200000,12.000000,172.000000,1.360000,1.673310,6.523909,193.580000,43.965610

The shape is:  ['cube6_cluster0', 'cube7_cluster2', 'cube7_cluster0', 'cube5_cluster0']
The number of nodes in the shape is:  4

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,5.821053,11.736842,28.247368,5.868421,175.157895,0.863684,0.281485,3.839048,241.412105,17.930186
std,2.387835,1.939132,0.676895,0.331751,20.958327,0.184066,0.034280,0.339757,23.200092,2.555011
min,0.700000,8.000000,27.500000,4.800000,152.000000,0.350000,0.214280,3.091000,199.510000,11.251450
25%,4.350000,10.000000,27.600000,5.700000,158.000000,0.740000,0.253390,3.597762,223.285000,17.397865
50%,6.300000,12.000000,27.800000,5.900000,170.000000,0.920000,0.280000,3.932013,250.390000,19.003620
75%,7.700000,13.000000,29.000000,6.050000,185.000000,0.975000,0.293500,4.107243,258.990000,19.468515
max,8.600000,15.000000,29.300000,6.300000,220.000000,1.170000,0.346000,4.299000,276.870000,20.465700

Current Simplical Complex:  ['Stratum 3 SUMMER 10-16: ']
Current Simplical Complex:  ['Stratum 4 SUMMER 10-16: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube3_cluster1', 'cube0_cluster1', 'cube1_cluster0', 'cube2_cluster1']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,1.591633,35.795918,29.553061,7.365306,23.224490,0.003061,0.369782,1.372517,23.421079,35.650223
std,1.030834,12.622697,3.437362,2.206576,10.188362,0.017584,0.108070,0.329019,10.479480,21.083073
min,0.460000,16.000000,24.000000,3.700000,6.000000,0.000000,0.210000,0.963000,6.000000,10.027860
25%,0.780000,27.000000,26.800000,5.800000,16.000000,0.000000,0.281449,1.107000,15.900000,19.435850
50%,1.000000,35.000000,29.500000,6.900000,22.000000,0.000000,0.334286,1.297983,21.900000,29.052150
75%,2.900000,40.000000,33.000000,8.400000,29.000000,0.000000,0.432000,1.568000,31.620000,50.266810
max,3.300000,70.000000,35.500000,13.400000,50.000000,0.120000,0.547000,2.218000,42.500000,91.549870

Current Simplical Complex:  ['Stratum 5 SUMMER 10-16: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube4_cluster1', 'cube1_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  5

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.0,95.000000,95.000000,95.000000,95.000000
mean,2.423158,29.968421,30.395789,11.118947,24.526316,0.0,0.192469,2.761972,26.835579,58.019429
std,1.617232,4.585947,2.274742,3.828263,7.298852,0.0,0.058694,0.742897,7.645653,22.779512
min,0.260000,18.000000,26.000000,5.100000,13.000000,0.0,0.117000,1.289000,15.040000,17.851060
25%,1.225000,27.000000,29.000000,8.800000,20.000000,0.0,0.149450,2.321500,21.500000,42.018255
50%,2.000000,30.000000,30.500000,10.600000,22.000000,0.0,0.180000,2.759659,24.750000,51.370920
75%,3.050000,34.000000,31.850000,13.800000,28.000000,0.0,0.209124,3.271713,29.960000,72.089495
max,9.400000,42.000000,34.900000,19.600000,48.000000,0.0,0.444069,4.398842,53.100000,119.462400

Current Simplical Complex:  ['Stratum 1 SUMMER 14-20: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube4_cluster4', 'cube3_cluster1', 'cube2_cluster2', 'cube1_cluster0']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,106.000000,106.000000,106.000000,106.000000,106.00000,106.000000,106.000000,106.000000,106.000000,106.000000
mean,6.149811,28.399878,27.166038,7.578302,54.90566,0.499686,0.229527,3.181405,81.943679,32.555738
std,2.528473,6.854749,1.482462,1.163738,24.46320,0.317300,0.050133,0.678528,26.904529,15.833449
min,0.680000,13.000000,24.800000,5.100000,15.00000,0.000000,0.109000,1.056507,22.010000,9.653400
25%,4.325000,25.000000,25.600000,6.700000,36.25000,0.227204,0.195160,2.749118,64.720000,19.115893
50%,6.200000,28.000000,27.100000,7.300000,51.50000,0.560000,0.230500,3.165176,82.175000,25.920300
75%,7.625000,32.000000,28.475000,8.300000,67.00000,0.754384,0.253000,3.597841,103.722500,47.306130
max,12.300000,48.000000,29.700000,11.000000,128.00000,1.022370,0.494508,4.628146,137.350000,72.416960

Current Simplical Complex:  ['Stratum 2 SUMMER 14-20: ']
The shape is:  ['cube5_cluster1', 'cube0_cluster0', 'cube2_cluster0', 'cube7_cluster2', 'cube6_cluster0', 'cube7_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  9

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000,280.000000
mean,4.078179,25.946429,27.270714,7.497500,71.285714,0.736567,0.247037,3.251966,102.589179,35.748010
std,1.974336,7.766807,1.426905,1.538384,41.597885,0.243710,0.053167,0.644665,50.476622,25.322034
min,0.300000,8.000000,25.200000,5.300000,15.000000,0.000000,0.152000,1.450107,19.720000,3.155920
25%,2.600000,21.750000,26.300000,6.400000,40.000000,0.620000,0.207724,2.963901,67.545000,19.423160
50%,4.000000,26.500000,26.800000,7.000000,59.000000,0.750000,0.246327,3.303877,90.525000,23.152325
75%,5.300000,31.000000,28.500000,8.400000,88.000000,0.912500,0.280056,3.569500,119.572500,42.589875
max,11.400000,42.000000,32.200000,12.000000,220.000000,1.360000,0.536388,4.791793,276.870000,107.311760

Current Simplical Complex:  ['Stratum 3 SUMMER 14-20: ']
The shape is:  ['cube2_cluster4', 'cube0_cluster0', 'cube2_cluster0', 'cube1_cluster5', 'cube2_cluster2', 'cube1_cluster1']
The number of nodes in the shape is:  6

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,0.919173,22.756958,28.723308,8.717293,52.315789,0.029850,0.317627,2.247321,52.580150,53.671621
std,0.505967,8.682136,2.132394,2.981090,30.324100,0.117827,0.116237,0.932839,29.353381,26.629376
min,0.300000,9.000000,23.100000,1.100000,5.000000,0.000000,0.138000,0.930000,7.640000,12.912610
25%,0.550000,15.000000,27.800000,6.600000,28.000000,0.000000,0.247752,1.585523,30.680000,30.735000
50%,0.800000,22.000000,28.900000,8.400000,41.000000,0.000000,0.289822,1.987938,44.140000,51.081280
75%,1.200000,30.000000,30.100000,10.600000,75.000000,0.000000,0.366000,2.941437,79.150000,70.535380
max,3.000000,47.000000,34.300000,15.500000,116.000000,0.620000,0.959000,5.341000,125.630000,121.777920

Current Simplical Complex:  ['Stratum 4 SUMMER 14-20: ']
The shape is:  ['cube1_cluster0', 'cube0_cluster0', 'cube2_cluster0']
The number of nodes in the shape is:  3

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.0,12.000000,12.000000,12.000000,12.000000
mean,1.258333,24.416667,26.991667,8.675000,32.833333,0.0,0.296585,1.387400,34.786073,53.868560
std,0.339942,5.775471,0.782140,1.649862,9.675023,0.0,0.042173,0.108285,6.148955,7.851244
min,0.850000,16.000000,25.900000,6.800000,21.000000,0.0,0.240000,1.262000,23.990000,43.351450
25%,0.995000,20.000000,26.375000,7.450000,24.750000,0.0,0.243549,1.295844,30.550000,47.457445
50%,1.150000,25.000000,26.800000,8.150000,33.000000,0.0,0.312067,1.354604,36.411440,51.779545
75%,1.535000,27.000000,27.550000,10.025000,38.750000,0.0,0.330938,1.485797,39.765000,60.964008
max,1.930000,35.000000,28.300000,12.000000,50.000000,0.0,0.345000,1.568000,42.220000,66.258580

Current Simplical Complex:  ['Stratum 5 SUMMER 14-20: ']
The shape is:  ['cube0_cluster0', 'cube2_cluster0', 'cube0_cluster2', 'cube5_cluster0', 'cube6_cluster0', 'cube1_cluster0', 'cube4_cluster0', 'cube3_cluster0']
The number of nodes in the shape is:  8

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
mean,1.958842,28.452632,29.240000,12.674737,30.978947,0.017474,0.240889,2.421064,33.654211,71.726039
std,0.867914,4.081011,1.478239,4.508927,8.772514,0.074562,0.095062,0.563783,10.997084,31.960131
min,0.260000,20.000000,26.500000,3.400000,13.000000,0.000000,0.139000,1.438000,15.040000,17.851060
25%,1.300000,26.000000,28.150000,9.200000,25.000000,0.000000,0.185765,2.107062,27.715000,44.177800
50%,2.000000,28.000000,29.200000,13.300000,30.000000,0.000000,0.201172,2.430420,31.220000,73.999150
75%,2.600000,30.000000,30.600000,15.700000,35.500000,0.000000,0.258601,2.760124,36.300000,94.769645
max,4.200000,42.000000,31.900000,22.900000,56.000000,0.470000,0.511000,3.458000,74.530000,152.640790

# Analyzing the largest structure per simplicial complex
Largest = Node count of the shape. The largest structure is likely to be the dominant feature of the stratum during this particular time period. As such, it is important to analyze the nodes within it. To do this, we generate all the shapes, and since the shapes are returned in descending order of the number of nodes per shape, we pull the first shape. From here, we can preform an analysis on each one.

In [44]:
allComplices = list(jsonData.keys())

for key in allComplices: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    largestShape = clean_getShapes(scomplex)[0]
    nodes = scomplex.get('nodes')
    print("Largest shape is: ", largestShape)
    print("Number of nodes is: ", len(largestShape))
    for node in largestShape:
        summary = nodeDataSummary(node, scomplex,variables,df_dict.get(key))
        if summary.loc['count'][0] > 5: # 5 is chosen arbitraily
            print("Information for: ", node)
            display(summary)

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
Largest shape is:  ['cube4_cluster0', 'cube5_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube6_cluster1', 'cube5_cluster2', 'cube2_cluster0', 'cube7_cluster1', 'cube8_cluster1', 'cube3_cluster0']
Number of nodes is:  10
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,5.927500,33.500000,27.814025,7.604477,38.200000,0.298900,0.189691,3.630190,62.784683,26.714508
std,3.133498,6.778449,1.802823,0.959260,7.911351,0.283599,0.061191,0.487281,9.150042,6.916225
min,0.350000,23.000000,25.900000,6.100000,21.000000,0.000000,0.058000,2.637000,49.874813,16.934920
25%,4.000000,28.000000,26.500000,7.000000,33.750000,0.015965,0.171182,3.473000,58.700000,22.030800
50%,5.400000,33.000000,27.200000,7.650000,39.000000,0.215274,0.180000,3.692766,61.850000,24.433895
75%,8.625000,39.000000,28.600000,8.050000,44.250000,0.506116,0.206250,3.860921,64.239005,33.219975
max,12.200000,46.000000,32.900000,10.100000,50.000000,0.971381,0.365100,4.642000,88.858608,42.224000

Information for:  cube5_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,3.807143,26.142857,28.985714,7.871429,49.142857,0.438676,0.158788,3.873822,72.414286,28.956149
std,1.778208,3.184785,2.741915,1.542416,5.080307,0.267538,0.070747,0.674105,7.990709,13.200369
min,0.350000,23.000000,26.000000,5.400000,41.000000,0.000000,0.058000,2.637000,62.000000,12.129260
25%,3.500000,23.500000,26.650000,7.150000,47.000000,0.303211,0.109008,3.651500,66.000000,20.209190
50%,4.000000,25.000000,28.400000,7.800000,50.000000,0.465320,0.187000,3.966000,73.400000,25.223080
75%,4.700000,28.500000,31.150000,8.750000,51.000000,0.656281,0.206750,4.284376,79.000000,38.391130
max,5.900000,31.000000,32.900000,10.100000,57.000000,0.686430,0.235000,4.642000,81.500000,48.140060

Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,8.157143,55.428571,28.614286,7.500000,14.285714,0.247618,0.208974,3.207881,16.728571,18.131447
std,2.302793,10.706029,1.531262,0.310913,2.627691,0.213130,0.062267,0.674927,2.888318,7.343541
min,4.600000,40.000000,25.900000,6.900000,11.000000,0.000000,0.148000,2.546000,12.700000,12.482370
25%,6.850000,49.500000,28.100000,7.450000,12.000000,0.040216,0.161094,2.681500,14.600000,13.439125
50%,7.900000,51.000000,29.200000,7.500000,15.000000,0.327316,0.175000,2.833098,16.900000,14.051490
75%,9.950000,65.000000,29.550000,7.650000,16.500000,0.423604,0.264337,3.820234,18.950000,22.029770
max,11.000000,68.000000,29.900000,7.900000,17.000000,0.478372,0.288955,4.072598,20.400000,29.448480

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,5.621137,45.325000,27.812500,8.007500,22.500000,0.250978,0.147989,3.536062,29.964444,28.655538
std,2.490461,6.174337,1.421842,1.678428,4.414429,0.219522,0.056210,0.745851,6.077292,12.162111
min,1.000000,35.000000,25.800000,5.600000,14.000000,0.000000,0.033480,2.440000,14.900000,12.261240
25%,4.375000,40.750000,26.575000,7.125000,20.000000,0.000000,0.124922,2.901946,27.500000,21.438485
50%,5.350000,45.000000,27.600000,7.650000,22.000000,0.239705,0.159500,3.459376,31.400000,26.074830
75%,7.150000,50.000000,29.025000,8.300000,25.250000,0.454490,0.178683,4.014244,33.300000,30.008710
max,11.500000,58.000000,31.500000,13.200000,31.000000,0.641864,0.259545,5.372994,40.800000,60.993300

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000
mean,5.557692,42.000000,28.025995,7.488522,25.871795,0.335335,0.157649,3.724000,37.352273,26.252378
std,2.549162,6.324555,1.664690,0.835900,4.514185,0.259763,0.058402,0.673336,5.464726,7.576448
min,0.950000,29.000000,25.800000,5.400000,14.000000,0.000000,0.033480,2.432000,28.200000,16.012890
25%,3.850000,37.000000,26.550000,6.950000,23.000000,0.012390,0.125719,3.370613,32.600000,20.867355
50%,5.200000,43.000000,28.100000,7.500000,26.000000,0.399802,0.165988,3.800555,37.100000,24.236100
75%,7.200000,46.000000,29.300000,8.050000,29.000000,0.514586,0.195500,4.272985,42.900000,28.964455
max,12.200000,58.000000,31.500000,9.300000,33.000000,0.836349,0.257459,5.372994,46.300000,45.051820

Information for:  cube7_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,6.000000,6.00000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,7.069638,22.00000,28.616667,6.716667,64.000000,0.382201,0.234102,4.040002,100.116667,12.588605
std,3.447338,2.19089,1.527634,0.614546,8.671793,0.215758,0.027843,0.569140,5.381604,1.093334
min,2.100000,20.00000,26.300000,6.200000,51.000000,0.000000,0.203103,3.322286,93.800000,11.100380
25%,4.763370,21.00000,28.100000,6.350000,60.000000,0.315645,0.210076,3.601522,96.350000,12.172130
50%,7.750000,21.00000,28.450000,6.600000,63.500000,0.462964,0.235558,4.136772,99.600000,12.343610
75%,9.475000,22.50000,29.400000,6.700000,70.750000,0.491671,0.250750,4.327500,103.000000,13.093835
max,11.000000,26.00000,30.800000,7.900000,74.000000,0.599497,0.273000,4.830000,108.300000,14.285150

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,5.928846,36.614253,28.095499,7.506716,34.461538,0.319702,0.183507,3.635988,51.876657,27.001539
std,2.868664,7.302092,1.291398,0.788009,5.832535,0.293309,0.067185,0.430396,7.202493,7.785066
min,0.950000,21.000000,26.200000,6.100000,25.000000,0.000000,0.065907,2.773550,40.300000,13.232800
25%,4.025000,30.750000,27.000000,7.000000,31.000000,0.030077,0.158500,3.385000,45.775000,21.070115
50%,5.800000,38.000000,27.850000,7.450000,34.000000,0.249155,0.175000,3.697266,51.400000,24.249055
75%,8.000000,40.000000,28.900000,8.155963,38.750000,0.524213,0.209750,3.919273,58.475000,33.638430
max,12.200000,55.970568,31.500000,8.800000,47.000000,0.971381,0.380512,4.532000,65.256021,44.539100

Current Simplical Complex:  ['Stratum 2 SUMMER 93-00: ']
Largest shape is:  ['cube4_cluster0', 'cube5_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube6_cluster1', 'cube2_cluster3', 'cube9_cluster1', 'cube2_cluster0', 'cube8_cluster0', 'cube4_cluster2', 'cube8_cluster1', 'cube3_cluster0', 'cube7_cluster0']
Number of nodes is:  13
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,2.866452,29.612903,27.848387,7.403226,45.129032,0.520821,0.193622,3.598834,75.818267,21.529343
std,1.681931,5.713594,1.606419,0.830857,8.448834,0.256931,0.046085,0.723290,8.786890,8.702629
min,0.550000,20.000000,25.800000,5.600000,23.000000,0.000000,0.059000,2.444341,60.500000,11.207460
25%,2.100000,25.000000,26.150000,6.800000,41.500000,0.395000,0.169205,3.064566,69.150000,14.447050
50%,2.700000,30.000000,27.800000,7.500000,46.000000,0.480000,0.191000,3.674000,73.400000,18.251700
75%,3.300000,34.500000,29.200000,7.900000,49.500000,0.640000,0.221500,4.192951,84.189571,29.873720
max,9.000000,41.000000,31.100000,9.700000,64.000000,1.230000,0.283290,4.813000,94.048725,39.947500

Information for:  cube5_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,4.216316,24.000000,28.373684,6.931579,58.052632,0.601186,0.227695,3.913729,93.347368,21.701102
std,2.341807,4.255715,1.629875,1.159527,8.262860,0.284497,0.052152,0.572480,6.090463,15.170426
min,0.610000,17.000000,26.000000,4.400000,41.000000,0.000000,0.153376,3.068283,83.700000,11.700560
25%,2.100000,21.500000,27.150000,6.550000,53.000000,0.467929,0.195094,3.424316,88.250000,12.729440
50%,4.300000,23.000000,28.300000,6.700000,58.000000,0.550000,0.224789,4.019355,93.900000,14.368400
75%,6.150000,25.500000,28.650000,7.900000,63.500000,0.748333,0.269587,4.407577,97.600000,23.579745
max,8.000000,35.000000,31.000000,8.800000,71.000000,1.230000,0.353227,4.813000,102.600000,61.344020

Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,41.000000,41.000000,41.00000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000
mean,3.999268,48.024390,27.55122,9.248780,17.731707,0.400890,0.171494,3.737361,25.709756,35.129096
std,1.843404,6.908284,1.19940,1.943723,4.043664,0.138696,0.054598,0.674567,5.509755,15.609921
min,0.630000,34.000000,25.90000,6.500000,11.000000,0.010000,0.041000,2.416000,14.300000,5.911680
25%,2.400000,45.000000,26.80000,7.600000,15.000000,0.340000,0.148000,3.429055,21.000000,23.034640
50%,3.800000,47.000000,27.40000,8.100000,17.000000,0.400000,0.160000,3.637000,26.000000,31.527500
75%,5.500000,52.000000,28.50000,11.100000,19.000000,0.500000,0.204276,4.344456,29.300000,49.417450
max,7.900000,63.000000,30.60000,13.300000,30.000000,0.670000,0.330000,4.782617,37.700000,65.769350

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000
mean,3.728795,40.891566,27.926574,8.342490,25.698795,0.504898,0.170943,3.559074,34.830211,29.720206
std,1.848282,7.239815,1.372591,1.732904,6.647455,0.207902,0.078725,0.697416,7.196590,12.098095
min,0.720000,20.000000,25.581729,5.300000,16.000000,0.010000,0.041000,2.255000,19.700000,13.463070
25%,2.300000,35.500000,26.800000,7.400000,21.000000,0.361678,0.142898,3.172138,30.150000,21.054140
50%,3.700000,42.000000,27.600000,7.800000,26.000000,0.500000,0.169529,3.547267,34.700000,25.154940
75%,4.900000,46.000000,29.200000,8.500000,29.000000,0.660000,0.183057,4.032231,41.750000,37.978170
max,8.200000,56.000000,31.600000,14.300000,61.000000,1.010000,0.723927,5.849319,46.700000,65.769350

Information for:  cube6_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,12.000000,12.00000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,5.241667,21.75000,28.275000,6.458333,64.166667,0.780000,0.247291,4.172654,103.000000,12.887455
std,2.662350,2.70101,0.418058,0.566422,5.540485,0.317003,0.048372,0.629060,7.852388,1.419166
min,1.800000,17.00000,27.100000,4.700000,55.000000,0.310000,0.153376,3.068283,92.900000,11.014640
25%,3.525000,20.00000,28.200000,6.500000,60.000000,0.502500,0.226337,3.688829,96.950000,11.743430
50%,4.150000,22.00000,28.300000,6.600000,63.500000,0.745000,0.250030,4.550506,100.600000,12.729440
75%,6.475000,23.25000,28.525000,6.700000,69.500000,1.002500,0.261250,4.654750,109.750000,14.168060
max,11.300000,26.00000,28.700000,6.800000,72.000000,1.240000,0.353227,4.759000,116.100000,15.130160

Information for:  cube9_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,4.985714,16.000000,29.300000,6.528571,88.714286,1.102913,0.291408,3.891805,145.557143,10.365466
std,1.558235,3.651484,0.486484,0.111270,6.102302,0.356356,0.062989,0.286075,5.392852,2.176883
min,3.100000,12.000000,28.500000,6.300000,80.000000,0.670000,0.174330,3.397843,138.000000,5.955980
25%,3.750000,13.500000,29.100000,6.500000,85.000000,0.820197,0.271762,3.776397,142.250000,10.028630
50%,5.100000,15.000000,29.500000,6.600000,90.000000,1.020000,0.305000,3.897000,147.300000,10.928900
75%,6.100000,18.500000,29.600000,6.600000,91.000000,1.425000,0.325500,4.056000,148.850000,11.700560
max,7.000000,21.000000,29.700000,6.600000,99.000000,1.540000,0.366000,4.283000,151.400000,12.215000

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000
mean,3.574800,36.440000,27.871774,7.765715,33.440000,0.541573,0.165463,3.429590,46.594944,29.067709
std,1.935881,6.390956,1.311185,0.912214,7.198423,0.256059,0.037681,0.626398,8.001931,7.874827
min,0.770000,21.000000,25.581729,4.500000,24.000000,0.107857,0.059000,2.255000,19.700000,13.463070
25%,1.825000,32.000000,26.800000,7.400000,29.000000,0.355000,0.146171,3.083089,42.600000,21.786970
50%,3.400000,36.000000,27.800000,7.800000,33.000000,0.520000,0.168000,3.388037,45.900000,28.834500
75%,5.200000,42.000000,29.200000,8.350000,36.000000,0.700000,0.180833,3.677000,50.928405,36.972480
max,8.200000,48.000000,30.400000,10.000000,61.000000,1.700000,0.273202,5.849319,62.100000,42.719280

Information for:  cube8_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.00000,8.000000
mean,4.100000,19.500000,29.037500,6.562500,77.250000,0.991250,0.286713,4.182472,141.10000,10.242980
std,0.838366,5.014265,0.471888,0.118773,10.306032,0.328305,0.034684,0.303745,6.08558,1.913915
min,3.000000,13.000000,28.600000,6.400000,64.000000,0.470000,0.241000,3.754793,131.00000,5.955980
25%,3.550000,14.750000,28.700000,6.500000,69.000000,0.797500,0.255372,3.963776,137.85000,10.178675
50%,4.100000,20.000000,28.750000,6.550000,75.500000,0.960000,0.293429,4.209000,140.00000,10.843160
75%,4.575000,24.250000,29.525000,6.600000,86.250000,1.165000,0.309500,4.319487,146.62500,11.164685
max,5.300000,25.000000,29.700000,6.800000,90.000000,1.490000,0.337000,4.692000,148.70000,11.957780

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000
mean,3.271273,31.745455,27.920000,7.323636,39.356364,0.519515,0.169822,3.497791,62.429174,26.294831
std,1.962906,5.504941,1.306451,1.029736,6.319833,0.255730,0.047729,0.532569,7.538273,10.235182
min,0.870000,21.000000,25.700000,4.500000,23.000000,0.107857,0.048000,2.283976,47.300000,11.207460
25%,1.850000,27.500000,27.050000,6.800000,36.000000,0.320000,0.156724,3.228621,57.150000,16.395910
50%,2.700000,32.000000,27.700000,7.600000,39.000000,0.530000,0.176099,3.572000,61.900000,26.310240
75%,4.250000,36.000000,29.100000,8.000000,43.500000,0.640000,0.196000,3.770601,67.300000,34.037370
max,9.000000,43.000000,31.000000,10.000000,52.000000,1.700000,0.256182,4.488699,84.841382,53.455940

Information for:  cube7_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,3.638462,21.692308,28.453846,6.700000,72.461538,0.668462,0.265921,4.221007,120.507692,12.152947
std,1.753824,2.213015,0.680215,0.369685,9.743505,0.234373,0.032053,0.303221,7.985556,1.994026
min,1.600000,18.000000,26.500000,6.300000,60.000000,0.270000,0.201708,3.801504,109.200000,9.557060
25%,2.500000,20.000000,28.200000,6.500000,66.000000,0.470000,0.254000,3.986034,116.100000,10.500200
50%,3.300000,21.000000,28.600000,6.700000,71.000000,0.780000,0.269000,4.095418,120.000000,12.129260
75%,4.200000,23.000000,28.700000,6.800000,75.000000,0.800000,0.281858,4.540000,123.400000,13.637550
max,8.300000,25.000000,29.500000,7.800000,93.000000,1.100000,0.312000,4.649000,137.400000,15.473120

Current Simplical Complex:  ['Stratum 3 SUMMER 93-00: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster0', 'cube2_cluster18', 'cube2_cluster15', 'cube2_cluster1', 'cube2_cluster10']
Number of nodes is:  6
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000
mean,1.207252,28.618635,29.096002,7.714953,35.295806,0.066694,0.265853,2.672869,38.231096,48.939013
std,0.929795,9.326957,2.843665,2.309010,13.446384,0.175467,0.217364,1.022454,13.194262,26.227359
min,0.370000,16.000000,25.000000,3.900000,10.000000,0.000000,0.038000,1.055000,9.900000,9.299840
25%,0.727500,20.000000,27.500000,6.150000,24.000000,0.000000,0.156250,1.843518,28.225000,29.421980
50%,0.920000,26.000000,28.500000,7.568698,34.282555,0.000000,0.216714,2.650804,38.850000,43.791425
75%,1.277500,34.000000,30.000000,8.400000,45.250000,0.010000,0.323953,3.351575,48.250000,61.643095
max,4.900000,51.000000,39.500000,14.100000,62.000000,0.948848,1.613000,5.681667,62.000000,122.408240

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000
mean,0.724265,19.779412,29.048529,10.292647,64.176471,0.000441,0.296522,2.432739,66.480288,93.321490
std,0.266028,3.548578,2.458946,5.396387,15.545735,0.002069,0.135092,1.104711,15.884450,26.945262
min,0.320000,11.000000,24.100000,3.300000,35.000000,0.000000,0.036000,0.560000,38.900000,39.558540
25%,0.565000,17.000000,27.275000,6.450000,52.000000,0.000000,0.220308,1.800250,54.950000,68.992240
50%,0.700000,20.000000,28.650000,9.650000,63.500000,0.000000,0.304628,2.114284,64.200000,93.499360
75%,0.832500,22.000000,31.000000,12.050000,76.000000,0.000000,0.385500,3.081750,79.457696,114.040670
max,1.500000,31.000000,35.400000,25.000000,101.000000,0.010000,0.585984,8.370005,112.700000,148.505460

Current Simplical Complex:  ['Stratum 4 SUMMER 93-00: ']
Largest shape is:  ['cube2_cluster0', 'cube3_cluster4', 'cube3_cluster5', 'cube1_cluster0']
Number of nodes is:  4
Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000
mean,0.904333,18.266667,30.230000,8.673333,75.166667,0.0,0.702390,2.072581,74.993333,85.534373
std,0.534536,3.532444,2.637024,4.199420,13.811747,0.0,0.392361,0.678327,15.598429,14.306598
min,0.370000,13.000000,26.400000,2.200000,41.000000,0.0,0.314000,1.290000,44.200000,59.440470
25%,0.602500,15.250000,28.225000,6.350000,67.250000,0.0,0.429192,1.536250,64.450000,76.956193
50%,0.745000,18.000000,29.400000,7.750000,78.000000,0.0,0.675000,1.971667,74.550000,84.065120
75%,0.837500,19.000000,32.175000,9.275000,84.500000,0.0,0.715197,2.275969,87.400000,97.146260
max,2.300000,27.000000,34.500000,25.000000,101.000000,0.0,1.874142,3.965000,100.700000,118.098140

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,15.000000,15.000000,15.000000,15.000000,15.00000,15.0,15.000000,15.000000,15.000000,15.000000
mean,0.862000,19.666667,30.073333,11.300000,61.80000,0.0,0.692436,2.054374,58.513333,84.244165
std,0.425377,4.639376,2.295793,6.731801,16.63559,0.0,0.432418,0.709863,11.545430,13.904893
min,0.410000,13.000000,26.600000,2.200000,31.00000,0.0,0.277000,1.339000,36.600000,59.440470
25%,0.705000,16.000000,28.650000,6.500000,49.00000,0.0,0.461674,1.541500,50.750000,73.579980
50%,0.750000,19.000000,29.400000,8.900000,63.00000,0.0,0.569000,1.846182,60.600000,84.958260
75%,0.860000,24.000000,31.350000,14.250000,75.50000,0.0,0.704591,2.377509,66.900000,96.212410
max,2.200000,27.000000,34.100000,25.000000,85.00000,0.0,1.865000,3.965000,76.700000,106.604540

Current Simplical Complex:  ['Stratum 5 SUMMER 93-00: ']
Largest shape is:  ['cube6_cluster0', 'cube4_cluster0', 'cube5_cluster0', 'cube1_cluster0', 'cube2_cluster0', 'cube7_cluster1', 'cube7_cluster3', 'cube3_cluster0']
Number of nodes is:  8
Information for:  cube6_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,1.925714,28.357143,27.900000,14.357143,39.095238,0.004286,0.177429,2.922071,40.528571,70.326939
std,1.093677,4.723296,2.495329,5.005616,6.536831,0.005345,0.050129,0.376339,7.559258,5.623039
min,0.600000,21.000000,26.400000,9.900000,33.000000,0.000000,0.069000,2.247000,33.700000,60.345700
25%,1.165000,25.250001,26.850000,11.800000,34.500000,0.000000,0.175000,2.782000,35.100000,67.503390
50%,1.650000,30.000000,27.000000,12.600000,37.000000,0.000000,0.198000,2.905000,38.300000,72.326300
75%,2.700000,31.250000,27.350000,14.700000,43.000000,0.010000,0.207000,3.216250,44.450000,73.985775
max,3.500000,34.500001,33.500000,25.000000,48.666667,0.010000,0.211000,3.306000,52.600000,76.638240

Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000
mean,2.476522,34.586957,28.260870,8.347826,29.441712,0.000870,0.152683,3.105230,30.204348,35.819010
std,1.026054,7.417198,2.025236,1.767862,7.696056,0.002881,0.070092,0.473152,8.981065,7.974006
min,0.740000,19.000000,25.500000,4.000000,16.000000,0.000000,0.028000,2.097000,15.200000,23.618420
25%,1.700000,30.500000,26.550000,7.300000,23.500000,0.000000,0.136180,2.826423,23.000000,30.692410
50%,2.400000,35.000000,27.500000,8.700000,30.000000,0.000000,0.153667,3.183000,29.700000,33.907520
75%,3.250000,38.500000,30.350000,9.000000,35.000000,0.000000,0.170750,3.389333,35.850000,41.722320
max,4.400000,50.000000,31.000000,12.800000,42.000000,0.010000,0.412000,3.897000,49.500000,55.409100

Information for:  cube5_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,2.790556,40.916667,29.044444,10.888889,25.675521,0.001667,0.170327,3.130087,29.730336,44.337102
std,1.153157,8.938104,1.810500,1.456785,8.679227,0.003835,0.144163,0.395016,11.518603,8.895812
min,0.840000,24.000000,26.400000,8.300000,14.000000,0.000000,0.028000,2.457000,12.400000,30.821460
25%,1.925000,33.000000,27.125000,10.200000,20.000000,0.000000,0.084250,2.887000,21.000000,37.764415
50%,3.000000,44.000000,29.650000,11.200000,22.000000,0.000000,0.145583,3.077000,29.950000,41.722320
75%,3.500000,48.500000,30.575000,11.750000,35.250000,0.000000,0.173125,3.199500,38.425000,50.437170
max,4.700000,53.000000,31.500000,13.400000,40.159376,0.010000,0.640000,4.068000,49.550000,60.345700

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
mean,2.093750,25.375000,28.862500,6.950000,51.625000,0.050000,0.157687,3.999500,60.693749,24.814572
std,2.051236,4.657943,2.637606,1.282854,10.595653,0.118442,0.052250,0.605632,8.238430,3.459216
min,0.720000,20.000000,25.500000,5.000000,31.000000,0.000000,0.041000,3.328000,44.100000,20.019420
25%,1.075000,22.250000,26.525000,6.450000,48.750000,0.000000,0.149125,3.477000,57.275000,22.190850
50%,1.365000,24.500000,29.300000,7.050000,53.500000,0.000000,0.166500,3.908000,62.400000,24.952250
75%,1.950000,28.750000,31.125000,7.575000,56.000000,0.020000,0.191750,4.605750,65.775000,27.342610
max,7.000000,32.000000,31.600000,9.000000,68.000000,0.340000,0.204000,4.691000,71.049995,29.448740

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,1.911000,29.547918,28.180000,6.905000,39.100000,0.041000,0.149903,3.680077,46.957500,23.330251
std,1.374114,5.821158,2.231969,1.232232,9.153084,0.082774,0.041380,0.545070,13.363808,6.660916
min,0.700000,22.000000,25.400000,4.900000,27.000000,0.000000,0.033000,3.063875,26.100000,9.266250
25%,1.135000,24.500000,26.450000,5.550000,31.000000,0.000000,0.145062,3.275850,37.775000,20.523415
50%,1.525000,28.500000,27.050000,7.400000,38.000000,0.000000,0.153750,3.500500,45.250000,24.683400
75%,2.250000,33.500000,30.925000,7.625000,45.500000,0.052500,0.174250,4.090250,57.850000,27.391645
max,7.000000,42.958364,31.500000,9.000000,56.000000,0.340000,0.204000,4.649993,71.049995,33.564260

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,2.006667,32.458333,28.966667,7.220833,31.479167,0.013750,0.160393,3.398003,35.816667,27.256286
std,0.978751,4.643641,2.010336,1.335788,6.088976,0.039542,0.016782,0.448265,9.584801,5.789707
min,0.740000,22.000000,25.600000,4.000000,15.000000,0.000000,0.135360,2.334000,16.400000,11.403600
25%,1.230000,29.750000,26.950000,6.500000,28.750000,0.000000,0.145625,3.152625,29.175000,23.444230
50%,1.850000,32.000000,30.300000,7.600000,30.500000,0.000000,0.161750,3.314500,34.650000,27.398190
75%,2.550000,35.250000,30.500000,8.100000,35.250000,0.000000,0.174250,3.651500,43.000000,31.439690
max,4.400000,45.000000,31.100000,8.900000,41.000000,0.150000,0.184005,4.495000,58.600000,38.653620

Current Simplical Complex:  ['Stratum 1 SUMMER 98-04: ']
Largest shape is:  ['cube4_cluster0', 'cube5_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube2_cluster0', 'cube3_cluster0']
Number of nodes is:  6
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000
mean,7.019048,36.141456,27.890476,7.304762,37.047619,0.338499,0.211949,3.687669,58.076190,26.744625
std,2.346192,6.653583,1.371825,0.687369,4.432563,0.294686,0.065597,0.425504,6.434431,6.774416
min,2.000000,21.000000,26.200000,6.100000,30.000000,0.000000,0.154671,2.773550,40.300000,13.232800
25%,6.000000,34.000000,26.600000,7.000000,34.000000,0.136244,0.171759,3.540000,53.200000,22.222360
50%,7.500000,36.000000,27.600000,7.400000,36.000000,0.244480,0.181066,3.686000,59.900000,27.011360
75%,8.800000,38.000000,29.500000,7.700000,42.000000,0.603949,0.223000,3.949592,62.300000,31.498980
max,10.700000,55.970568,29.900000,8.800000,45.000000,0.971381,0.380512,4.532020,67.700000,36.627350

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,6.482310,52.405405,27.837838,8.448649,16.945946,0.160936,0.205400,3.502660,24.202703,31.768493
std,3.262616,7.935362,1.461421,1.395354,3.872596,0.164619,0.073557,1.050863,5.595806,12.266982
min,1.200000,41.000000,25.400000,5.600000,11.000000,0.000000,0.130000,1.656369,13.800000,12.261240
25%,4.700000,46.000000,26.800000,7.700000,14.000000,0.000000,0.163183,2.585529,20.200000,25.123840
50%,6.000000,50.000000,27.500000,8.300000,17.000000,0.115756,0.175000,3.437000,24.500000,28.141000
75%,8.100000,55.000000,29.200000,8.900000,20.000000,0.279436,0.226237,4.370000,28.800000,35.294670
max,13.000000,75.000000,31.300000,13.200000,25.000000,0.512200,0.480270,5.758000,35.100000,61.636230

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,46.000000,46.000000,46.00000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000
mean,5.374902,44.630435,28.01087,8.258696,22.521739,0.287956,0.192557,3.735589,33.495652,36.473464
std,2.525076,7.072195,1.46382,1.509757,3.925637,0.180077,0.067710,0.809277,5.455597,14.058158
min,1.000000,30.000000,25.30000,5.400000,15.000000,0.000000,0.050028,2.445000,23.000000,12.261240
25%,3.825000,40.250000,26.85000,7.525000,20.000000,0.149388,0.154567,3.171382,29.175000,26.223070
50%,5.400000,45.000000,28.50000,8.150000,22.500000,0.305114,0.173619,3.752316,33.200000,32.989510
75%,6.775000,49.000000,29.17500,8.800000,25.000000,0.427121,0.219550,4.337625,37.300000,47.108252
max,11.500000,60.000000,31.20000,13.200000,34.000000,0.639594,0.440779,5.653000,43.200000,61.636230

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000
mean,5.589286,38.107143,28.178571,7.796429,28.571429,0.361121,0.189239,4.023313,42.203571,35.355646
std,2.536743,5.989740,1.783122,0.881279,4.917306,0.213921,0.077255,0.661255,5.907778,13.691270
min,1.700000,21.000000,25.300000,5.400000,16.000000,0.000000,0.050028,2.712289,28.000000,16.470800
25%,4.000000,35.000000,26.875000,7.475000,26.000000,0.240596,0.154504,3.460750,39.100000,24.204520
50%,5.500000,38.000000,28.050000,7.600000,28.000000,0.329284,0.172000,4.061659,42.150000,33.446060
75%,7.650000,43.000000,29.325000,8.650000,31.000000,0.490264,0.201500,4.582000,46.375000,43.317215
max,10.400000,47.000000,31.500000,9.300000,43.000000,0.822152,0.440779,5.084000,52.100000,59.232040

Current Simplical Complex:  ['Stratum 2 SUMMER 98-04: ']
Largest shape is:  ['cube4_cluster0', 'cube5_cluster0', 'cube1_cluster0', 'cube0_cluster1', 'cube2_cluster0', 'cube3_cluster0']
Number of nodes is:  6
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,150.000000,150.000000,150.000000,150.00000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,3.530200,43.080000,28.028000,8.76600,23.366667,0.405149,0.174434,3.875682,34.444667,40.589531
std,2.366153,9.083889,1.479984,1.60167,8.159004,0.201431,0.061271,0.786911,9.178839,13.801331
min,0.300000,20.000000,25.400000,5.30000,6.000000,0.000000,0.002000,1.874175,15.300000,6.665920
25%,1.800000,38.000000,26.800000,8.00000,18.000000,0.270000,0.150000,3.332354,27.850000,30.029557
50%,3.150000,42.500000,27.800000,8.40000,22.000000,0.430000,0.164054,3.816984,33.400000,37.865320
75%,4.775000,47.000000,29.200000,8.87500,28.000000,0.530000,0.188319,4.501043,41.075000,52.453075
max,18.400000,65.000000,31.600000,18.20000,61.000000,0.880000,0.723927,5.426000,55.900000,68.848800

Information for:  cube5_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000
mean,4.232679,55.410714,27.603571,9.010714,14.392857,0.351250,0.156542,4.162728,24.010714,35.368549
std,2.229737,9.292767,1.194680,1.209760,4.084020,0.154791,0.022577,0.864870,5.160256,12.594814
min,0.630000,38.000000,25.900000,7.600000,6.000000,0.000000,0.121566,2.438000,11.500000,18.468340
25%,2.700000,50.000000,26.800000,8.275000,12.000000,0.267500,0.140645,3.527950,20.075000,25.130297
50%,3.800000,54.500000,27.200000,8.600000,15.000000,0.355000,0.152760,4.348962,24.450000,31.676205
75%,5.850000,60.000000,29.100000,9.100000,17.000000,0.480000,0.167571,5.060949,27.925000,45.653275
max,10.000000,80.000000,30.200000,12.300000,24.000000,0.700000,0.236196,5.236000,32.900000,63.413240

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,4.488462,21.961538,28.446154,6.484615,66.923077,0.692918,0.252521,4.042150,108.915385,12.502711
std,2.402054,2.424554,0.780375,0.637929,10.368888,0.270491,0.045940,0.524754,14.053005,1.682654
min,1.600000,17.000000,26.500000,4.400000,41.000000,0.270000,0.153376,3.068283,84.200000,9.557060
25%,3.000000,20.250000,28.225000,6.425000,61.250000,0.476893,0.225305,3.767761,97.500000,11.293295
50%,4.100000,22.000000,28.500000,6.600000,65.000000,0.690000,0.257661,4.023343,110.000000,12.452470
75%,5.700000,23.750000,28.700000,6.700000,71.000000,0.820000,0.277500,4.541500,119.650000,13.663823
max,11.300000,26.000000,30.900000,7.800000,93.000000,1.240000,0.353227,4.759000,137.400000,15.473120

Information for:  cube0_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,4.053333,18.866667,29.013333,6.566667,81.266667,0.913360,0.285069,4.080175,137.313333,11.163256
std,1.548209,4.189556,0.476395,0.139728,10.666815,0.332488,0.044992,0.329509,11.946958,1.994911
min,1.600000,12.000000,28.500000,6.300000,64.000000,0.470000,0.174330,3.397843,118.000000,5.955980
25%,3.050000,15.500000,28.650000,6.500000,71.500000,0.730000,0.263161,3.923500,127.200000,10.671680
50%,4.000000,19.000000,28.700000,6.600000,85.000000,0.820000,0.290000,4.016000,138.100000,11.014640
75%,4.750000,21.000000,29.500000,6.600000,90.000000,1.060000,0.309500,4.283000,147.550000,12.043520
max,7.000000,25.000000,29.700000,6.800000,99.000000,1.540000,0.366000,4.692000,151.400000,15.130160

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,3.714516,24.483871,27.906452,7.112903,53.483871,0.627823,0.222175,3.993574,84.235484,20.506689
std,2.005625,3.940144,1.685415,1.165545,9.153764,0.248832,0.043474,0.542785,12.911637,12.746568
min,0.950000,17.000000,25.800000,4.400000,40.000000,0.280000,0.153376,3.068283,60.500000,11.614820
25%,2.150000,22.000000,26.250000,6.600000,46.000000,0.465000,0.190581,3.488887,72.400000,13.380150
50%,3.100000,24.000000,28.300000,7.100000,51.000000,0.550000,0.211000,4.023685,86.300000,14.770850
75%,4.650000,26.500000,28.650000,7.900000,61.000000,0.780000,0.249091,4.448963,94.500000,20.907490
max,8.000000,33.000000,31.000000,9.000000,71.000000,1.230000,0.353227,4.813000,102.600000,61.344020

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000
mean,3.190385,32.807692,27.850000,8.079487,36.597436,0.502824,0.187337,3.740642,53.035897,35.140099
std,2.543894,6.903900,1.589066,1.657205,8.165909,0.279290,0.075113,0.671633,11.591096,14.542453
min,0.410000,20.000000,25.600000,4.500000,25.000000,0.000000,0.002000,1.874175,19.700000,6.665920
25%,1.600000,26.250000,26.700000,7.600000,31.000000,0.355602,0.158000,3.380500,45.025000,26.082070
50%,2.500000,35.000000,27.500000,8.000000,35.000000,0.520000,0.180497,3.638000,51.250000,35.654970
75%,4.200000,38.000000,29.300000,8.400000,40.000000,0.640000,0.202250,4.176589,61.600000,39.588635
max,18.400000,46.000000,31.200000,18.200000,64.000000,1.700000,0.723927,5.426000,81.700000,66.549140

Current Simplical Complex:  ['Stratum 3 SUMMER 98-04: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster0', 'cube0_cluster1', 'cube2_cluster0', 'cube0_cluster2', 'cube1_cluster6', 'cube1_cluster7', 'cube2_cluster1']
Number of nodes is:  8
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,1.241268,29.144060,28.884601,7.903957,34.442752,0.077685,0.319684,2.841300,36.992230,42.285154
std,0.964648,9.097836,2.240009,2.543288,13.820004,0.193858,0.352985,1.306616,13.519738,17.387639
min,0.370000,12.000000,25.000000,3.000000,10.000000,0.000000,0.002000,1.055000,9.900000,9.299840
25%,0.730000,22.000000,27.925000,6.150000,23.000000,0.000000,0.174433,1.737767,28.225000,26.910890
50%,0.890000,28.000000,28.500000,7.800000,33.000000,0.000000,0.275144,2.500747,36.700000,42.431940
75%,1.150000,34.500000,29.925000,9.100000,43.000000,0.015000,0.339582,3.837368,43.825000,55.557707
max,4.900000,51.000000,35.500000,14.700000,71.000000,0.948848,2.527667,6.398813,69.800000,74.202100

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000
mean,0.660946,18.000000,28.733784,8.178378,74.229730,0.001757,0.362220,2.433070,72.939189,93.410907
std,0.211590,3.792567,1.885509,3.620878,19.486945,0.008335,0.102602,0.613052,20.774113,35.054877
min,0.300000,11.000000,23.400000,2.800000,35.000000,0.000000,0.174284,1.380164,37.300000,26.597260
25%,0.500000,15.000000,27.425000,5.750000,61.250000,0.000000,0.305000,2.032007,58.625000,66.153863
50%,0.650000,18.000000,28.650000,7.750000,77.000000,0.000000,0.366449,2.204841,72.100000,86.007060
75%,0.827500,20.000000,29.800000,9.850000,91.000000,0.000000,0.397940,2.754746,85.275000,125.032385
max,1.100000,31.000000,33.700000,25.000000,108.000000,0.050000,0.650235,4.086458,121.100000,163.343920

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.0,15.000000,15.000000,15.000000,15.000000
mean,0.648667,16.400000,28.613333,10.626667,85.933333,0.0,0.429756,2.235445,81.726667,144.028314
std,0.235155,2.131398,2.578999,3.915257,10.031854,0.0,0.130238,0.432397,11.448610,15.832468
min,0.300000,13.000000,24.500000,6.200000,66.000000,0.0,0.263000,1.458000,65.600000,119.963970
25%,0.485000,15.000000,26.450000,7.350000,79.500000,0.0,0.355025,2.075874,73.300000,131.136685
50%,0.540000,16.000000,28.000000,9.300000,89.000000,0.0,0.391995,2.217682,82.000000,143.288280
75%,0.915000,18.500000,31.100000,13.600000,93.000000,0.0,0.483523,2.334811,87.900000,157.996255
max,0.970000,19.000000,32.300000,18.700000,100.000000,0.0,0.698000,3.451000,100.800000,167.211530

Information for:  cube2_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000
mean,0.606250,15.250000,28.718750,7.525000,102.562500,0.003750,0.338579,2.661216,106.100000,87.469564
std,0.171187,2.886751,1.875178,3.663059,7.676534,0.012583,0.144276,0.799613,12.563121,21.921345
min,0.340000,11.000000,25.800000,2.900000,91.000000,0.000000,0.176684,1.464953,86.900000,51.105860
25%,0.495000,14.000000,27.850000,5.100000,96.000000,0.000000,0.245953,2.103096,94.425000,73.269063
50%,0.560000,15.000000,28.950000,7.150000,102.000000,0.000000,0.327748,2.509976,109.950000,84.187890
75%,0.765000,17.000000,29.550000,8.475000,108.000000,0.000000,0.390003,3.030188,114.400000,107.984957
max,0.950000,21.000000,32.400000,17.000000,116.000000,0.050000,0.750948,4.086458,130.200000,126.044020

Current Simplical Complex:  ['Stratum 4 SUMMER 98-04: ']
Largest shape is:  ['cube2_cluster1', 'cube3_cluster0', 'cube0_cluster0', 'cube1_cluster0']
Number of nodes is:  4
Information for:  cube2_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,0.824500,18.550000,29.320000,7.430000,81.550000,0.000500,0.799378,1.886956,79.05500,84.540862
std,0.534273,2.946452,2.954675,1.790354,7.089466,0.002236,0.299046,0.487965,12.26147,12.588341
min,0.300000,11.000000,26.300000,4.600000,67.000000,0.000000,0.364000,1.160499,57.10000,65.056840
25%,0.575000,17.750000,26.750000,6.550000,77.750000,0.000000,0.615147,1.412523,70.10000,76.575880
50%,0.615000,19.000000,27.450000,7.100000,82.000000,0.000000,0.801589,1.968167,78.05000,83.654690
75%,0.800000,20.000000,32.100000,8.000000,85.750000,0.000000,1.070964,2.212549,90.20000,91.112120
max,2.300000,24.000000,33.900000,13.300000,94.000000,0.010000,1.224177,2.885041,99.30000,113.934600

Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.0,11.000000,11.000000,11.000000,11.000000
mean,0.790909,23.181818,31.181818,13.290909,40.090909,0.0,0.583625,1.618916,42.190909,102.972876
std,0.481922,2.960344,1.701069,6.344518,5.539938,0.0,0.363836,0.805044,4.562117,9.201108
min,0.510000,19.000000,28.700000,7.300000,31.000000,0.0,0.026000,0.024000,34.500000,87.455140
25%,0.585000,20.500000,29.650000,9.200000,37.000000,0.0,0.295500,1.405433,38.050000,96.556960
50%,0.640000,23.000000,31.700000,9.700000,41.000000,0.0,0.610054,1.531000,44.100000,104.493530
75%,0.725000,25.500000,32.500000,14.800000,43.500000,0.0,0.943881,2.089495,44.950000,108.684935
max,2.200000,27.000000,33.400000,25.000000,48.000000,0.0,1.028000,2.879706,48.300000,119.127730

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.0,22.000000,22.000000,22.00000,22.000000
mean,0.691818,20.318182,29.963636,10.090909,60.045455,0.0,0.703107,1.488344,55.60000,88.492328
std,0.391683,3.630379,2.802812,4.381010,14.123527,0.0,0.404185,0.748542,10.27373,16.360030
min,0.370000,13.000000,26.500000,5.900000,41.000000,0.0,0.026000,0.024000,43.80000,65.056840
25%,0.500000,19.000000,27.225000,6.950000,45.750000,0.0,0.351147,1.300555,45.92500,75.971860
50%,0.595000,20.000000,29.350000,8.850000,62.500000,0.0,0.633500,1.574500,55.15000,85.670850
75%,0.712500,22.500000,32.550000,11.975000,71.750000,0.0,1.071540,2.018500,63.80000,100.030798
max,2.200000,27.000000,34.400000,25.000000,82.000000,0.0,1.307046,2.578272,76.70000,119.127730

Current Simplical Complex:  ['Stratum 5 SUMMER 98-04: ']
Largest shape is:  ['cube4_cluster0', 'cube5_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube0_cluster1', 'cube2_cluster0', 'cube3_cluster0']
Number of nodes is:  7
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,2.513636,29.954545,29.227273,11.481818,29.454545,0.002727,0.169288,2.788364,32.136364,61.392198
std,1.262555,5.781239,2.138734,1.195674,8.370945,0.004671,0.028427,0.444319,8.577211,4.875147
min,0.400000,22.000000,26.400000,9.900000,15.000000,0.000000,0.139000,2.221000,17.800000,55.731550
25%,1.550000,26.000000,26.950000,10.900000,23.500000,0.000000,0.145500,2.442000,26.650000,57.578035
50%,3.200000,31.000000,30.500000,11.200000,29.000000,0.000000,0.160000,2.881000,33.200000,61.823180
75%,3.400000,31.750000,30.950000,11.550000,36.000000,0.005000,0.194500,2.969000,37.250000,62.861680
max,3.700000,43.000000,31.500000,14.100000,43.000000,0.010000,0.213000,3.708000,48.300000,72.193760

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000
mean,2.219750,32.275000,28.247500,7.387500,32.725000,0.024000,0.162839,3.529149,36.31000,28.441493
std,1.270214,4.690347,2.529213,1.243689,10.619256,0.060034,0.022274,0.555976,13.42842,5.039718
min,0.720000,20.000000,24.700000,4.000000,20.000000,0.000000,0.079333,2.334000,18.30000,18.734560
25%,1.250000,29.750000,25.900000,6.875000,25.000000,0.000000,0.153500,3.196466,25.70000,25.085600
50%,2.100000,33.000000,27.600000,7.500000,30.000000,0.000000,0.167250,3.441786,31.80000,29.103040
75%,3.025000,35.000000,30.525000,7.925000,35.250000,0.022500,0.175500,3.708302,43.37500,33.223895
max,7.000000,40.000000,31.600000,9.700000,68.000000,0.340000,0.204000,4.965000,66.30000,35.062720

Information for:  cube0_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000
mean,1.768571,33.997026,27.378571,6.992857,28.500000,0.040714,0.153655,3.375448,31.121429,17.472104
std,0.850492,6.084357,2.059566,1.087314,4.398426,0.059026,0.017273,0.474571,6.037980,4.341199
min,0.700000,25.000000,25.500000,4.900000,19.000000,0.000000,0.137017,2.961000,24.300000,9.266250
25%,0.890000,29.000000,25.775000,6.150000,27.000000,0.000000,0.139053,2.980480,26.575000,16.516060
50%,1.700000,32.500000,26.450000,7.500000,29.000000,0.015000,0.144458,3.290875,29.500000,17.847160
75%,2.575000,36.750001,29.650000,7.600000,32.000000,0.055000,0.168625,3.592250,33.775000,20.523415
max,3.000000,45.000000,30.500000,8.100000,33.000000,0.210000,0.184000,4.649993,41.500000,22.675280

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
mean,2.243704,32.685185,27.670370,8.140741,28.407407,0.014444,0.159485,3.472231,31.374074,35.593416
std,1.079755,5.264446,2.602043,1.069241,6.611524,0.027781,0.023609,0.480293,9.123073,4.900491
min,0.740000,19.000000,24.700000,6.700000,20.000000,0.000000,0.079333,2.334000,18.300000,29.920460
25%,1.400000,30.000000,25.450000,7.300000,23.000000,0.000000,0.151808,3.251609,24.150000,32.760320
50%,2.100000,34.000000,26.300000,7.900000,27.000000,0.000000,0.166427,3.446997,29.200000,34.175320
75%,3.150000,35.000000,30.450000,9.100000,30.000000,0.020000,0.173235,3.748500,39.700000,37.052745
max,4.400000,40.000000,31.400000,10.600000,42.000000,0.120000,0.188953,4.260000,52.300000,46.503250

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,2.480769,31.653846,28.676923,9.815385,29.076923,0.005385,0.154145,3.185793,31.369231,51.759055
std,1.047525,7.352394,2.302952,1.801780,7.815173,0.008771,0.039786,0.513348,6.869544,4.792454
min,0.900000,19.000000,24.900000,5.300000,16.000000,0.000000,0.036000,2.278000,16.700000,44.874860
25%,1.600000,28.000000,26.400000,9.200000,25.000000,0.000000,0.150461,3.033000,28.500000,46.503250
50%,2.500000,33.000000,29.000000,9.500000,27.000000,0.000000,0.158000,3.077718,30.300000,53.099780
75%,3.300000,35.000000,30.700000,11.300000,36.000000,0.010000,0.167000,3.708000,35.500000,55.731550
max,4.300000,48.000000,31.100000,11.800000,42.000000,0.030000,0.213000,3.879000,42.200000,58.483850

Current Simplical Complex:  ['Stratum 1 SUMMER 01-13: ']
Largest shape is:  ['cube4_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube2_cluster0', 'cube3_cluster1', 'cube3_cluster0']
Number of nodes is:  6
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,6.718182,16.181818,27.527273,5.109091,113.000000,0.388642,0.275861,3.288684,144.754545,11.219515
std,2.496725,1.834022,1.077117,0.945996,9.787747,0.283944,0.039279,0.757381,9.670818,1.764690
min,2.600000,12.000000,25.900000,3.700000,99.000000,0.000000,0.212211,2.179000,132.800000,9.164280
25%,4.950000,15.000000,26.400000,4.450000,106.000000,0.122138,0.246000,2.693015,139.500000,9.974620
50%,7.300000,17.000000,28.200000,5.200000,112.000000,0.493969,0.293000,3.113000,141.800000,10.825840
75%,8.150000,17.500000,28.200000,6.050000,120.000000,0.511753,0.300210,4.063546,146.150000,12.166850
max,10.200000,18.000000,28.800000,6.200000,128.000000,0.805551,0.325000,4.109222,166.800000,15.153320

Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000
mean,6.278235,49.254902,28.972549,8.760784,17.993464,0.231402,0.236170,3.154973,25.430065,40.954292
std,3.635944,9.953530,1.846556,1.534997,6.094105,0.254660,0.149535,1.062318,9.433208,23.179630
min,0.490000,25.000000,25.300000,4.400000,7.000000,0.000000,0.050028,1.098997,6.500000,12.274300
25%,3.700000,43.000000,27.600000,7.800000,13.000000,0.000000,0.158000,2.379296,18.600000,26.181860
50%,5.800000,48.000000,29.200000,8.600000,17.000000,0.185841,0.190000,3.136000,23.800000,33.155430
75%,8.200000,55.000000,29.900000,9.900000,22.000000,0.366928,0.235292,3.839979,33.000000,48.076560
max,19.300000,75.000000,33.200000,12.300000,34.000000,1.050000,1.228158,5.940472,49.600000,138.525820

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000
mean,5.202029,35.550725,28.685507,7.124638,33.782609,0.434691,0.219456,3.774528,50.179710,30.255758
std,2.926618,8.864231,1.840978,1.416853,8.793162,0.293105,0.078487,0.905516,13.472571,11.816889
min,0.450000,16.000000,25.300000,4.400000,20.000000,0.000000,0.050028,1.311000,28.000000,9.860680
25%,2.800000,30.000000,27.600000,5.800000,27.000000,0.237645,0.171759,3.323274,39.800000,23.665420
50%,5.500000,35.000000,29.000000,7.500000,33.000000,0.418486,0.201926,3.861619,46.300000,27.731480
75%,6.800000,41.000000,29.500000,7.800000,38.000000,0.655102,0.234000,4.532020,61.900000,33.409820
max,12.200000,65.000000,33.400000,11.300000,59.000000,1.020154,0.527039,5.084000,84.600000,59.232040

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,5.483871,24.870968,29.677419,5.838710,54.548387,0.333086,0.238669,3.383990,86.258065,23.197582
std,3.333376,5.572204,1.449531,0.608647,10.330662,0.322661,0.074691,0.890330,18.244228,10.507308
min,0.700000,17.000000,27.500000,4.900000,36.000000,0.000000,0.152091,1.324565,49.800000,9.860680
25%,3.000000,19.500000,28.500000,5.350000,47.500000,0.000000,0.196495,2.762011,69.450000,11.886995
50%,5.500000,25.000000,30.200000,5.700000,54.000000,0.267408,0.218000,3.284037,86.900000,25.084150
75%,7.500000,28.500000,30.600000,6.400000,58.500000,0.597500,0.256203,4.035892,101.700000,31.537305
max,11.400000,35.000000,32.800000,6.700000,78.000000,0.970294,0.527039,4.828000,118.300000,38.821380

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,8.033333,16.888889,27.811111,5.477778,86.111111,0.241078,0.248096,3.575848,118.211111,12.473358
std,5.026679,2.027588,1.062361,0.511805,11.515690,0.321260,0.093506,1.070278,14.909682,1.659277
min,1.700000,14.000000,26.300000,4.800000,64.000000,0.000000,0.147438,1.621279,97.000000,10.116490
25%,4.500000,15.000000,27.200000,5.000000,78.000000,0.000000,0.190000,3.287600,104.800000,11.532040
50%,7.200000,17.000000,28.200000,5.400000,89.000000,0.000000,0.198822,4.085000,117.400000,12.089160
75%,11.100000,18.000000,28.600000,6.000000,96.000000,0.463131,0.294439,4.220000,126.100000,13.621240
max,17.400000,20.000000,29.300000,6.100000,99.000000,0.736962,0.443508,4.789353,143.900000,15.292600

Current Simplical Complex:  ['Stratum 2 SUMMER 01-13: ']
Largest shape is:  [['cube0_cluster0', 'cube1_cluster1']]
Number of nodes is:  1
Node is a list and thus cannot get summary information:  ['cube0_cluster0', 'cube1_cluster1']
Information for:  ['cube0_cluster0', 'cube1_cluster1']

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000
mean,3.706181,39.029536,29.006962,8.224051,32.092827,0.455573,0.204445,3.425653,47.360900,39.462714
std,2.547560,12.455552,1.821232,2.094807,21.129717,0.322538,0.121665,1.085387,29.997104,24.936709
min,0.200000,15.000000,25.400000,4.300000,6.000000,0.000000,0.002000,0.935000,10.600000,2.329570
25%,1.800000,30.000000,27.600000,6.600000,17.000000,0.210000,0.152000,2.649636,24.925000,23.820982
50%,3.100000,39.000000,29.100000,8.150000,25.000000,0.380000,0.184823,3.396025,37.000000,32.745180
75%,5.100000,46.000000,30.100000,9.775000,39.000000,0.660000,0.225750,4.346609,62.875000,47.508578
max,18.400000,80.000000,38.300000,18.200000,104.000000,1.340000,1.673310,6.523909,133.700000,132.389500

Current Simplical Complex:  ['Stratum 3 SUMMER 01-13: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster0', 'cube1_cluster14', 'cube2_cluster6', 'cube1_cluster16', 'cube2_cluster0', 'cube2_cluster1']
Number of nodes is:  7
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000
mean,1.154842,26.054299,30.447964,8.738506,41.579186,0.051493,0.368413,2.519329,41.994118,48.306444
std,0.833914,9.462690,3.172489,3.532496,19.074479,0.143032,0.291896,1.006550,18.381337,28.581596
min,0.180000,11.000000,23.200000,0.400000,9.000000,0.000000,0.002000,0.919000,8.800000,7.214360
25%,0.560000,20.000000,28.300000,6.000000,25.000000,0.000000,0.209000,1.793608,28.900000,24.005430
50%,0.900000,25.000000,29.700000,8.200000,39.000000,0.000000,0.308000,2.252500,40.600000,45.716520
75%,1.400000,31.000000,32.700000,10.800000,54.000000,0.000000,0.426857,3.043000,54.500000,67.762300
max,3.900000,67.000000,38.600000,19.000000,88.000000,1.000000,2.904651,6.531588,91.800000,129.315300

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000
mean,0.606349,17.746032,30.491270,10.142638,73.896825,0.000397,0.434542,2.451640,75.709524,105.759922
std,0.285390,3.466264,2.988057,4.432866,19.324939,0.004454,0.228114,0.680223,20.172062,35.979368
min,0.180000,10.000000,23.400000,2.800000,37.000000,0.000000,0.174284,0.937000,41.800000,35.058920
25%,0.420000,15.000000,28.550000,6.700000,61.000000,0.000000,0.268162,2.033400,62.100000,79.275735
50%,0.530000,18.000000,30.250000,9.550000,71.000000,0.000000,0.372675,2.362166,72.350000,104.029900
75%,0.800000,20.000000,32.250000,13.350000,85.750000,0.000000,0.529429,2.757944,85.600000,132.286102
max,2.300000,26.000000,37.800000,21.800000,116.000000,0.050000,1.375000,4.759936,130.200000,175.992050

Information for:  cube2_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.0,7.000000,7.000000,7.000000,7.000000
mean,0.397143,12.428571,27.728571,11.571429,102.714286,0.0,0.398073,1.989556,106.442857,161.494813
std,0.178859,2.225395,2.396327,4.330402,9.250483,0.0,0.183793,0.883700,15.408965,7.148262
min,0.250000,10.000000,24.700000,7.300000,93.000000,0.0,0.232105,1.326779,90.200000,151.113910
25%,0.275000,10.500000,26.350000,7.800000,95.000000,0.0,0.251392,1.407464,94.900000,156.210460
50%,0.400000,12.000000,27.900000,11.300000,100.000000,0.0,0.363050,1.530564,100.800000,164.978080
75%,0.405000,14.500000,28.250000,14.050000,110.000000,0.0,0.495286,2.233811,117.950000,167.155040
max,0.770000,15.000000,32.300000,18.700000,116.000000,0.0,0.698000,3.787000,128.400000,167.640700

Current Simplical Complex:  ['Stratum 4 SUMMER 01-13: ']
Largest shape is:  ['cube3_cluster2', 'cube4_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube1_cluster1', 'cube0_cluster1', 'cube2_cluster0', 'cube3_cluster0']
Number of nodes is:  8
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.0,7.000000,7.000000,7.000000,7.000000
mean,0.437143,14.571429,31.542857,10.800000,75.714286,0.0,1.098864,2.040636,79.085714,113.072303
std,0.163576,1.718249,1.160254,3.359067,6.183696,0.0,0.239353,0.440216,8.679560,17.254628
min,0.250000,11.000000,29.800000,5.100000,70.000000,0.0,0.818000,1.160499,65.900000,91.132540
25%,0.320000,14.500000,30.800000,8.800000,71.500000,0.0,0.929904,1.937468,75.300000,103.013500
50%,0.400000,15.000000,31.700000,12.600000,74.000000,0.0,1.095094,2.189830,78.900000,109.639680
75%,0.525000,15.500000,32.500000,12.900000,77.500000,0.0,1.215500,2.327752,82.100000,122.075260
max,0.720000,16.000000,32.700000,14.500000,88.000000,0.0,1.488150,2.403685,94.000000,140.556380

Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,1.730606,42.303030,30.709091,6.393939,18.333333,0.004545,0.388936,1.386330,17.912121,26.583943
std,1.073310,11.058042,2.978922,1.234387,6.386835,0.021373,0.110990,0.389797,6.168861,11.382297
min,0.460000,27.000000,24.100000,3.700000,6.000000,0.000000,0.230000,0.963000,6.000000,10.027860
25%,0.780000,35.000000,29.300000,5.500000,14.000000,0.000000,0.311860,1.045000,14.900000,18.254580
50%,1.300000,40.000000,29.800000,6.300000,20.000000,0.000000,0.359992,1.207000,19.800000,25.012840
75%,3.000000,45.000000,33.200000,7.300000,23.000000,0.000000,0.530563,1.715077,22.900000,34.801870
max,3.300000,70.000000,34.800000,9.000000,27.000000,0.120000,0.547000,2.218000,26.900000,57.501070

Information for:  cube1_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000
mean,1.779767,33.302326,28.881395,7.281395,26.116279,0.003488,0.521861,1.498528,26.555814,42.396093
std,1.022989,6.170340,3.008025,2.023464,7.191957,0.018757,0.451866,0.463474,8.152835,22.321594
min,0.370000,20.000000,24.000000,5.000000,16.000000,0.000000,0.017000,0.983000,14.900000,14.433070
25%,0.875000,29.500000,27.150000,6.050000,21.500000,0.000000,0.313697,1.108794,21.050000,22.431185
50%,1.600000,34.000000,29.100000,6.600000,24.000000,0.000000,0.399000,1.336917,23.900000,35.766760
75%,2.950000,36.000000,30.000000,7.750000,31.000000,0.000000,0.484802,1.824301,33.350000,61.331100
max,3.300000,47.000000,35.500000,13.400000,42.000000,0.120000,1.871039,2.344000,42.500000,91.549870

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.0,31.000000,31.000000,31.000000,31.000000
mean,0.744839,21.677419,30.216129,8.796774,50.096774,0.0,1.203388,1.862887,47.887097,83.205492
std,0.444521,4.657518,2.521785,1.835662,12.926342,0.0,0.562865,0.789886,9.090352,14.988974
min,0.370000,15.000000,26.500000,6.000000,31.000000,0.0,0.026000,0.024000,33.800000,62.103600
25%,0.495000,19.500000,27.700000,7.350000,40.500000,0.0,0.943881,1.513290,40.700000,72.667475
50%,0.590000,20.000000,30.200000,8.800000,48.000000,0.0,1.081617,2.237158,45.700000,77.438700
75%,0.675000,22.000000,32.550000,9.750000,60.000000,0.0,1.752239,2.318215,55.850000,89.554960
max,1.800000,32.000000,34.400000,13.600000,77.000000,0.0,2.168000,2.879706,65.200000,119.127730

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.0,29.000000,29.000000,29.000000,29.000000
mean,0.491379,17.206897,29.555172,9.220690,70.931034,0.0,1.222990,1.969179,67.072414,91.187522
std,0.120408,2.273753,2.303505,2.520683,8.795011,0.0,0.351939,0.608676,9.110077,21.766656
min,0.250000,13.000000,26.300000,5.100000,53.000000,0.0,0.735784,0.024000,45.400000,65.056840
25%,0.440000,15.000000,27.600000,7.400000,67.000000,0.0,1.070600,1.684314,60.600000,73.912510
50%,0.500000,17.000000,29.800000,8.600000,71.000000,0.0,1.130808,2.243771,65.900000,84.183200
75%,0.580000,20.000000,31.400000,11.100000,77.000000,0.0,1.224177,2.309500,73.200000,111.287980
max,0.720000,20.000000,34.800000,14.500000,94.000000,0.0,2.168000,2.678000,82.400000,140.556380

Current Simplical Complex:  ['Stratum 5 SUMMER 01-13: ']
Largest shape is:  ['cube2_cluster1', 'cube0_cluster0', 'cube1_cluster0', 'cube2_cluster2']
Number of nodes is:  4
Information for:  cube2_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.0,6.000000,6.000000,6.000000,6.000000
mean,1.218333,24.000000,30.283333,8.616667,42.500000,0.0,0.180604,3.032768,46.100000,39.491572
std,0.329995,3.949684,1.810433,1.749762,3.271085,0.0,0.085926,1.160983,6.187407,8.739263
min,0.870000,20.000000,27.900000,5.100000,39.000000,0.0,0.079333,1.545000,38.900000,28.757340
25%,1.005000,20.500000,28.825000,8.900000,40.250000,0.0,0.147650,2.227589,41.175000,32.417642
50%,1.200000,23.500000,30.850000,9.300000,42.000000,0.0,0.158896,3.105303,45.750000,41.041415
75%,1.275000,27.250000,31.375000,9.475000,43.750000,0.0,0.195423,3.613562,51.525000,44.262840
max,1.800000,29.000000,32.400000,9.700000,48.000000,0.0,0.335000,4.723000,53.100000,51.229560

Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,132.000000,132.000000,132.000000,132.000000,132.000000,132.000000,132.000000,132.000000,132.000000,132.000000
mean,2.838712,36.424242,29.918182,11.431061,20.333333,0.013258,0.172454,2.790015,23.332576,54.471432
std,1.608594,7.387963,2.582910,3.729317,4.498798,0.049755,0.042849,0.786676,5.831207,23.333929
min,0.460000,25.000000,24.700000,5.300000,10.000000,0.000000,0.036000,1.289000,11.100000,16.452220
25%,1.500000,30.750000,27.800000,8.625000,17.000000,0.000000,0.142982,2.283000,18.975000,36.220270
50%,2.650000,35.000000,30.100000,11.300000,20.500000,0.000000,0.168005,2.810750,22.900000,50.730160
75%,3.825000,40.000000,31.925000,14.025000,23.000000,0.000000,0.189215,3.277447,26.700000,68.055683
max,9.400000,58.000000,34.900000,20.500000,34.000000,0.380000,0.307000,4.825473,40.700000,126.426440

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,2.283918,31.319588,28.924742,9.791753,28.278351,0.021649,0.171846,3.047676,31.653608,46.522145
std,1.665005,6.033839,2.483908,3.158707,7.521832,0.058926,0.045299,0.862843,9.088237,21.167659
min,0.400000,18.000000,24.700000,5.100000,18.000000,0.000000,0.036000,1.289000,15.900000,16.516060
25%,1.000000,28.000000,26.900000,7.800000,23.000000,0.000000,0.145000,2.369000,24.500000,30.714460
50%,1.700000,30.000000,28.900000,9.300000,26.000000,0.000000,0.167000,2.980480,29.800000,43.427160
75%,3.200000,35.000000,30.700000,10.800000,32.000000,0.000000,0.185582,3.685000,37.200000,56.007580
max,9.400000,49.000000,34.600000,20.500000,53.000000,0.380000,0.335000,4.965000,56.100000,102.407070

Current Simplical Complex:  ['Stratum 1 SUMMER 10-16: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster0', 'cube4_cluster1', 'cube2_cluster0', 'cube3_cluster0']
Number of nodes is:  5
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
mean,6.561765,45.441176,29.835294,7.529412,17.441176,0.232029,0.252561,3.208299,23.541176,28.990368
std,4.363069,9.244789,1.868865,1.842516,8.102342,0.299944,0.164984,1.384253,11.653277,4.753252
min,1.600000,21.000000,26.600000,4.400000,8.000000,0.000000,0.142000,1.151000,11.400000,21.261240
25%,3.500000,40.000000,28.600000,5.650000,12.000000,0.000000,0.182460,1.925932,15.800000,25.420987
50%,6.250000,45.500000,29.800000,8.100000,15.000000,0.071875,0.204000,3.364428,19.200000,28.824000
75%,8.100000,51.500000,31.700000,8.950000,18.750000,0.434349,0.231445,4.328250,27.200000,33.170820
max,19.300000,62.000000,32.600000,10.200000,35.000000,0.919989,0.928245,5.940472,54.300000,37.659000

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,46.000000,46.000000,46.00000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000
mean,5.476087,28.413043,28.13913,6.295652,41.956522,0.443328,0.231560,3.755694,69.350435,21.628906
std,2.734080,4.874314,2.39086,0.917958,7.486155,0.322191,0.051948,0.896716,13.536788,7.019399
min,0.700000,17.000000,24.80000,4.400000,29.000000,0.000000,0.171000,1.056507,38.600000,10.683970
25%,3.600000,25.000000,25.62500,5.500000,36.000000,0.134571,0.206000,3.320362,63.875000,16.080713
50%,5.450000,28.000000,28.25000,6.350000,41.000000,0.440977,0.218000,3.922500,70.615000,21.856550
75%,6.700000,32.750000,30.27500,6.975000,47.000000,0.713639,0.245768,4.342250,75.900000,26.438453
max,12.200000,37.000000,32.80000,8.300000,67.000000,0.970294,0.527039,4.828000,95.700000,38.135820

Information for:  cube4_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.00000,8.000000
mean,6.012500,15.875000,27.900000,4.812500,117.500000,0.292634,0.282245,3.030284,143.81875,12.225820
std,2.357624,1.885092,0.558058,0.862616,9.546877,0.316018,0.053968,0.619291,7.93257,3.307369
min,2.600000,12.000000,27.000000,3.700000,100.000000,0.000000,0.187224,2.179000,132.80000,9.549010
25%,4.400000,15.000000,27.825000,3.950000,114.000000,0.000000,0.273461,2.695483,139.62500,9.974620
50%,6.350000,16.500000,28.200000,5.100000,120.000000,0.263589,0.294000,3.056933,141.80000,10.613035
75%,7.925000,17.000000,28.200000,5.350000,124.000000,0.503930,0.304923,3.243750,149.12500,13.502100
max,8.900000,18.000000,28.300000,5.800000,128.000000,0.805551,0.361000,4.053759,156.35000,17.562920

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000
mean,5.889744,24.948718,28.648718,6.464103,60.615385,0.462092,0.227995,3.331086,98.234615,22.678118
std,2.632369,4.173530,1.984794,0.614083,11.212341,0.336741,0.043616,0.794748,12.172170,8.089312
min,0.800000,17.000000,24.800000,4.900000,41.000000,0.000000,0.140535,1.324565,75.300000,9.653400
25%,4.100000,21.500000,27.800000,6.350000,52.000000,0.085862,0.195879,2.751877,88.460000,16.511250
50%,5.900000,26.000000,29.000000,6.600000,60.000000,0.520773,0.234722,3.435000,98.170000,20.658600
75%,7.500000,28.000000,30.250000,6.700000,68.500000,0.720331,0.254166,3.945964,106.940000,29.823405
max,11.700000,32.000000,31.800000,7.600000,82.000000,1.022370,0.329000,4.760000,119.880000,38.821380

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000
mean,7.290476,16.380952,28.342857,5.852381,103.952381,0.468299,0.255288,3.230023,126.402857,18.163210
std,3.284342,2.906479,0.566190,1.105269,15.347561,0.320335,0.043200,0.620048,13.526093,6.657988
min,2.600000,12.000000,27.000000,3.700000,78.000000,0.000000,0.176219,2.179000,110.440000,9.549010
25%,5.100000,15.000000,28.100000,5.000000,98.000000,0.053943,0.234493,3.014000,116.500000,10.825840
50%,7.300000,16.000000,28.200000,6.600000,104.000000,0.525257,0.253000,3.149000,119.880000,19.694100
75%,8.300000,18.000000,28.300000,6.700000,116.000000,0.668549,0.291000,3.582200,137.350000,24.190140
max,17.400000,23.000000,29.700000,6.900000,128.000000,0.875559,0.361000,4.789353,156.350000,29.376660

Current Simplical Complex:  ['Stratum 2 SUMMER 10-16: ']
Largest shape is:  ['cube4_cluster0', 'cube4_cluster1', 'cube1_cluster0', 'cube5_cluster2', 'cube0_cluster1', 'cube2_cluster0', 'cube3_cluster1', 'cube3_cluster0']
Number of nodes is:  8
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,4.866667,14.666667,28.191667,5.350000,136.333333,0.883333,0.273959,3.317975,152.763333,13.973889
std,1.761370,3.393398,0.350216,0.762174,16.837908,0.252130,0.041638,0.735682,14.144024,4.670095
min,1.200000,9.000000,27.600000,4.100000,116.000000,0.150000,0.191774,2.393000,134.800000,9.549010
25%,3.975000,11.750000,28.100000,4.700000,123.000000,0.900000,0.260038,2.598526,136.960000,10.506633
50%,5.000000,15.500000,28.200000,5.600000,134.000000,0.920000,0.285854,3.158304,156.200000,11.960800
75%,5.850000,17.000000,28.300000,5.850000,143.000000,1.005000,0.291750,4.073559,164.482500,15.690010
max,7.500000,20.000000,29.000000,6.300000,168.000000,1.120000,0.341447,4.367226,174.400000,23.325720

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000
mean,4.481053,30.228070,28.343860,6.344737,42.850877,0.792708,0.234080,3.821235,71.165758,23.162827
std,2.047610,3.584715,2.239036,0.882985,7.238335,0.282592,0.139798,0.914088,14.300501,7.971654
min,0.420000,23.000000,25.200000,4.400000,28.000000,0.000000,0.171000,1.182264,37.800000,2.329570
25%,3.000000,28.000000,25.600000,5.600000,38.000000,0.610000,0.197250,3.135592,61.395000,18.672750
50%,4.500000,30.000000,28.700000,6.400000,42.000000,0.835000,0.215924,3.977172,70.650000,21.533790
75%,6.075000,32.750000,30.175000,7.000000,47.750000,1.000000,0.234958,4.601500,83.427500,28.666522
max,10.300000,41.000000,34.600000,8.300000,63.000000,1.260000,1.673310,6.523909,101.000000,43.965610

Information for:  cube0_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000
mean,3.509104,40.432836,30.159701,8.055224,21.537313,0.317777,0.232899,3.164783,29.481775,30.243654
std,2.395485,10.348802,1.839224,1.809594,8.992132,0.298831,0.183355,1.367993,12.978095,7.603890
min,0.300000,23.000000,25.200000,5.200000,10.000000,0.000000,0.155000,0.990000,14.500000,10.400230
25%,1.675000,30.500000,29.200000,6.650000,14.000000,0.120000,0.183415,1.822531,19.250000,24.277250
50%,3.000000,38.000000,29.500000,8.100000,19.000000,0.240000,0.200000,2.998943,24.400000,31.015080
75%,4.700000,50.000000,31.150000,9.500000,29.500000,0.480000,0.221973,4.471637,38.350000,35.821320
max,10.300000,60.000000,35.200000,12.000000,45.000000,1.240000,1.673310,6.523909,56.460000,42.465240

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000
mean,3.896277,25.521277,28.929787,6.325532,66.659574,0.816897,0.240482,3.328665,102.658939,23.108576
std,2.266140,5.754341,1.950618,0.790391,16.813047,0.228038,0.048515,0.895910,14.524606,9.135370
min,0.600000,15.000000,25.200000,4.300000,40.000000,0.000000,0.168543,1.182000,74.700000,8.555920
25%,2.300000,22.000000,28.100000,5.825000,52.000000,0.672500,0.201679,2.906177,88.750000,16.511250
50%,3.600000,25.000000,29.300000,6.400000,64.000000,0.825000,0.228572,3.429850,105.310000,20.748125
75%,5.075000,30.000000,30.300000,6.700000,80.000000,0.967500,0.282500,3.902727,113.010000,30.251880
max,12.000000,38.000000,32.500000,10.200000,104.000000,1.360000,0.355000,4.791793,129.100000,42.606600

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000
mean,4.191273,18.472727,28.301818,5.876364,97.981818,0.845566,0.267514,3.340949,126.720727,16.399015
std,2.499599,4.654168,0.737737,0.660797,15.991307,0.196861,0.046275,0.463896,14.414290,5.859247
min,0.780000,9.000000,25.900000,4.300000,71.000000,0.350000,0.145235,2.393000,104.730000,3.155920
25%,2.200000,15.000000,28.100000,5.500000,85.000000,0.740058,0.243982,3.001500,117.770000,10.329295
50%,3.700000,17.000000,28.100000,6.000000,98.000000,0.877321,0.265461,3.337112,124.620000,16.266290
75%,5.450000,22.500000,28.600000,6.400000,112.000000,0.940000,0.293071,3.515691,131.750000,20.562150
max,10.800000,33.000000,29.700000,6.800000,140.000000,1.340000,0.376570,4.529150,171.480000,30.097010

Current Simplical Complex:  ['Stratum 3 SUMMER 10-16: ']
Largest shape is:  ['cube2_cluster10']
Number of nodes is:  1
Current Simplical Complex:  ['Stratum 4 SUMMER 10-16: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster0', 'cube0_cluster1', 'cube2_cluster0', 'cube3_cluster1', 'cube2_cluster1']
Number of nodes is:  6
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,14.000000,14.000000,14.000000,14.000000,14.000000,14.0,14.000000,14.000000,14.000000,14.000000
mean,1.137857,50.785714,33.014286,6.150000,11.928571,0.0,0.443679,1.297471,11.878571,21.205345
std,0.866702,11.517068,1.561487,1.524038,3.989685,0.0,0.099829,0.336520,4.358401,9.972774
min,0.460000,36.000000,29.500000,3.700000,6.000000,0.0,0.281449,0.963000,6.000000,10.027860
25%,0.732500,42.750000,32.925000,5.100000,9.000000,0.0,0.362368,1.021173,8.700000,12.855795
50%,0.900000,45.500000,33.200000,5.850000,11.500000,0.0,0.481000,1.193500,10.900000,19.197225
75%,0.950000,60.000000,33.975000,7.375000,14.750000,0.0,0.531806,1.462691,15.750000,28.580828
max,3.200000,70.000000,34.800000,8.700000,18.000000,0.0,0.547000,2.145733,18.000000,40.476670

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,1.941000,34.600000,29.806667,7.796667,21.600000,0.005000,0.364532,1.422347,21.845333,40.637381
std,1.164268,5.733146,3.105605,2.246144,4.406891,0.022399,0.113296,0.342330,5.229129,21.800275
min,0.460000,22.000000,24.100000,5.000000,14.000000,0.000000,0.210000,0.983000,14.900000,17.209990
25%,0.752500,32.250000,28.500000,6.150000,17.250000,0.000000,0.258250,1.167798,17.775000,21.948638
50%,2.165000,35.000000,29.600000,7.400000,22.000000,0.000000,0.331875,1.354000,21.550000,33.640910
75%,3.100000,36.750000,30.650000,8.625000,25.750000,0.000000,0.468240,1.703003,24.597500,56.327298
max,3.300000,46.000000,35.500000,13.400000,29.000000,0.120000,0.535000,2.218000,32.900000,91.549870

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,10.000000,10.000000,10.000000
mean,1.136000,24.700000,27.700000,8.450000,32.600000,0.0,0.315589,1.354433,35.171288,54.748660
std,0.308912,5.229192,2.831176,1.598089,7.691265,0.0,0.049636,0.124473,5.107003,8.370539
min,0.650000,17.000000,25.900000,6.800000,21.000000,0.0,0.240000,1.166026,27.000000,43.351450
25%,0.985000,20.750000,26.325000,7.350000,26.750000,0.0,0.303034,1.282336,31.102500,47.673550
50%,1.065000,25.000000,26.800000,7.850000,33.000000,0.0,0.319635,1.308491,36.411440,54.091030
75%,1.312500,26.500000,27.775000,9.675000,37.750000,0.0,0.332954,1.459052,39.215000,61.612323
max,1.650000,35.000000,35.500000,11.200000,44.000000,0.0,0.413544,1.568000,41.160000,66.258580

Current Simplical Complex:  ['Stratum 5 SUMMER 10-16: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster0', 'cube4_cluster1', 'cube2_cluster0', 'cube3_cluster0']
Number of nodes is:  5
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,43.000000,43.000000,43.000000,43.000000,43.000000,43.0,43.000000,43.000000,43.000000,43.000000
mean,3.106512,32.209302,30.023256,8.788372,23.790698,0.0,0.179294,2.849848,24.311628,38.834779
std,1.824474,4.621678,2.003549,2.198615,7.314559,0.0,0.044868,0.799825,6.501545,9.075036
min,0.780000,22.000000,26.000000,5.500000,13.000000,0.0,0.117000,1.289000,15.040000,17.851060
25%,1.650000,29.000000,29.350000,7.300000,20.000000,0.0,0.143609,2.408750,19.350000,32.425500
50%,2.900000,34.000000,30.400000,9.100000,21.000000,0.0,0.177002,2.735196,22.200000,40.627560
75%,4.050000,35.500000,31.150000,9.500000,27.000000,0.0,0.202037,3.330395,27.500000,45.158380
max,9.400000,42.000000,34.000000,15.800000,44.000000,0.0,0.283000,4.398842,40.800000,51.275300

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,55.000000,55.000000,55.000000,55.000000,55.000000,55.0,55.000000,55.000000,55.000000,55.000000
mean,2.473818,30.109091,30.929091,10.500000,24.072727,0.0,0.197723,2.562922,25.885455,53.810309
std,1.569309,4.681218,2.070129,3.513308,7.887765,0.0,0.061040,0.705748,8.029441,9.900240
min,0.260000,18.000000,26.000000,5.100000,13.000000,0.0,0.119649,1.289000,15.040000,37.156440
25%,1.225000,27.000000,30.300000,8.550000,19.000000,0.0,0.147524,2.187638,21.060000,45.158380
50%,2.200000,30.000000,30.900000,10.300000,21.000000,0.0,0.188911,2.493000,22.900000,51.229560
75%,3.300000,34.000000,32.350000,13.150000,28.000000,0.0,0.250422,3.113244,29.255000,62.730285
max,6.000000,42.000000,34.800000,18.000000,48.000000,0.0,0.335000,4.398842,53.100000,74.182430

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,27.000000,27.000000,27.000000,27.000000,27.000000,27.0,27.000000,27.000000,27.000000,27.000000
mean,1.803704,28.111111,30.374074,14.433333,25.333333,0.0,0.195078,2.809770,29.285185,78.456474
std,0.990905,3.915780,2.678202,2.534531,6.855655,0.0,0.066592,0.665737,7.242475,10.927082
min,0.500000,18.000000,26.400000,9.800000,16.000000,0.0,0.123695,1.398325,18.540000,64.187100
25%,1.025000,26.000000,27.800000,12.850000,21.000000,0.0,0.153500,2.343500,24.625000,69.875360
50%,1.800000,28.000000,30.500000,13.600000,25.000000,0.0,0.182965,2.917315,28.100000,75.156060
75%,2.200000,31.000000,32.500000,16.300000,27.500000,0.0,0.200475,3.407989,31.655000,87.362150
max,4.600000,36.000000,34.900000,19.600000,43.000000,0.0,0.444069,3.685000,45.800000,98.098050

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.0,12.000000,12.000000,12.000000,12.000000
mean,1.566667,28.583333,29.575000,15.733333,24.583333,0.0,0.183308,3.176590,29.830833,100.411627
std,0.588269,3.604501,2.677558,2.054854,5.451577,0.0,0.028235,0.348352,5.885355,8.824784
min,0.500000,23.000000,26.600000,12.700000,18.000000,0.0,0.142929,2.446000,21.520000,88.524150
25%,1.275000,27.500000,27.550000,14.475000,22.000000,0.0,0.172000,3.070952,27.190000,94.060433
50%,1.700000,28.000000,28.800000,15.200000,23.000000,0.0,0.179500,3.264489,28.045000,98.903225
75%,1.900000,28.750000,30.600000,16.925000,25.000000,0.0,0.193891,3.441500,31.397500,103.825700
max,2.600000,36.000000,34.900000,19.600000,40.000000,0.0,0.253000,3.510000,44.700000,119.462400

Current Simplical Complex:  ['Stratum 1 SUMMER 14-20: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster0', 'cube2_cluster2', 'cube2_cluster0', 'cube3_cluster1', 'cube4_cluster4']
Number of nodes is:  6
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,6.276667,37.222222,26.488889,8.850000,27.222222,0.519645,0.212508,2.805806,40.015556,51.918704
std,3.297901,5.493906,1.438091,1.266422,5.796100,0.236280,0.055141,0.538122,11.707283,11.276626
min,0.680000,31.000000,25.300000,6.000000,15.000000,0.000000,0.109000,2.084000,22.010000,22.469510
25%,3.950000,33.000000,25.500000,8.350000,24.000000,0.469256,0.189526,2.314002,30.497500,50.563812
50%,6.350000,36.000000,25.900000,8.850000,30.000000,0.561176,0.210917,2.760576,37.990000,54.162150
75%,8.600000,39.750000,26.750000,9.675000,31.000000,0.584063,0.234000,3.105314,50.140000,59.401292
max,11.700000,48.000000,29.200000,11.000000,34.000000,0.889338,0.335296,3.945751,60.480000,64.890630

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,54.000000,54.000000,54.000000,54.000000,54.00000,54.000000,54.000000,54.000000,54.000000,54.000000
mean,5.466667,30.727333,26.601852,7.927778,40.37037,0.460247,0.228791,3.279014,67.604815,36.664149
std,2.215809,4.019982,1.378609,1.154224,9.20274,0.333040,0.041513,0.752015,13.967570,17.681482
min,2.100000,24.000000,24.800000,5.100000,25.00000,0.000000,0.140000,1.056507,30.760000,13.720400
25%,3.800000,27.000000,25.500000,7.225000,32.00000,0.043394,0.198075,2.830670,59.745000,18.295775
50%,5.400000,30.777534,26.200000,7.700000,39.00000,0.470282,0.233000,3.240745,68.990000,34.983115
75%,6.800000,33.000000,27.100000,8.775000,46.00000,0.731330,0.255250,3.845115,75.880000,51.150688
max,12.300000,40.000000,29.600000,10.500000,63.00000,1.011591,0.335296,4.628146,93.650000,72.416960

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
mean,6.482222,26.386379,27.944444,6.964444,63.311111,0.488728,0.234275,3.308744,97.970000,24.453775
std,2.535143,3.638418,1.425507,0.612801,10.629766,0.333175,0.055843,0.639172,11.371784,8.268817
min,0.900000,18.000000,24.800000,5.400000,41.000000,0.000000,0.140535,1.538236,75.000000,9.653400
25%,4.500000,24.000000,27.800000,6.500000,57.000000,0.200000,0.197056,2.990897,89.230000,18.729600
50%,6.400000,26.662078,28.300000,6.900000,63.000000,0.560000,0.234493,3.381026,98.390000,22.435400
75%,8.200000,29.000000,28.900000,7.600000,68.000000,0.761798,0.256000,3.678423,105.180000,30.712370
max,12.300000,33.448966,29.700000,8.000000,87.000000,1.022370,0.494508,4.349000,119.880000,40.102240

Information for:  cube3_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,6.900000,18.719057,28.063158,6.710526,96.157895,0.579732,0.253454,3.244719,117.834211,21.836977
std,1.943079,3.860108,1.108658,0.270585,15.008380,0.291842,0.027308,0.427512,7.712745,3.208708
min,3.800000,13.000000,26.400000,5.800000,76.000000,0.000000,0.176219,2.331215,105.950000,16.531750
25%,5.400000,15.000000,27.300000,6.650000,82.500000,0.513539,0.241900,3.051000,113.365000,19.499745
50%,6.500000,20.000000,28.200000,6.700000,99.000000,0.645982,0.253000,3.149000,117.390000,21.185620
75%,8.300000,21.000000,28.950000,6.900000,104.000000,0.733981,0.265906,3.479434,119.690000,24.190140
max,10.900000,26.662078,29.700000,7.000000,128.000000,1.019107,0.307000,4.145000,137.350000,29.376660

Current Simplical Complex:  ['Stratum 2 SUMMER 14-20: ']
Largest shape is:  ['cube5_cluster1', 'cube6_cluster0', 'cube4_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube7_cluster2', 'cube2_cluster0', 'cube3_cluster0', 'cube7_cluster0']
Number of nodes is:  9
Information for:  cube5_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,3.791667,12.416667,27.991667,6.141667,160.000000,0.805833,0.305281,3.474108,201.476667,19.591152
std,2.442599,2.712206,1.014852,0.326018,8.045326,0.243589,0.078068,0.800941,20.659782,2.099458
min,0.700000,9.000000,26.300000,5.700000,148.000000,0.150000,0.252770,1.450107,165.870000,15.450300
25%,1.425000,10.750000,27.600000,5.950000,152.000000,0.720000,0.267390,3.258705,187.602500,18.211235
50%,4.050000,12.000000,27.800000,6.100000,160.000000,0.870000,0.283178,3.665907,205.055000,19.516135
75%,4.775000,13.250000,29.000000,6.300000,166.500000,0.930000,0.297326,4.034580,214.592500,20.856547
max,8.300000,19.000000,29.300000,6.700000,172.000000,1.100000,0.536388,4.299000,231.460000,22.501780

Information for:  cube6_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,5.766667,11.166667,28.191667,5.925000,173.500000,0.813333,0.284706,3.918513,247.863333,18.074698
std,2.803353,1.696699,0.715362,0.226134,14.119619,0.190708,0.034044,0.296274,17.236512,2.235928
min,0.700000,8.000000,27.500000,5.600000,152.000000,0.350000,0.241641,3.294882,221.800000,12.363900
25%,3.575000,10.000000,27.600000,5.775000,164.500000,0.700000,0.253695,3.757927,232.015000,17.696497
50%,6.300000,12.000000,27.750000,5.900000,175.000000,0.910000,0.281356,4.024500,256.165000,18.915440
75%,8.300000,12.250000,29.000000,6.050000,180.000000,0.930000,0.300671,4.118729,258.425000,19.340182
max,8.600000,13.000000,29.300000,6.300000,200.000000,1.050000,0.346000,4.299000,276.870000,20.012110

Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,3.748421,16.842105,27.010526,6.400000,130.105263,0.724211,0.296724,3.398204,167.450526,21.509325
std,2.300138,3.833524,0.879327,0.316228,19.688956,0.279887,0.037666,0.478041,9.333731,3.714843
min,0.600000,10.000000,26.300000,5.800000,98.000000,0.150000,0.236199,2.585106,149.000000,14.969660
25%,1.450000,14.500000,26.400000,6.100000,120.000000,0.490000,0.275979,3.033969,162.415000,18.716190
50%,4.100000,16.000000,26.400000,6.600000,128.000000,0.760000,0.285473,3.337112,167.670000,22.501780
75%,5.100000,19.500000,27.700000,6.650000,140.000000,0.925000,0.314933,3.784126,173.615000,23.723930
max,8.700000,24.000000,29.000000,6.700000,168.000000,1.100000,0.385264,4.107947,189.000000,27.202350

Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000
mean,4.169863,33.410959,26.684932,8.834247,35.424658,0.621627,0.230139,3.069325,57.071507,54.482196
std,1.899100,4.686967,1.405216,1.243117,5.079692,0.255139,0.049811,0.653630,11.763113,25.308254
min,0.300000,23.000000,25.200000,6.000000,15.000000,0.000000,0.152000,1.821861,19.720000,14.882400
25%,2.800000,30.000000,25.500000,8.100000,33.000000,0.490000,0.191483,2.683871,52.360000,40.281500
50%,4.100000,34.000000,26.400000,8.800000,35.000000,0.660000,0.225252,3.175987,61.140000,47.950000
75%,5.300000,38.000000,27.000000,9.900000,38.000000,0.780000,0.263207,3.455707,65.500000,65.321500
max,11.400000,42.000000,32.200000,12.000000,45.000000,1.160000,0.407246,4.689808,71.250000,106.969660

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000
mean,4.306759,30.531034,26.817931,8.355862,44.337931,0.722612,0.226906,3.172458,72.806828,47.409816
std,1.973916,5.116769,1.459627,1.502723,9.489922,0.222429,0.047328,0.740869,13.210323,28.935171
min,0.780000,19.000000,25.200000,5.400000,29.000000,0.100000,0.152000,1.871000,44.110000,11.741000
25%,3.000000,27.000000,25.500000,7.200000,37.000000,0.620000,0.191196,2.727383,63.880000,21.273400
50%,4.300000,30.000000,26.500000,8.000000,42.000000,0.730000,0.225000,3.234567,70.200000,40.907500
75%,5.400000,34.000000,28.300000,9.800000,50.000000,0.870000,0.257000,3.515381,83.420000,58.122500
max,11.400000,42.000000,32.200000,11.300000,66.000000,1.200000,0.407246,4.791793,101.630000,107.311760

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000
mean,3.804333,24.622222,28.130000,6.664444,73.855556,0.796889,0.249171,3.231298,106.998889,24.099913
std,1.872016,4.371968,1.239015,0.696913,13.289821,0.206608,0.047481,0.439603,12.219910,8.447870
min,0.370000,15.000000,25.200000,5.300000,51.000000,0.270000,0.169645,2.145167,84.640000,9.663300
25%,2.325000,22.000000,27.700000,6.300000,63.000000,0.680000,0.211471,3.006881,98.402500,18.562445
50%,3.600000,24.000000,28.500000,6.600000,72.000000,0.785000,0.252000,3.308152,106.685000,20.851500
75%,4.775000,27.750000,29.175000,7.000000,84.000000,0.917500,0.278750,3.485201,116.947500,32.437040
max,9.100000,33.000000,29.700000,8.000000,104.000000,1.360000,0.355000,4.503000,137.440000,41.443650

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.00000,52.000000
mean,3.496923,19.865385,27.773077,6.476923,96.596154,0.779038,0.265535,3.275859,127.37000,20.592508
std,1.686032,4.238150,1.150467,0.391385,13.502737,0.214935,0.043542,0.341163,14.70179,4.483520
min,0.620000,9.000000,25.900000,5.600000,71.000000,0.310000,0.169645,2.648391,108.51000,3.155920
25%,2.200000,16.000000,26.500000,6.150000,86.000000,0.660000,0.242812,3.025750,118.29000,18.392025
50%,3.350000,21.000000,27.900000,6.550000,97.000000,0.775000,0.265745,3.281063,123.29000,20.926985
75%,4.300000,23.000000,28.550000,6.725000,105.000000,0.915000,0.287800,3.483836,129.39750,22.704710
max,8.900000,30.000000,29.700000,7.100000,128.000000,1.340000,0.355000,4.306139,171.48000,33.586820

Information for:  cube7_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,6.400000,12.333333,28.550000,5.933333,200.000000,0.976667,0.288813,3.736927,259.526667,18.314275
std,0.957079,1.966384,0.668581,0.206559,14.142136,0.158072,0.042139,0.365512,5.853073,1.585088
min,5.400000,9.000000,27.600000,5.700000,180.000000,0.700000,0.214280,3.294882,250.390000,15.836100
25%,5.700000,12.000000,28.050000,5.750000,192.500000,0.940000,0.284073,3.424485,257.267500,17.351355
50%,6.150000,12.500000,28.900000,5.950000,200.000000,1.010000,0.288681,3.770736,259.110000,19.155960
75%,7.050000,13.000000,29.000000,6.075000,207.500000,1.042500,0.317314,4.051266,263.840000,19.403948
max,7.800000,15.000000,29.100000,6.200000,220.000000,1.170000,0.331841,4.131367,266.480000,19.501200

Current Simplical Complex:  ['Stratum 3 SUMMER 14-20: ']
Largest shape is:  ['cube0_cluster0', 'cube1_cluster1', 'cube2_cluster2', 'cube2_cluster0', 'cube2_cluster4', 'cube1_cluster5']
Number of nodes is:  6
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,0.978229,26.479167,28.538542,8.117708,35.656250,0.023125,0.316778,2.220078,36.864896,49.011373
std,0.448767,7.062099,2.218030,2.912369,14.040414,0.105315,0.127043,0.994641,14.712410,22.773049
min,0.300000,13.000000,23.100000,1.100000,5.000000,0.000000,0.138000,0.930000,7.640000,12.912610
25%,0.600000,20.750000,27.225000,6.275000,25.000000,0.000000,0.243238,1.535095,25.902500,29.417862
50%,0.910000,26.500000,28.900000,7.450000,34.000000,0.000000,0.286963,1.953708,34.920000,47.595050
75%,1.200000,31.250000,30.100000,9.700000,43.250000,0.000000,0.366923,2.963640,47.067500,66.994948
max,2.600000,47.000000,33.300000,15.500000,71.000000,0.560000,0.959000,5.341000,74.950000,103.860850

Information for:  cube1_cluster1

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000
mean,0.756610,15.638567,29.138983,9.869492,80.237288,0.045763,0.310838,2.270298,79.947627,60.155721
std,0.505926,5.386279,1.779967,2.788230,23.486121,0.142505,0.082656,0.713420,21.680806,29.164658
min,0.320000,9.000000,25.500000,3.300000,36.000000,0.000000,0.180480,1.476000,44.800000,14.228770
25%,0.480000,11.500000,28.050000,7.800000,59.000000,0.000000,0.248715,1.661000,61.070000,38.247000
50%,0.600000,15.000000,29.000000,9.800000,84.000000,0.000000,0.306932,2.021940,80.980000,57.614380
75%,0.875000,18.500000,30.100000,11.600000,99.000000,0.000000,0.353346,2.660678,97.185000,77.337750
max,3.000000,35.000000,34.300000,15.500000,116.000000,0.620000,0.544000,4.758000,125.630000,121.777920

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.0,7.000000,7.000000,7.000000,7.000000
mean,0.412857,11.285714,28.500000,10.871429,111.285714,0.0,0.422709,1.965101,110.132857,74.325619
std,0.068487,2.214670,2.118175,1.783923,6.183696,0.0,0.085783,0.282475,11.460613,10.189243
min,0.320000,10.000000,26.700000,8.800000,99.000000,0.0,0.282000,1.621000,96.440000,62.153790
25%,0.375000,10.000000,27.150000,9.350000,110.000000,0.0,0.383433,1.778500,101.815000,66.772220
50%,0.400000,10.000000,27.600000,10.900000,112.000000,0.0,0.432901,2.021940,105.710000,76.032650
75%,0.450000,12.000000,29.650000,12.300000,116.000000,0.0,0.466599,2.046818,119.760000,78.059145
max,0.520000,15.000000,31.600000,13.100000,116.000000,0.0,0.544000,2.462132,125.630000,92.430160

Current Simplical Complex:  ['Stratum 4 SUMMER 14-20: ']
Largest shape is:  ['cube2_cluster0', 'cube0_cluster0', 'cube1_cluster0']
Number of nodes is:  3
Information for:  cube0_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.0,8.000000,8.000000,8.00000,8.000000
mean,1.108750,27.500000,26.762500,8.325000,27.875000,0.0,0.311161,1.358886,31.73161,57.470310
std,0.232221,4.242641,0.732778,1.601562,6.937218,0.0,0.030317,0.112417,5.18245,6.970028
min,0.850000,23.000000,25.900000,6.900000,21.000000,0.0,0.242197,1.262000,23.99000,46.809130
25%,0.967500,25.000000,26.275000,7.450000,21.000000,0.0,0.307101,1.287779,28.68500,51.815562
50%,1.015000,26.000000,26.750000,7.850000,27.500000,0.0,0.319635,1.297804,31.27500,58.262695
75%,1.237500,28.500000,26.875000,8.500000,31.750000,0.0,0.330938,1.413945,35.68716,62.620812
max,1.530000,35.000000,28.300000,12.000000,38.000000,0.0,0.333938,1.568000,38.57000,66.258580

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,7.000000,7.000000,7.000000,7.00000,7.000000,7.0,7.000000,7.000000,7.000000,7.000000
mean,1.397143,20.857143,27.014286,8.50000,39.428571,0.0,0.287143,1.412476,39.281840,49.587623
std,0.331246,3.625308,0.784068,1.66333,6.373307,0.0,0.044594,0.122183,2.435111,6.130859
min,1.000000,16.000000,26.200000,6.80000,30.000000,0.0,0.240000,1.262000,34.962879,43.351450
25%,1.150000,18.500000,26.350000,7.10000,36.500000,0.0,0.242365,1.299307,38.215000,46.088780
50%,1.350000,20.000000,26.800000,7.80000,38.000000,0.0,0.301000,1.482000,39.430000,47.673550
75%,1.600000,24.000000,27.700000,10.05000,42.500000,0.0,0.319635,1.488360,40.965000,50.987160
max,1.930000,25.000000,28.000000,10.60000,50.000000,0.0,0.345000,1.568000,42.220000,61.936480

Current Simplical Complex:  ['Stratum 5 SUMMER 14-20: ']
Largest shape is:  ['cube6_cluster0', 'cube4_cluster0', 'cube5_cluster0', 'cube0_cluster0', 'cube1_cluster0', 'cube2_cluster0', 'cube0_cluster2', 'cube3_cluster0']
Number of nodes is:  8
Information for:  cube4_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.0,21.000000,21.000000,21.000000,21.000000
mean,2.153333,30.476190,29.557143,15.880952,27.095238,0.0,0.319650,2.595026,29.548095,105.534953
std,0.905281,4.057327,1.192297,2.092754,4.763452,0.0,0.135452,0.474882,3.250244,9.059786
min,0.500000,22.000000,27.600000,12.500000,18.000000,0.0,0.169000,1.511000,21.520000,94.326570
25%,1.900000,28.000000,28.600000,14.700000,23.000000,0.0,0.192887,2.393424,27.990000,98.098050
50%,2.200000,30.000000,29.500000,15.400000,26.000000,0.0,0.289140,2.600000,29.600000,103.351000
75%,2.600000,34.000000,30.700000,16.700000,31.000000,0.0,0.464826,2.760000,31.330000,109.744450
max,4.200000,37.000000,31.700000,19.800000,35.000000,0.0,0.497000,3.436000,35.780000,129.486500

Information for:  cube5_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.0,6.000000,6.000000,6.000000,6.000000
mean,2.016667,26.166667,28.350000,19.583333,31.333333,0.0,0.272250,2.316083,33.723333,136.901368
std,0.884119,2.228602,1.157152,2.387816,4.885352,0.0,0.105223,0.727799,2.898494,11.588508
min,0.700000,23.000000,26.800000,16.300000,23.000000,0.0,0.173000,1.555000,30.960000,119.462400
25%,1.450000,26.000000,27.775000,18.375000,29.750000,0.0,0.206250,1.687000,31.380000,131.041513
50%,2.250000,26.000000,28.100000,19.200000,32.000000,0.0,0.262000,2.244750,32.920000,137.759185
75%,2.675000,26.000000,29.175000,21.150000,35.000000,0.0,0.276500,2.987375,35.990000,143.178067
max,2.900000,30.000000,29.900000,22.900000,36.000000,0.0,0.467500,3.116000,37.660000,152.640790

Information for:  cube1_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000
mean,1.683214,27.000000,29.010714,7.646429,37.178571,0.043214,0.217565,2.375582,39.930357,37.617895
std,0.830894,3.953433,1.275507,2.130638,7.463757,0.119196,0.059569,0.524943,11.603750,9.513446
min,0.620000,20.000000,26.700000,3.400000,21.000000,0.000000,0.139000,1.464000,21.600000,17.851060
25%,0.945000,24.000000,28.275000,6.450000,32.500000,0.000000,0.187387,2.107093,30.012500,32.618400
50%,1.550000,27.000000,29.200000,8.150000,37.000000,0.000000,0.202037,2.403506,37.585000,39.902885
75%,2.150000,29.250000,29.725000,9.350000,41.250000,0.000000,0.213250,2.758986,46.917500,44.107650
max,3.400000,36.000000,31.600000,10.600000,52.000000,0.470000,0.420212,3.279035,62.890000,56.337990

Information for:  cube2_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,2.013077,28.961538,29.461538,11.146154,28.192308,0.021154,0.214269,2.338609,29.769231,56.395755
std,0.957876,4.787323,1.638311,3.512860,8.777331,0.067547,0.074985,0.505168,9.105724,9.571153
min,0.260000,22.000000,26.500000,4.000000,13.000000,0.000000,0.139000,1.464000,15.040000,40.470050
25%,1.400000,26.000000,28.675000,9.500000,21.250000,0.000000,0.171882,2.118810,22.342500,49.580780
50%,1.900000,29.000000,29.850000,10.900000,27.500000,0.000000,0.193077,2.293081,28.860000,56.823795
75%,2.600000,30.000000,30.875000,13.375000,34.750000,0.000000,0.212213,2.685055,35.200000,64.362060
max,4.200000,42.000000,31.700000,18.000000,44.000000,0.310000,0.444069,3.420048,53.190000,76.985400

Information for:  cube3_cluster0

,PREDICTED_WDP,PREDICTED_SECCHI,PREDICTED_TEMP,PREDICTED_DO,PREDICTED_TURB,PREDICTED_VEL,PREDICTED_TP,PREDICTED_TN,PREDICTED_SS,PREDICTED_CHLcal
count,37.000000,37.000000,37.000000,37.000000,37.000000,37.0,37.000000,37.000000,37.000000,37.000000
mean,2.080541,29.054054,29.335135,15.097297,27.351351,0.0,0.240078,2.364704,29.151081,86.741724
std,0.730608,3.843797,1.569716,2.569964,5.458002,0.0,0.095537,0.616952,4.475235,10.615325
min,0.500000,22.000000,27.100000,10.700000,16.000000,0.0,0.147000,1.438000,18.540000,63.289500
25%,1.800000,27.000000,28.100000,13.300000,25.000000,0.0,0.184500,1.900864,26.780000,81.910500
50%,2.300000,28.000000,28.600000,14.700000,27.000000,0.0,0.198950,2.314600,29.600000,87.216900
75%,2.600000,30.000000,30.900000,16.500000,31.000000,0.0,0.256202,2.653500,31.710000,94.482790
max,3.300000,37.000000,31.800000,21.100000,38.000000,0.0,0.511000,3.458000,37.320000,104.232810

# Condensing 1-simplices
Currently, many one simplices that we have contain information that means one of them is a subset of the other. To resolve this, we replace them with one cluster with all the indices in one node.

This is stored in the function `clean_getShapes(scomplex)` function. Below is a comparison of running the two functions

In [ ]:
allComplices = list(jsonData.keys())
print("Standard shape version")
for key in allComplices[0:1]:
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    nodes = scomplex.get('nodes')
    shapes = getShapes(scomplex)
    for shape in shapes:
        indices = []
        for node in shape:
            indices.append(nodes.get(node))
        indices = list(set([item for sublist in indices for item in sublist]))
        print(str(shape) + " : " + str(indices))

print("Clean shape version")
for key in allComplices[0:1]:
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    nodes = scomplex.get('nodes')
    cleanShapes = clean_getShapes(scomplex)
    for shape in cleanShapes:
        indices = []
        npShape = np.array(shape).flatten()
        for node in npShape:
            indices.append(nodes.get(node))
        indices = list(set([item for sublist in indices for item in sublist]))
        print(str(shape) + " : " + str(indices))

# Box plot per shape
Here, we generate box plots for the variables of interest. for each shape in the simplicial complex <br>
TODO: Plot output ideas: <br>
SS, Turb, CHLCal <br>
Vel, TN, TP <br>
Temp, DO, SECCHI <br>

In [ ]:
allComplices = list(jsonData.keys())
for key in allComplices[0:1]: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    shapes = clean_getShapes(scomplex)
    print("number of shapes: ", len(shapes))
    for shape in shapes:
        """
        Hello whoever is using this function
        getBoxplots takes a couple arguments. 
        the big thing that matters here is the 
        strataYear variable. Essentially, the key that allows us to access each simplicial complex is weird.
        Depending on your file system, using the str(key) conversion may cause errors. to resolve this, 
        below is a potential example. Feel free to change it as you go for your use.
        """
        strataYear = str(key).replace(" ","-").replace(":","").replace("[","").replace("]","").replace("'","")
        print(strataYear)
        """
        before: 
        ['Stratum 1 SUMMER 93-00: ']
        after:
        Stratum-1-SUMMER-93-00-
        """
        subdf = getSubdf(scomplex, shape, df_dict.get(key))
        plots = getBoxplots(subdf, shape, strataYear,  
                            filePath = r"C:\Users\forre\Desktop\REU\TDA\Data\TDAOutputs\Boxplots")

# Discovering which indices within the nodes overlap
This code will determine what points in the nodes are overlapping within two nodes.

In [23]:
allComplices = list(jsonData.keys())
for key in allComplices[0:1]: # remove the indices here to get all the strata for all the time periods
    print("Current Simplical Complex: ", key)
    scomplex = jsonData.get(key)
    shapes = clean_getShapes(scomplex)
    print("number of shapes: ", len(shapes))
    result = determineOverlap(scomplex, shapes, verbose = False)
    print(result)

Current Simplical Complex:  ['Stratum 1 SUMMER 93-00: ']
number of shapes:  8
{frozenset({97, 66, 'cube6_cluster1 -> cube5_cluster0: '}), frozenset({'cube2_cluster0 -> cube3_cluster0: ', 51, 22, 87, 72, 56, 76}), frozenset({59, 'cube4_cluster0 -> cube5_cluster0: ', 83, 4}), frozenset({98, 'cube7_cluster1 -> cube8_cluster1: '}), frozenset({67, 44, 'cube1_cluster0 -> cube0_cluster0: '}), frozenset({32, 1, 34, 65, 36, 69, 71, 'cube3_cluster0 -> cube4_cluster0: ', 62, 63}), frozenset({'cube7_cluster1 -> cube6_cluster1: ', 102}), frozenset({20, 'cube5_cluster2 -> cube4_cluster0: '}), frozenset({'cube0_cluster0 -> cube1_cluster0: ', 67, 44}), frozenset({0, 2, 5, 10, 11, 15, 18, 24, 26, 27, 28, 29, 43, 47, 111, 112, 114, 53, 54, 'cube1_cluster0 -> cube2_cluster0: '}), frozenset({0, 2, 5, 10, 11, 15, 18, 24, 26, 27, 28, 29, 43, 47, 111, 112, 114, 'cube2_cluster0 -> cube1_cluster0: ', 53, 54}), frozenset({98, 'cube8_cluster1 -> cube7_cluster1: '}), frozenset({'cube4_cluster0 -> cube5_cluster2: ', 20}), frozenset({'cube5_cluster0 -> cube6_cluster1: ', 97, 66}), frozenset({32, 1, 34, 65, 36, 69, 'cube4_cluster0 -> cube3_cluster0: ', 71, 62, 63}), frozenset({51, 22, 87, 72, 56, 76, 'cube3_cluster0 -> cube2_cluster0: '}), frozenset({59, 'cube5_cluster0 -> cube4_cluster0: ', 83, 4}), frozenset({102, 'cube6_cluster1 -> cube7_cluster1: '})}

# See compare shapes over the years
NOTE: Comparing the largest shape in each.